### ISSUE TITLE
css formatting

### ISSUE THREAD

**Issue by netnr** [microsoft/monaco-editor#1011]
monaco-editor version: 0.14.3
Browser:Chrome
OS: win10
Steps or JS usage snippet reproducing the issue:

Please implement css formatting, thank you!

**Comment by troy351** [comment]
Since the [htmlWorker](https://github.com/Microsoft/vscode-html-languageservice/tree/master/src/beautify) already included [js-beautify](https://github.com/beautify-web/js-beautify) but [cssWorker](https://github.com/Microsoft/vscode-css-languageservice/tree/master/src) doesn't.
Is there any way to reuse it? So that we can format css/less/scss code without manually import `js-beautify` again? @alexandrudima

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
