### ISSUE TITLE
context menu items no longer have hover effects

### ISSUE THREAD

**Issue by troy351** [Microsoft/monaco-editor#1013]
monaco-editor version: 0.14.3
Browser: latest stable Chrome
OS: Win10
Steps or JS usage snippet reproducing the issue:

just see demo here https://microsoft.github.io/monaco-editor/
their background color should change when hovering

**Comment by spahnke** [comment]
Hi,

any news on this one? Although there is a PR associated this still doesn't work in 0.15.1. The background color does not change on hover and the active element has no background color either (e.g. in quickfixes).

<img width="254" alt="contextmenu" src="https://user-images.githubusercontent.com/25029871/48481705-cfe6dd80-e80e-11e8-89e9-81aa341270ef.png">

<img width="246" alt="quickfix" src="https://user-images.githubusercontent.com/25029871/48481714-d5dcbe80-e80e-11e8-9f55-a196a58bc0da.png">

Which CSS classes can I style in the meantime? I found `action-menu-item` for the hover but what about the active selected one?

Thanks!

**Comment by sbatten** [comment]
running from source does not reproduce this issue for me, but when I bundle a release, I can repro. Will take a look tomorrow with @rebornix

**Comment by alexandrudima** [comment]
@sbatten The root cause is the use of `<any>` [here](https://github.com/Microsoft/vscode/blob/2836b09e4b9b8b7c8eb4285f5440e71a4a1b54d7/src/vs/base/browser/ui/actionbar/actionbar.ts#L729)

Once only the editor sources are analyzed, our tree shaker does not find any references to [`MenuActionItem`.`blur`](https://github.com/Microsoft/vscode/blob/2836b09e4b9b8b7c8eb4285f5440e71a4a1b54d7/src/vs/base/browser/ui/menu/menu.ts#L315) and proceeds to shake that code out. But that method is reachable from `ActionBar.updateFocus`. You can see this is a problem when finding all references: Find all references does not find the usage [here](https://github.com/Microsoft/vscode/blob/2836b09e4b9b8b7c8eb4285f5440e71a4a1b54d7/src/vs/base/browser/ui/actionbar/actionbar.ts#L741). This is also a problem when e.g. deciding to rename the method from `blur` to `blur2`, i.e. no compilation errors will be given, but the code will no longer execute, as is the case in the packaged standalone editor.

**Comment by sbatten** [comment]
@alexandrudima ouch! thanks for that information, though. will keep this in mind

**Comment by spahnke** [comment]
Sorry for the spam, but it seems this broke again in 0.15.4

**Comment by rebornix** [comment]
@spahnke 0.15.5 is published with the fix reapplied.
