### ISSUE TITLE
Only Adding CodeCompletionItem without deleting existing one

### ISSUE THREAD

**Issue by liz3** [Microsoft/monaco-editor#1036]
**NOTE**: I know that questions should go on Stackoverflow, but the "Monaco editor" tag on stackoverflow seams quite inactive, so i will ask here.

[languages#registerCompletionItemProvider](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registercompletionitemprovider) will take the provided items if the returned array is not empty, else it will take the auto generated completion list.
My Question: How can i just append own items to the auto generated list?

Regards,
Liz3

**Comment by jrieken** [comment]
this is 
https://github.com/Microsoft/vscode/issues/21611

**Comment by liz3** [comment]
@jrieken this is not my problem, i want to be able to get the Word based suggestions in a way that when providing a own Completion item Provider i can **add** to the existing rather then **replacing them completely**

**Comment by alexandrudima** [comment]
@liz3 I think completion item providers are additive. Did you actually try something out or is this a theoretical problem?

**Comment by liz3** [comment]
@alexandrudima Its simple, i am registering a own CompletionItemProvider, when the array i return has a length of 0(as result is empty) monaco falls back to the word based suggestion(as expected), if though the length is greater than 0 it will only provide the one from the array.
What i would like(in a perfect solution) is a additional parameter in: [provideCompletionItems](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitemprovider.html#providecompletionitems), which is an array containing the auto generated word based suggestions, making it possible to merge them into one big array.
Is there any other way to retrieve the word based suggestions code wise?

**Comment by alexandrudima** [comment]
@liz3 But then your issue is the one @jrieken pointed to. You don't have a problem with another registered completion item provider, you have a problem with the **built-in word suggestions**, which disappear once you provide completions.

As a workaround, you can compute and provide word completions by yourself, it is not super complicated to split a string into words... You can always use the built-in implementation as reference - https://github.com/Microsoft/vscode/blob/095400ad6c5c6f2ac5ce4e9619d8de813e320dc5/src/vs/editor/common/services/editorSimpleWorker.ts#L150:L197
