### ISSUE TITLE
Ability to set different themes to different elements and make colorizeElement independently themed.

### ISSUE THREAD

**Issue by jasonreiche** [microsoft/monaco-editor#1068]
I want to use colorizeElement to provide syntax highlighting of example text in vs theme and then have an editor that is using vs-dark theme.  With just the colorizeElement element configured, the example text appears with the vs theme.  As soon as I add the editor, it changes the theme and associated class on all other elements to vs-dark.

Having only one theme option across all editors and elements seems counter-intuitive.  
If an element is colorized, the work is done and shouldn't be attached to any tokenization system.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
