### ISSUE TITLE
Validation of the constants reassignment

### ISSUE THREAD

**Issue by kirovboris** [microsoft/monaco-editor#1072]
monaco-editor version: 0.14.3
Browser: any
OS:  any

Steps or JS usage snippet reproducing the issue:

JS validation can't detect a constants reassignment. It looks like it's solved in vscode with eslint, but it'd be great to have this behavior in the js validator itself.

![image](https://user-images.githubusercontent.com/3633477/45878275-23a5ef00-bda9-11e8-9061-4faa99b61ea9.png)

![image](https://user-images.githubusercontent.com/3633477/45878310-489a6200-bda9-11e8-8e36-98fdd9b38ba7.png)

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
