### ISSUE TITLE
Question: having trouble running the completion provider example in playground

### ISSUE THREAD

**Issue by wlnirvana** [microsoft/monaco-editor#1075]
monaco-editor version: playground version
Browser:69.0.3497.100 (Official Build) (64-bit)
OS: macOS 10.13.5

I'm a newbie to monaco editor, and cannot trigger the completion popup of the example. Is there any documentation on how to run it?

**Comment by shad** [comment]
I'm seeing the same thing while trying to test out and understand completion.

I've tested in Chrome (69.0.3497.92) and Firefox (60.0.1) on Mac (10.13.6). I can get the completions to fire if I include `quickSuggestion` in the editor definition:
```
monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json",
    quickSuggestions: true
});
```

But then it completes incorrectly (keeping the surrounding quotes):
![2018-10-06 11 00 00](https://user-images.githubusercontent.com/3585/46573182-02233680-c957-11e8-98c6-f96fded0332c.gif)

**Comment by alexandrudima** [comment]
I cannot reproduce, I always get completions correctly shown when I press `Ctrl+Space`.

And it is expected that `"` are doubled. The completion item provider is always returning `insertText: '"lodash": "*"'` regardless of the contents of the document ... because it is a toy example meant to show how the API works. A more involved implementation would check more context around the completion position and return adjusted edits appropriately.

**Comment by s-KaiNet** [comment]
@alexandrudima is it possible to trigger suggestion for JSON without pressing `Ctrl+Space`, i.e. automatically as you type the first quotation mark?
