### ISSUE TITLE
Loading "vs/base/common/worker/simpleWorker" failed

### ISSUE THREAD

**Issue by fpsqdb** [microsoft/monaco-editor#1076]
monaco-editor version: 0.14.3
Browser: electron 2.0.10
OS: windows 10 1803
Steps or JS usage snippet reproducing the issue:
I follow this guide [https://github.com/Microsoft/monaco-editor-samples/blob/master/electron-amd/electron-index.html](https://github.com/Microsoft/monaco-editor-samples/blob/master/electron-amd/electron-index.html)

![qq 20180925174825](https://user-images.githubusercontent.com/6482819/46006916-398a1b80-c0eb-11e8-85b6-b37e1ea2f818.png)

![qq 20180925174644](https://user-images.githubusercontent.com/6482819/46006863-1bbcb680-c0eb-11e8-8f1c-d7060d2f8e3f.png)

and I can't find `vs/base/common/worker/simpleWorker.js` file in the `monaco-editor` package.

**Comment by rebornix** [comment]
@fpsqdb can you try clean the node_modules folder and do a fresh install and see if you still have the problem? I can't reproduce by having this repo and run on a fresh new machine.

**Comment by Canna71** [comment]
I am receving this error, in my electron application, since I enabled node integration in web worker through the following option:
webPreferences: {
            nodeIntegrationInWorker: true
        }
This seems to lead monaco-editor loader to believe it is running under an actual Nodejs and so trying to load the module in a different way.
Is there any way to force the monaco loader environment to be the browser or electron-renderer?
I already have process.browser = true for some other reason but it's not working.

Thank you.

**Comment by alexandrudima** [comment]
I don't think we ever tested the loader in a node integration enabled electron web worker. I'm not sure, should it use `importScript` or `fs` to load files in such a context? Perhaps this can be detected and handled [here]( https://github.com/Microsoft/vscode-loader/blob/e8d11ad1c0b68658b2d276dbfba0c4a0c1fd3258/src/core/main.ts#L81 )
