### ISSUE TITLE
Markup is broken when used with Angular 6+

### ISSUE THREAD

**Issue by simerlec** [Microsoft/monaco-editor#1124]
monaco-editor version: 0.14.3
monaco-editor-webpack-plugin: 1.5.4
Browser: Chrome (69.0.3497.100)
OS: MacOS High Sierra (10.13.6)
Angular: 6.1.0

Hello,
since the webpack plugin became available (https://github.com/Microsoft/monaco-editor-webpack-plugin) we wanted to upgrade from @timkendrick/monaco-editor to the "real deal". The general setup went fine and I'm able to create the editor but the markup seems completely broken. At first I thought there's something interfering since the editor is somewhat nested in our product. I created a new project using the angular-cli (@angular/cli@6.2.5), changed the builder inside angular.json to be able to modify the webpack config and add the MonacoWebpackPlugin and added the editor to the page.

**ng new** creates a default component which I modified to this:

```javascript
import { Component, ViewChild, OnInit } from '@angular/core';
import * as monaco from 'monaco-editor';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'monaco-webpack-test';
  @ViewChild('container')
  container;
  ngOnInit(): void {
    monaco.editor.defineTheme('theme', {
      base: 'vs-dark',
      inherit: true,
      rules: [{ background: '2f3d47', token: '' }],
      colors: {
        'editor.background': '#2f3d47',
        'editor.lineHighlightBackground': '#d3d3d331'
      }
    });

    monaco.editor.setTheme('theme');
    monaco.editor.create(this.container.nativeElement, {
      value: 'console.log("Hello, world")',
      language: 'javascript'
    });
  }
}
```

using the following template:

`<div #container class="container"></div>`

and css:
`.container {
  width: 100%;
  height: 400px;
}`

which results in this:
<img width="1752" alt="screenshot 2018-10-18 13 56 29" src="https://user-images.githubusercontent.com/5793380/47152697-b620ac00-d2dd-11e8-8fad-e283ee8b6290.png">

Is there any obvious thing I'm doing wrong?

Thanks

**Comment by simerlec** [comment]
Ok, so apparently it has something todo with the styles not being loaded correctly, due to webpack configuration - since this is not really related to the editor itself I'll close this issue and reopen on the webpack side.

**Comment by prabal77** [comment]
facing the same issue. Did you find any solution?

**Comment by simerlec** [comment]
Yeah, I did - "lucky" for me I ejected the project a long time ago due to the fact that I needed to change the webpack config. To get it to work correctly all what was really necessary was a css processing using some loaders in the webpack module.exports module rules:

```
{
        include: [
          path.join(process.cwd(), 'src/styles.css'),
          path.join(process.cwd(), 'node_modules/monaco-editor'),
        ],
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],    // <-- note: the order of application is right to left
},
```

depending on your setup you might need to exclude it from some other css processing.

**Comment by scottlogic-alex** [comment]
That search scope is broader than I'd recommend. By telling it to pick up "all css under monaco-editor/", you're grabbing the source _and_ minified versions (and smashing them together).

I'd recommend scoping it to: `node_modules/monaco-editor/esm` to avoid clashes (since the same rules are specified also in `dev/` and in `min/`).

Even better would be to just point it at a single file; there are bundles available at `node_modules/monaco-editor/dev/vs/editor/editor.main.css` and (minified) `node_modules/monaco-editor/min/vs/editor/editor.main.css`.

In our case: we didn't go as far as to change our webpack config. We have a global styles file at `src/styles/main.scss`, and inside there we were able to add an import:

```sass
@import '~monaco-editor/min/vs/editor/editor.main';
```

Downside of this approach was that it runs the whole file through a minification process again. It'd be better to configure it as vendored CSS in Webpack (somehow). But this was an acceptable stopgap measure.

**Comment by simerlec** [comment]
@scottlogic-alex thanks for the writeup and I completely agree. In the end I also removed it from webpack and resorted to the global import. Honestly I really disliked "messing" with webpack, especially since my project config can be considered ancient by now.
