### ISSUE TITLE
How do i use middle click to navigate instead of select?

### ISSUE THREAD

**Issue by nathan1658** [microsoft/monaco-editor#1130]
I found this for Visual Studio Code [https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MiddleClickScroll](url), is this possible with Monaco Editor? Thanks

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
