### ISSUE TITLE
How to use manaco editor in ember

### ISSUE THREAD

**Issue by MR-H0200** [microsoft/monaco-editor#1142]
Hi 

I am working on a ember project.

I want to use a html/css/js editor. 

I saw https://github.com/MiguelMadero/ember-monaco-editor but it uses iframe to load manaco it there a alternative way to use manaco editor in ember project

Thankz in advance 😄

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
