### ISSUE TITLE
types for all the esm files

### ISSUE THREAD

**Issue by veeramarni** [microsoft/monaco-editor#1197]
**monaco-editor version:** 0.15.4

**Steps or JS usage snippet reproducing the issue:**

I have noticed some types missing in the api but the code exist. For example, the api for ITexmodel doesn't show the following method exist but it exist under `esm/vs/editor/common/textModel.js`. Can we have types created for all those files like `esm/vs/editor/common/textModel.d.ts` ? It would help us in case if we want to use one off methods that exist in the package but not exposed in `*.api.d.ts`

```
    TextModel.prototype.getLanguageIdentifier = function () {
        return this._languageIdentifier;
    };
```

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
