### ISSUE TITLE
Make twitter account @monacoeditor

### ISSUE THREAD

**Issue by natebass** [microsoft/monaco-editor#120]
Would you guys consider making a twitter account? [@codemirror](https://twitter.com/codemirror) has one and you can see from its [recent activity](https://twitter.com/search?q=%40codemirror&src=typd) that people use it.

**Comment by fdeitelhoff** [comment]
Would be awesome for promoting the monaco editor I think.

**Comment by rcjsuen** [comment]
The VS Code [@code](https://twitter.com/code) account is quite active so Twitter PR isn't exactly new for Microsoft. I too feel like this would be a worthy endeavour to venture into.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
