### ISSUE TITLE
Add an option to enable CORS for the editor css file

### ISSUE THREAD

**Issue by sigalvo** [microsoft/monaco-editor#1217]
When the editor.main.min.css is loaded from CDN, a crossorigin': 'anonymous attribute need to be added to the link node in order to allow CORS. Otherwise the css file considered as un-trusted by the browser.
Is it possible to add the attribute to the link node, or to add a boolean option to add it?

Thanks,
Violet.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
