### ISSUE TITLE
Disable the diff editor to compute diff

### ISSUE THREAD

**Issue by XDfield** [microsoft/monaco-editor#1236]
Hi !I use monaco to make an app for auditing merge requests, which is got through gitlab api.

I create a diff editor and load two file. But **when my file content is a little big(over 20w lines), the editor didn't show the diff info.** Small files work fine. 

Is this because the editor is calculating diff?
So can I disable the diff editor to compute diff instead of using the diff info which I get through api?

**Comment by alexandrudima** [comment]
@XDfield The diff is computed on a web worker, so it is computed asynchronous. Currently, the API is that you have to provide the original and the modified version and the diff will be computed and always updated as you type.

AFAIK we have a quite performant diff algorithm so that should not be stuck for a very long time, unless you have very large files? How large is "20w lines"? What does "w" stand for?

**Comment by XDfield** [comment]
"20w" means 200,000. That is my bad habit, sorry for the misleading.
The situation is that, the file contains 200,000 lines, and has changed about 10 lines.When I load this file, it takes about 4 ~ 5 seconds for computing diff.
Is there any way to spead up this process ? Thanks for your help. : )

**Comment by alexandrudima** [comment]
Unfortunately not.

Currently, we need to create a web worker, send both files there, run the diff algorithm there, and then return the results.
