### ISSUE TITLE
Validation message doesn't support markdown string

### ISSUE THREAD

**Issue by Zeroundefined** [microsoft/monaco-editor#1264]
**monaco-editor version:** 
    "monaco-editor-core": "0.12.0",
    "monaco-languages": "1.0.0",
**Browser:**
**OS:** 

![image](https://user-images.githubusercontent.com/40539227/50880105-360b6d80-1418-11e9-95fb-ecb685344652.png)
![image](https://user-images.githubusercontent.com/40539227/50880157-64894880-1418-11e9-9140-350115ad00fe.png)

It seems monaco.editor.setModelMarkers doesn't support markdown message。Is there any other way to support markdown?

**Comment by alexandrudima** [comment]
I am not 100% sure if markers support markdown or not. @jrieken @sandy081 maybe you know?

**Comment by sandy081** [comment]
Marker messages does not support markdown.

**Comment by bodinsamuel** [comment]
Hello,
We are using `setModelMarker` to display deprecated code in the UI and take this opportunity to show some links and help on how to migrate.
We would love to have some clickable links and formatting too.

+1 on this

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

---

However, I think there is a feature request for this for VS Code (an implementation for that would also add it to the monaco editor).
