### ISSUE TITLE
[Feature Request] Use resizeObserver for editor layout.

### ISSUE THREAD

**Issue by atilkan** [microsoft/monaco-editor#1266]
The way of checking element width every 100ms is not ideal. Use resizeObserver instead. 
https://developers.google.com/web/updates/2016/10/resizeobserver

**Comment by rebornix** [comment]
We can probably user MutationObserver for IE.

**Comment by dcecile** [comment]
Instead of using [`automaticLayout`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#automaticlayout) with its "severe performance impact", my current workaround looks like this:

```
div.page (display flex column)
    div.content-before
    div.wrapper (flex grow, position relative)
        div.container (position absolute, width 100%, height 100%)
            monaco
    div.content-after
```

- The wrapper div fills the available space on the page page (space not used by content before or after)
- Because the container has position absolute, Monaco won't be able to "lock in" extra space on the page during page shrinking
- When the wrapper div resizes (I'm using [`react-resize-detector`](https://github.com/maslianok/react-resize-detector)), I call `editor.layout()`

This works for both growing and shrinking the page. Monaco quickly resizes to the correct size.

**Comment by atilkan** [comment]
@dcecile This is not related to your use case. That lib uses resize-observer-polyfill which uses mutation observer. We don't need to fake or polyfill. And this request asks for a implementation change.

**Comment by nrayburn-tech** [comment]
@alexdima I think that I can implement something for this, but wanted to run my ideas by somebody before working on it.

Modify the ElementSizeObserver to create a MutationObserver on the editor element.  When the observer is triggered, we will update the editor size.  It is my understanding that MutationObserver only catches changes to the DOM, so we would need to bind another listener to the window resize event.

As mentioned above, a ResizeObserver can be used instead for the browsers that support it.

Does that sound correct?  If so, I can work on creating a PR for it.

**Comment by alexdima** [comment]
@nrayburn-tech :+1: PR welcome

**Comment by nrayburn-tech** [comment]
@alexdima Should this also be used in the [diffEditorWidget](https://github.com/microsoft/vscode/blob/beaf391bc53136912e4f0bbdfb7844ad954247db/src/vs/editor/browser/widget/diffEditorWidget.ts#L360)?

**Comment by alexdima** [comment]
@nrayburn-tech Good point. I have pushed https://github.com/microsoft/vscode/commit/88146d9a54893f932d92eed4d92e840bef0766af for this.
