### ISSUE TITLE
could monaco support the 3-way diff view

### ISSUE THREAD

**Issue by shi-yan** [microsoft/monaco-editor#1295]
This is a feature request. The current diff view supports 2 way diff. but in case of merging and resolving conflicts, a three way diff view would be nice.

![](https://www.araxis.com/merge/documentation-windows/en/img/screenshots/three-way-text-comparison.png)

**Comment by rcates1** [comment]
This would be excellent

**Comment by rossdrew** [comment]
This is the clearest merge view for most people and would be a great addition.

**Comment by demonguy** [comment]
That's what i'm looking for. Is it going to be implemented?

**Comment by demonguy** [comment]
2 years already, seems Micrsoft is not going to do anything about it

**Comment by hediet** [comment]
VS Code has a three way merge editor now. However, currently, it is not part of the monaco editor release and we currently don't have plans to change that.

---

We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
