### ISSUE TITLE
Parcel + CSS worker = Cannot redefine property: Position

### ISSUE THREAD

**Issue by oldrich-s** [microsoft/monaco-editor#1327]
**monaco-editor version:** 0.15.6
**Browser:** Chrome
**OS:** Win64

**Steps or JS usage snippet reproducing the issue:**

1. Follow https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md#using-parcel to compile Parcel.
2. Load a *.css file into Monaco in the Browser
3. I get `Cannot redefine property: Position`

If I add `configurable: true` to all occurrences of `Object.defineProperty` in the `css.worker.js` then the error disappears.

Is it a `Parcel` related bug or a `Monaco` related bug?

**Comment by oldrich-s** [comment]
@AaronGillBraun Could you please take a look at it?

**Comment by AaronGillBraun** [comment]
I was able to reproduce the problem, but I'm getting some other errors as well. Both errors only occur when using the css language worker, and the `Cannot redefine property` error is followed by multiple `Unexpected usage` errors originating from the `loadForeignModule` method inside `simpleWorker.js`.

These `Unexpected usage` errors seem to be due to the `foreignModuleFactory` property being undefined when monaco is trying to make a new worker, but I don't see how that could cause the `Cannot redefine property: Position` error... Because the css worker does work when using webpack, I'm inclined to believe that it is in fact a parcel problem but I'm not 100% sure.

My use case never involved using the language workers, meaning I never had to deal with this error, so I apologize for not being able to offer any more insight. I know this doesn't help but I ended up also switching over to webpack simply due to a number of complications I had surrounding parcel.

**Comment by alexandrudima** [comment]
Interestingly, using javascript (which also uses a web worker) works fine using the parcel packing documentation. @AaronGillBraun, I've also updated the sample in https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-parcel with your method of doing it.

It might be something specific about the shape of the code loaded in the CSS worker that breaks things.

**Comment by lleighton** [comment]
I'm also seeing this error when using parcel to build the css worker, I noticed that someone has reported it could be down to double export of Range, Position etc from https://github.com/Microsoft/vscode-css-languageservice. (Apologies I can't find the issue and link that mentioned it else I would have added the reference.)

I may try switching to webpack to see if that fixes unless there's an easy fix?

**Comment by aeschli** [comment]
I cleaned up the exports in the css service. This should work with the upcoming monaco editor release.

**Comment by alexdima** [comment]
Thank you @aeschli
