### ISSUE TITLE
Native scrollbars

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#1334]
I've been integrating monaco in an app of mine, and probably the single biggest issue I have with it from an UI point of view is that it uses a custom scrollbar implementation, which makes it look a bit off with the rest of the app.

Would it be possible for it to use the native scrollbars instead in the future?

**Comment by alexandrudima** [comment]
We've had 3 reasons why we moved to custom scrollbars:
- Edge (or IE at the time) could not go above 1.5M px. That was about 70k-80k lines, it simply could not scroll more than that at that time.
- native scrollbars cannot be blocked from scrolling, i.e. first they scroll, and only afterwards we receive the scroll event. Due to our virtual scrolling, this would sometimes end up flashing a frame of whiteness until we received the event and had a chance to render.
- the overview ruler where we render find matches, etc.

I don't think we would want to invest into going back to native scrollbars, although the scrollbars can be customized to look more native-like...

**Comment by fabiospampinato** [comment]
I see 🤔 The issue about "uncancellable" scrolls seems to be the biggest show stopper here.

> the scrollbars can be customized to look more native-like...

I don't think I'm going to take that route, as otherwise I would have to think about how native scrollbars look under each OS/OS version, and ultimately they won't behave exactly the same so I guess it's better to make the distinction clear instead.

Thanks for the detailed answer.
