### ISSUE TITLE
Sogou IME does not work in Edge/IE

### ISSUE THREAD

**Issue by roblourens** [microsoft/monaco-editor#136]
Test-item Microsoft/vscode#11146 
- OS Version: Win 10 Anniversary Update (14393)
1. Install the Sogou IME per the directions here - https://github.com/Microsoft/vscode/wiki/IME-Test

Edge: When I type `ni`, the IME prompt does not appear. It works fine in VS Code and Chrome. Same if I use the 'npm' version of the editor, so not a regression.

IE: When I type `ni`, the prompt does appear, but when I press space or select an option, the text is not inserted into the editor. In the 'npm' version, the text is inserted but monaco also duplicates some of the text surrounding the character.

**Comment by alexandrudima** [comment]
This test item came in this month and we never did anything special for Sogou before. Good to know that something is off, but given the Microsoft Pinyin method works no action for now.

**Comment by jitao13** [comment]
Has this problem been solved？

**Comment by jitao13** [comment]
I had the same problem

**Comment by alexdima** [comment]
The Monaco Editor is generated from the source code of VS Code and in order to improve VS Code we must be able to use modern browser features, like Flexbox, which has a number of bugs that we cannot workaround in IE11.

We have investigated the cost of fixing all the problems of IE11 and have decided to discontinue support for IE 11. The last Monaco Editor version that was tested on IE 11 is `0.18.1`.

Thank you for your understanding.
