### ISSUE TITLE
Failed to construct 'Worker' WARNING and Unexpected usage ERROR

### ISSUE THREAD

**Issue by Aralhi** [microsoft/monaco-editor#1373]
**monaco-editor version:** 0.16.0
**Browser:** chrom 72.0.3626.119
**OS:** macOS 10.13.6
**webpack:**  4.29.6
**Steps or JS usage snippet reproducing the issue:**
I use monaco editor with react and typescript
```
import * as monaco from 'monaco-editor';
const editor = monaco.editor.create($editor.current, {
      value: [
        'function x() {',
          '\tconsole.log("Hello world!");',
          '}'
        ].join('\n'),
      language:"javascript"
    })
```
When i refresh, there are one warning and one error
warning is 
```
simpleWorker.js:33 Failed to construct 'Worker': Script at 'http://localhost:8083/editor.worker.js' cannot be accessed from origin 'http://localhost:7002'.
logOnceWebWorkerWarning @ simpleWorker.js:33
push../client/node_modules/_monaco-editor@0.16.1@monaco-editor/esm/vs/editor/common/services/editorWorkerServiceImpl.js.EditorWorkerClient._getOrCreateWorker @ editorWorkerServiceImpl.js:298
simpleWorker.js:33 Failed to construct 'Worker': Script at 'http://localhost:8083/typescript.worker.js' cannot be accessed from origin 'http://localhost:7002'.
```
As this warning can tell, web worker cannot loaded from a different domain. Due to the worker js like 'editor.worker.js' and 'typescript.worker.js' is generate by monaco, is can't handle worker js by 'worker-loader' like this
```
// webpack.config.js
{
  module: {
    rules: [
      {
        test: /\.worker\.js$/,
        use: { loader: 'worker-loader', options: { inline: true } }
      }
    ]
  }
}
```
and error is
```
languageFeatures.js:170 Error: Unexpected usage
    at EditorSimpleWorkerImpl.push../client/node_modules/_monaco-editor@0.16.1@monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:470)
    at webWorker.js:39
```

**Comment by PavelGriza** [comment]
@Aralhi,
This issue happens because web workers are not allowed to load scripts from different domains.
You can find a workaround [here](https://github.com/microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md).

If you generate language scripts with [Monaco Editor Webpack Loader Plugin](https://github.com/microsoft/monaco-editor-webpack-plugin) then you must be having something similar in your webpack.config.js:

```js
const webpack = require('webpack');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

const ASSET_PATH = 'http://localhost:8083/';

module.exports = {
    // ...
    output: {
        globalObject: 'self',
        publicPath: ASSET_PATH
    },
    // ...
    plugins: [
        new MonacoWebpackPlugin({
            languages: ['typescript']
        }),
        new webpack.DefinePlugin({
            'process.env.ASSET_PATH': JSON.stringify(ASSET_PATH)
        })
    ]
};
```

Before your editor is instantiated you should provide your own definition of `window.MonacoEnvironment` with your own implementation of `getWorkerUrl` function: 

```js
window.MonacoEnvironment = {
    getWorkerUrl: function (moduleId, label) {
        if (label === 'typescript' || label === 'javascript') {
	    return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
	        importScripts('${process.env.ASSET_PATH}/typescript.worker.js');`
	    )}`;
        }

	return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
	    importScripts('${process.env.ASSET_PATH}/editor.worker.js');`
	)}`;
    }
}
```

The idea is to load scripts with `data:text/javascript` worker URL.
[importScripts](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) will import a script provided by `'${process.env.ASSET_PATH}/editor.worker.js'` URL into worker's global scope. In your case this URL should directly point at 'http://localhost:8083/editor.worker.js' and 'http://localhost:8083/typescript.worker.js'

**Comment by alexdima** [comment]
@Aralhi Have you resolved your issue?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
