### ISSUE TITLE
Applying \r\n as two seperate edits causes the editor to render 2 new lines instead of 1

### ISSUE THREAD

**Issue by Place1** [microsoft/monaco-editor#1427]
Hey, I think i've run into a bug with how monaco handles CR LF characters. If you use the below script in the [monaco playground](https://microsoft.github.io/monaco-editor/playground.html) you can see that applying `\r\n` as two separate edits causes the editor to display 2 lines rather than 1. If you apply `\r\n` in a single edit then this isn't a problem.

**monaco-editor version:** playground
**Browser:** firefox
**OS:** windows 10

**Steps or JS usage snippet reproducing the issue:**
```javascript
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "hello",
	language: "javascript"
});

editor.getModel().applyEdits([
    {
        text: '\r',
        range: new monaco.Range(1, 1, 1, 1),
    },
]);

editor.getModel().applyEdits([
    {
        text: '\n',
        range: new monaco.Range(1, 2, 1, 2),
    },
]);

console.log(JSON.stringify(editor.getModel().getValue()))

```

**Comment by alexdima** [comment]
This is as designed. By design, we do not allow a file to be in a mixed line ending situation. Therefore, if the model is configured to have `\r\n\` as EOL sequence, when you insert `\r`, it will be "fixed" to `\r\n`. Also, when you insert `\n`, it will be "fixed" to `\n`.

There are some people who would still want mixed line endings in their files 🤷‍♂ ... Let's track that at https://github.com/microsoft/vscode/issues/127
