### ISSUE TITLE
Special highlighting for JS functions, methods, prototypes 

### ISSUE THREAD

**Issue by justintaylor-dev** [microsoft/monaco-editor#1471]
Is there a syntax highlighting token for JavaScript functions, methods, prototypes? Looks like they get lumped into the identifier token with variable names. Thanks!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
