### ISSUE TITLE
Avoiding breaking Esc key keydown events

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#1475]
**monaco-editor version:** 0.17.0
**Browser:** Chrome 70-something
**OS:** macOS 10.14

[Here](https://github.com/microsoft/vscode/blob/d13ee527b679ea619a1f761bbffa3c9b26af7eeb/src/vs/editor/browser/controller/textAreaInput.ts#L135-L139) for some reason the editor is set to always call `preventDefault ()` whenever the Esc key is pressed, this breaks my app because I'm doing something when the Esc key is pressed, and the shortcuts library I'm using for managing my shortcuts exits immediately if a keyboard event has been already handled by somebody else (rightfully so IMHO), i.e. `preventDefault` has been called on it.

The linked url doesn't exist anymore, retrieving it back via the wayback machine ([here](http://web.archive.org/web/20150110232316/http://msdn.microsoft.com:80/en-us/library/ie/ms536939(v=vs.85).aspx)) I'm seeing a page mentioning HTML 4 and IE 4, so I guess those lines of code are not needed anymore.

Can those lines of code be removed so that I can keep listening on the `Esc` key keydown events properly?

**Comment by alexdima** [comment]
The problem is the following:
- when selecting some text in the editor, we have a tiny `<textarea>` in which we also place the selected text. This is done for accessibility and for input composition purposes.
- to determine what is typed, we remember what state we "wrote" to the tiny `<textarea>`, such as the text we placed in there and the native selection we placed in there.
- after `input` events, we "read" from the tiny `<textarea>` and discover what is the new state inside of it (like what is the new text and what is the new native selection). We then painstakingly deduce what has happened by comparing the state we wrote vs the state we read. Basically that is how text input works in the Monaco Editor and it is done like this to cover as many as possible input systems (IMEs)
- finally, the problem of `Escape`: If `Escape` is not handled by our keybinding dispatching service, so `preventDefault()` is not called on the `keydown` event, browsers will do their default, which is to collapse their selection. This makes it that the state we "wrote" is no longer valid and it would then result in us messing up the input deduction phase and entire lines getting inserted when pressing `Escape`.

I'm not 100% sure what you are trying to accomplish, could you just add a capturing `keydown` listener to be the first one to receive `Escape`, or could you not participate via the `addCommand` in the keybinding dispatching service itself ?

**Comment by fabiospampinato** [comment]
Thanks for the explanation, I see no way to avoid calling `preventDefault` on esc `keydown`s and not break things then, so I'm closing this issue.

> I'm not 100% sure what you are trying to accomplish

I just want to handle keyboard events, so for instance if the user presses Esc the app will close a popover or something. The thing is if there are 10 possible  things to dismiss we don't want to dismiss all of them with a single keypress, so we have to detect when events have been handled by somebody else, i.e. `preventDefault` was called on them. But actually I think just calling `stopImmediatePropagation` on the handled events and not trying to detect anything would be a better option.

> could you just add a capturing keydown listener to be the first one to receive `Escape`

I could, but I think it'd get a little messy, I don't want to special-case this and the jQuery-like APIs I'm using for attaching event handlers only deal with the bubbling phase.

> or could you not participate via the addCommand in the keybinding dispatching service itself ?

I could, but I'd rather do the opposite, take control of (most) keyboard events and telling the editor what to do.
