### ISSUE TITLE
Feature Request: Add syntax highlighting for Microsoft AL language

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/monaco-editor#1489]
Today highlighting in VS Code is achieved with the appropriate extension. In i.e. Azure DevOps al-Code is not highlighted.

Info on AL:
<https://github.com/microsoft/AL>

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
