### ISSUE TITLE
How to set all detail visible  in CompletionList

### ISSUE THREAD

**Issue by bupttl** [microsoft/monaco-editor#1528]
**monaco-editor version:** 0.X.Y
**Browser:**
**OS:** 

**Steps or JS usage snippet reproducing the issue:**

The detail prop is visible only when current line of suggestion is active.
Is there any prop that can be set to make all detail visible?

![image](https://user-images.githubusercontent.com/2988284/62272385-8bb76e00-b46d-11e9-8422-4e6b5a503c94.png)

**Comment by Rifdhan** [comment]
While not the exact thing you asked for, I found a solution that worked for my use case by using the `qualifier` field on the `CompletionItemLabel` of the `CompletionItem` instead. This field is always shown for all completions. Relevant docs page: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitemlabel.html

<img width="305" alt="image" src="https://user-images.githubusercontent.com/8062299/104388270-ba07fc80-54ed-11eb-9f2c-f6cdb58c86da.png">

**Comment by bozerkins** [comment]
Technically now this is possible by using CompletionItemLabel - https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.CompletionItemLabel.html

Instead of setting label as a string here - https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
Set it as an object with "label", "description" and/or "detail" option. Those will be permanent in the view.

Example suggestion item
```javascript
{
  label: {label: '"lodash"', description: 'description', detail: ' -> detail'},
  kind: monaco.languages.CompletionItemKind.Function,
  documentation: 'The Lodash library exported as Node.js modules.',
  insertText: '"lodash": "*"',
  range: range
}
```

Hope it helps. I think this issue can be closed.
