### ISSUE TITLE
Add find controller in the API

### ISSUE THREAD

**Issue by siddhant1** [microsoft/monaco-editor#1562]
Is there any way to toggle wholeWord find without opening find panel?

**Comment by alexdima** [comment]
I am not 100% sure, what do you mean?

**Comment by siddhant1** [comment]
I want to enable/disable wholeword search toggle using editor APIs (unfortunately not able to find it in docs)

**Comment by alexdima** [comment]
There is no API at this time to control the find widget settings.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
