### ISSUE TITLE
If nextEmbedded: "@pop" isn't at the root level of an action, it's not recognized

### ISSUE THREAD

**Issue by sdegutis** [microsoft/monaco-editor#1598]
**monaco-editor version:** 0.18.1
**Browser:** Safari 13.0.1
**OS:** macOS 10.14.6

**Steps or JS usage snippet reproducing the issue:**

First let me say, I found a workaround for this that gets the job done for me. So I don't personally need this bug fixed. I'm only mentioning it here in case it's not already known about, so that you can be made aware.

When the `action` of `myrule` is:

```js
{ cases: {
  '@default': { token: 'invalid', next: '@pop', nextEmbedded: '@pop' },
}}
```

or:

```js
['keyword', 'string', { token: 'type', next: '@pop', nextEmbedded: '@pop' }, 'keyword']
```

then I get this error:

> [Error] Error: monarch-language-javascript: no rule containing nextEmbedded: "@pop" in tokenizer embedded state: myrule.Hi
> 
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:746:681
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:1196:688
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:1196:883
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:1195:990
> h@http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:989:799
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:995:826
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:995:494
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:994:453
> http://127.0.0.1:8080/node_modules/monaco-editor/min/vs/editor/editor.main.js:994:209
> 	(anonymous function) (editor.main.js:38:771)

**Comment by alexandrudima** [comment]
@sdegutis This is indeed a limitation in the way in which you need to write `nextEmbedded: @pop` actions, such that we can find the embedded mode ending offset efficiently.

e.g. when tokenizing something like `<script>// some JS ... </script>`, we want to find the JS cut-off point `</script>` even before going inside the JS block, so the JS tokenizer doesn't even get to see the `</script>` part, or eat it up by accident... 

In order to find this efficiently, we need that one of the top rules of the state has an explicit `nextEmbedded: '@pop'` action...

**Comment by sdegutis** [comment]
Thanks, this makes sense. I think this can be considered a non-issue then so I'll close it.
