### ISSUE TITLE
Problem of offset between text and cursor in Chrome (MacOS)

### ISSUE THREAD

**Issue by templth** [microsoft/monaco-editor#1618]
**monaco-editor version:** 0.18.1
**Browser:** Chrome
**OS:** MacOS

**Steps or JS usage snippet reproducing the issue:**

Using the editor in an angular application, we can see an offset between text and cursor. For example, if we want to erase a character at the position of the cursor, the character at two or three position before is deleted.

This only occurs using Chrome under MacOS. We don't have this behavior for Firefox / Safari on MacOS and Chrome / Firefox on Linux.

**Comment by alexdima** [comment]
@templth Do you have a reproducible HTML? Are you using custom fonts? The editor will measure the fonts at creation time and if fonts are loaded after the fact, it might still have the font measurements since before the font finished loading. You can reset the editor's font measurements cache via `monaco.editor.remeasureFonts()`.

**Comment by templth** [comment]
@alexdima thanks for your answer!

I fixed this problem based on the stackoverflow answer:

https://stackoverflow.com/questions/58271107/offset-between-text-and-cursor-with-the-monaco-editor-angular-under-chrome-m

 It was some styles we added on .editor-container .view-line (`font-family`, `font-size` and `letter-spacing`).
