### ISSUE TITLE
Add await helper support

### ISSUE THREAD

**Issue by ErkoKnoll** [microsoft/monaco-editor#1620]
With the new TS 3.6 release TS is now able to notify if the user has forgotten to use await keyword as following: `Did you forget to use 'await'?`, including appropriate quick fix.

After I upgraded to 18.1 I cannot see that help being available on Monaco the same way as it is available in VS Code.

Is there a property that needs enabling to get it working?

**Comment by spahnke** [comment]
Support for quickfixes in general was added recently with https://github.com/microsoft/monaco-typescript/pull/40. I guess this will be included in the next release.

**Comment by spahnke** [comment]
Based on your issue I also created https://github.com/microsoft/monaco-typescript/pull/48 so that the related information will be shown in the error message. Quickfixes are available regardless, this PR only adds the additional text to the error message.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
