### ISSUE TITLE
[Feature Request] defaultTabSize setting for (1) editor and (2) file types

### ISSUE THREAD

**Issue by BennyHinrichs** [microsoft/monaco-editor#1665]
I know there have been other issues that somewhat touched on this (#259, #270). Everything says that tab size is a model property, which is fine. It would be quite nice, however, if we could set it once on editor creation, then the editor calls `updateOptions` every time you make a new model. Currently you can set a default for HTML ([docs link](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.html.htmlformatconfiguration.html#tabsize)), but not for any other file type. It would be great if you could do

1. an editor-wide setting that would get applied to all new models
1. a file extension specific setting that would get applied to all new models of that type

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
