### ISSUE TITLE
How can I put `Paste` to context menu

### ISSUE THREAD

**Issue by wang12124468** [microsoft/monaco-editor#1674]
**monaco-editor version:**  any
**Browser:** any
**OS:**  any

**Steps or JS usage snippet reproducing the issue:**

How can I put `Paste` to context menu ?

**Comment by IamFonky** [comment]
This may help you 
``` typescript
  editor.addAction({
    id: "myPaste",
    label: "Paste",
    keybindings: [m.KeyMod.CtrlCmd | m.KeyCode.KEY_V],
    contextMenuGroupId: "9_cutcopypaste",
    run: (editor) => {
      alert("Add your custom pasting code here");
    }
  });
```

See [this example](https://codesandbox.io/s/monaco-editor-contextmenu-oni1f)

**Comment by wang12124468** [comment]
Thank you, @IamFonky . However I want use the  native `Paste`.

**Comment by IamFonky** [comment]
This issue has been discussed many time and it seem that the paste command is available in the context menu only on IE for security reasons.

See issue #391 .

I can't help you more because copy/pasting is really a mess with JS, see [this link](https://stackoverflow.com/questions/51395393/how-to-trigger-paste-event-manually-in-javascript).
I hope you'll find a solution but the only things you can do here are ugly workarounds. Like intercepting the "copy" command in monaco-editor and saving the selected text and then inserting the previously saved text in the editor. This will work only if you copy-paste in the editor. It won't work with content copied outside.

**Comment by wang12124468** [comment]
Got it. It seems that I should only override `copy/cut/paste` to realize.
Thanks for you help. @IamFonky
