### ISSUE TITLE
Pug highlighting missing for custom tags

### ISSUE THREAD

**Issue by kladnik** [microsoft/monaco-editor#1697]
For some reason, it does not highlight custom tags, which it should. 
Example with Monaco editor:
![image](https://user-images.githubusercontent.com/11619663/70314073-12fb6080-1817-11ea-8408-9c96ea313c37.png)

Same example in VSCode:
![image](https://user-images.githubusercontent.com/11619663/70314181-476f1c80-1817-11ea-981f-2990eb4c7fd5.png)

Could there be an update with highlighting where all tags are allowed? There are custom tags even in documentation: https://pugjs.org/language/tags.html

Thanks

EDIT:
The issue is here on line 43 where all the tags are predefined: https://github.com/microsoft/monaco-languages/blob/master/src/pug/pug.ts

**Comment by alexdima** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
