### ISSUE TITLE
Question: how to get contextual IntelliSense for a single object

### ISSUE THREAD

**Issue by danvk** [microsoft/monaco-editor#170]
I'm using Monaco to help users edit style configurations for a map. The style configuration is an object which can contain either constants or callbacks:

``` js
{
  strokeWidth: 3,
  strokeColor: feature => feature.properties.population > 100 ? 'hotpink' : 'blue'
}
```

I can define an `interface` for this object using TypeScript. Is it possible to tell the Monaco editor that whatever the user types needs to match this interface?

https://github.com/Microsoft/monaco-editor/issues/61 seems relevant here.

**Comment by alexandrudima** [comment]
@danvk Since this is something very special, we don't have such support out of the box. You can fork [monaco-typescript](https://github.com/Microsoft/monaco-typescript) to change it that it always prepends `myFunction(` and appends `)` to the model text before passing the text over for validation to the TypeScript services. You can then define an extraLib which describes the shape of `myFunction(arg:...)`. Next, you can build your own version of the monaco editor by using your forked version of `monaco-typescript`.

**Comment by danvk** [comment]
A hook for prepending and appending text before it gets sent to the TS services would be really valuable.

In the example above, I'm unable to get good highlighting unless I prepend either `var x = ...` or wrap it in a function call.

**Comment by alexandrudima** [comment]
@danvk At your own risk :) ... non-API advice here -- You could use a combination of `editor.setHiddenAreas()` https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/editorBrowser.ts#L525 and `editor.getModel().setEditableRange()` https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/editorCommon.ts#L2133

But be warned these are considered non-API and may break at any time.
