### ISSUE TITLE
Reveal.js Example

### ISSUE THREAD

**Issue by joeskeen** [microsoft/monaco-editor#1717]
As a presenter, I have long wished I could embed a fantastic code editor like Monaco into my slides for simple demonstrations.  With the open sourcing of Monaco, it seems that may now be possible.  Unfortunately, in my first attempt of bringing the two together using [Reveal.js](http://lab.hakim.se/reveal-js/#/), I found that the way that Reveal automatically scales content seems to make Monaco not work well; the font size is too small (and can't be increased), the command pallete shows up with font too big and gets cut off, and the cursor doesn't line up with the text the further down the line you go.

It would be great to get an example out there of how you can use the two together, even if it requires additional CSS and/or JS to get them to play nicely.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
