### ISSUE TITLE
wordBasedSuggestions is gone in 0.19.0

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/monaco-editor#1746]
Is this intentional? The content can be found [here](https://github.com/microsoft/monaco-editor/blob/c854d18c3579ecae9e859ae6d1fea785a6dd462b/website/playground/monaco.d.ts.txt#L2991-L2994) in the 0.18.1 version of `monaco.d.ts`.

`wordBasedSuggestions` can no longer be found [here](https://github.com/microsoft/monaco-editor/blob/ccfa5557585f81bd81f291ded7bbd0ab12fdee1b/website/playground/monaco.d.ts.txt) in 0.19.0.

**Comment by rcjsuen** [comment]
I'm assuming this isn't intentional but if it is please add an entry to the `CHANGELOG.md` so we can all be made aware of this.

**Comment by alexdima** [comment]
There are a bunch of settings that are "global" and are being read directly from the configuration service by various pieces of code. Those settings do not make it through the same code paths as the internal editor options and cannot be customized per editor. In other words, `wordBasedSuggestions` was in `IEditorOptions`, but that was somewhat of an oversight since it does not function like any of the other editor options. 

[Here are the "global" settings](https://github.com/microsoft/vscode/blob/dccd0b23cca8d3cee6219dfdce74f225bc786305/src/vs/editor/common/config/commonEditorConfig.ts#L442-L516) which are not editor options per se, although calling `editor.updateOptions` with them works as expected due to [some trickery done via the `SimpleConfigurationService`](https://github.com/microsoft/vscode/blob/9349e9a2fdbd1d92824ce99af4a50b6785351b11/src/vs/editor/standalone/browser/simpleServices.ts#L610-L625). Those settings are currently not properly typed anywhere:
