### ISSUE TITLE
Display type definition when we highlight a variable

### ISSUE THREAD

**Issue by pgherveou** [microsoft/monaco-editor#1778]
Feature request:

The current behavior when we mouseover a variable is to display the type in a popup
example: 
<img width="294" alt="Screen Shot 2020-01-24 at 11 21 36 AM" src="https://user-images.githubusercontent.com/521091/73084889-c7bb1100-3e9b-11ea-8cc6-aa62e3a9cce3.png">

This is great, but sometimes I also want to access the type definition. Could we show as well the type definition when we highlight the variable and maybe hold an extra key.

Right now the only way to get the type definition is to highlight the type itself (which might not be directly available in editor)  

<img width="394" alt="Screen Shot 2020-01-24 at 11 21 49 AM" src="https://user-images.githubusercontent.com/521091/73084914-d30e3c80-3e9b-11ea-91a6-edc2caae4642.png">

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
