### ISSUE TITLE
Drag and drop of text not working with Shadow Dom

### ISSUE THREAD

**Issue by aeschli** [microsoft/monaco-editor#1788]
Testing https://github.com/microsoft/vscode/issues/89392

Firefox and Chrome, Shadow Dom.

Select a text, try to drag it to another location in the editor. Nothing happens on drop.

**Comment by afonsomatos** [comment]
Any news on this?

**Comment by afonsomatos** [comment]
We are adding multiple event listeners up the document fragment ladder (because events don't bubble between shadow-doms). In turn, the events captured at various document fragment levels will have elements as their `target` that aren't inside the monaco editor itself:

In turn, the `HitTestRequest` will have the `targetPath` completely empty, because it will be tracing the path of the target element which is outside the monaco's view node).

This will mean that hit testing against the lines won't work (because the hit test request is not correct), and that's what happens. `isChildOfViewLines` faces an empty `targetPath` and returns null.

**Comment by afonsomatos** [comment]
Probably this will fix it, I still need to test it properly, on mouseHandler.ts:
```ts
    _createMouseTarget(e, testEventTarget) {
        const shadowRoot = dom.getShadowRoot(ctx.viewDomNode);
        const target = shadowRoot ? shadowRoot.elementFromPoint(e.posx, e.posy) : e.target;
        return this.mouseTargetFactory.createMouseTarget(this.viewHelper.getLastRenderData(), e.editorPos, e.pos, testEventTarget ? target : null);
    }
```
