### ISSUE TITLE
Clarify status of IE 11 support

### ISSUE THREAD

**Issue by kpreisser** [microsoft/monaco-editor#1790]
**monaco-editor version:** 0.19.3
**Browser:** IE 11
**OS:** Windows 10

It seems the current Monaco Editor 0.19.3 doesn't work correctly in **IE 11**.
For example:

* Open the [Monaco Editor page](https://microsoft.github.io/monaco-editor/index.html) in IE 11, and in the editor, type `Math.`:
![grafik](https://user-images.githubusercontent.com/13289184/73338124-30c4cf00-4276-11ea-8dfa-02a610519d70.png)

* Right-click on a symbol and notice that there is a rendering issue in the "Peek" line:
![grafik](https://user-images.githubusercontent.com/13289184/73358679-777aef00-429f-11ea-9422-968fd5ad8959.png)

* Select `Peek references` on a symbol (and notice nothing happens), then select it a second time where now the window opens, but cannot be closed:
![grafik](https://user-images.githubusercontent.com/13289184/73358842-cde82d80-429f-11ea-86e3-4fc527b730ce.png)

* Press <kbd>Ctrl</kbd>+<kbd>F</kbd> and notice search doesn't find anything:
![grafik](https://user-images.githubusercontent.com/13289184/73359152-76968d00-42a0-11ea-87e9-26b0776725ee.png)

<br>

However, the Monaco Editor page still says:
> It is licensed under the MIT License and supports **IE 11**, Edge, Chrome, Firefox, Safari and Opera.

If Monaco Editor no longer supports IE 11, the website should be updated to reflect this.

Thanks!

**Comment by alexdima** [comment]
Thank you for pointing this out. We have investigated the cost of fixing all the problems of IE11 and have decided to discontinue support for IE 11.

The Monaco Editor is generated from the source code of VS Code and in order to improve VS Code we must be able to use modern browser features, like Flexbox, which has a number of bugs that we cannot workaround, and which is the root cause of many of the issues you point out.

The last Monaco Editor version that was tested on IE 11 is `0.18.1`.

Thank you for your understanding, we will update our website and readme to reflect this.
