### ISSUE TITLE
VIM Key Binding Support?

### ISSUE THREAD

**Issue by gynet** [microsoft/monaco-editor#182]
I know there is VSCodeVim/Vim working on enabling VIM key binding for VS Code, but it would be great if monaco-editor have VIM key binding as well.

**Comment by altusgerona** [comment]
Any update on this?

**Comment by gchristiansen** [comment]
This is essential if using as editor for online code editors. Please bump up priority :)

**Comment by gynet** [comment]
Is it possible to use neovim and WebSocket?

**Comment by mrandrewandrade** [comment]
Any update on this?

**Comment by ryskin** [comment]
this will resolve iPad Pro keyboard (arrows) issue )

**Comment by hifall** [comment]
Definitely desired!!!

**Comment by juancampa** [comment]
I just started a bounty for this issue (pledged $50)

https://www.bountysource.com/issues/37736535-vim-key-binding-support

Feel free to add to the bounty

**Comment by brijeshb42** [comment]
I have finished a prototype for vim mode. Demo @ https://editor-a5ea1.firebaseapp.com/ 
Not fully functional but most of the functionalities are working

**Comment by juancampa** [comment]
@brijeshb42 I just tried it for a bit and it feels great. Now you can have 10x🍺on me

**Comment by hifall** [comment]
@brijeshb42, that seems interesting! Do you plan to open source the implementation?

**Comment by brijeshb42** [comment]
I just have to cleanup some code and create a nice to use api for the extension. Then I'll opensource it

**Comment by brijeshb42** [comment]
Published https://github.com/brijeshb42/monaco-vim

**Comment by hifall** [comment]
@brijeshb42, one more question: is the approach you take in the implementation generic enough to accommodate other bindings like Emacs, etc.?

For example, if I were to implement Emacs bindings for Monaco, I'd grab a CM keymap for Emacs, then plug it into your work, I should have Emacs bindings. Is that right?

Thanks.

**Comment by brijeshb42** [comment]
@hifall That would have worked, for say, if I released keybindings for emacs and you wanted to create a sublime keybinding as they both are direct mapping of keypress to some action on the editor. Vim is a different because of its modal nature. The adapter that I have written might help though has it has a lot of functions already implemented. But you can't directly pickup CM's emacs code and expect it to work.

**Comment by hifall** [comment]
That makes sense. I hope there will be an Emacs or Sublime-based implementation soon so that others can build more bindings off of that.

**Comment by brijeshb42** [comment]
If you see the demo, there's already an emacs mode checkbox. It's still in  development. 10:37 AM, August 20, 2018, hifall <notifications@github.com>:That makes sense. I hope there will be an Emacs or Sublime-based implementation soon so that others can build more bindings off of that.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

-

**Comment by mlynch** [comment]
@brijeshb42 wow, cheers from all of us, that is awesome!

What's the status of it? Ready to be used in a production app (we're working on an IDE for Ionic Framework and I can't live without vim bindings). 

Also, is there a way for us to listen for certain tab commands like `gt` and `gT` so we can switch tabs in our tool?

**Comment by brijeshb42** [comment]
@mlynch I created it to be used @ Hackerrank. It is already being used in production by us. Besides that, [Expo](https://snack.expo.io/) and Repl.it are using it.

Regarding usage, it is just a wrapper on top of Codemirror's vim implementation. So you can do anything that is allowed by the Codemirror VIM api. You can read about that [here](https://codemirror.net/doc/manual.html#vimapi_extending)

**Comment by erquhart** [comment]
@alexandrudima just wanted to point out that this is the most thumbed up issue on this repo by a very wide margin ([issues sorted by reactions](https://github.com/Microsoft/monaco-editor/issues?q=is%3Aopen+sort%3Areactions-%2B1-desc)) - double the reactions of the next most thumbed up issue.

I'm aware that this in no way dictates your roadmap, but can you at least comment on whether vim keybindings are on the core team's radar?

**Comment by gynet** [comment]
I am revisiting this issue. As the popularity of monaco editor now, I am thinking about it would make sense for the monaco-editor to add a js/ts based plugin system.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

---

We are open to enable users to implement this on their own though, please create issues/PRs for missing API/problems you encounter!
