### ISSUE TITLE
suggestions box doesn't show the item text. 

### ISSUE THREAD

**Issue by mboutros1** [microsoft/monaco-editor#1829]
**monaco-editor version:** 0.20.0
**Browser:** IE 11 - 11.0.170
**OS:** Windows 10 
**Playground code that reproduces the issue:**https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world

```js
```
The suggestion box shows  blank box when you press ctrl + space.  

Please open https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world 
in IE 11. 

![image](https://user-images.githubusercontent.com/8062071/74265247-3687cf00-4cd0-11ea-8c2d-c4edd071b7cd.png)

not sure if it is related but I've noticed there is JS error 
Unable to get property 'addEventListener' of undefined or null reference
events.ts line 19

**Comment by alexdima** [comment]
Thank you for pointing this out. We have investigated the cost of fixing all the problems of IE11 and have decided to discontinue support for IE 11.

The Monaco Editor is generated from the source code of VS Code and in order to improve VS Code we must be able to use modern browser features, like Flexbox, which has a number of bugs that we cannot workaround in IE11, and which is the root cause of the issue you point out.

The last Monaco Editor version that was tested on IE 11 is `0.18.1`.

Thank you for your understanding, we will update our website and readme to reflect this.
