### ISSUE TITLE
File 'monaco-editor/monaco.d.ts' is not a module [Angular 2]

### ISSUE THREAD

**Issue by Coleim** [Microsoft/monaco-editor#184]
Hello,

I am trying to use monaco editor within an Angular 2 project.
I found a way to integrate it with the workaround proposed here: https://github.com/Microsoft/monaco-editor/issues/18#issuecomment-231788869

But I would like now to create a `CustomCompletionItemProvider` which implements `monaco.languages.CompletionItemProvider`.

But when I try to import from monaco, I got this error:

> File 'monaco-editor/monaco.d.ts' is not a module

Any idea why the monaco.d.ts is not recognize as a module?
The module is declared as:
`declare module monaco`
Maybe an export is missing ?

You could check the sample project I made for that here: https://github.com/Coleim/monaco_exemple

Thanks for the support.
Cheers
Clement

**Comment by alexandrudima** [comment]
I am sorry I am not an expert in the way TypeScript pulls in `.d.ts` files and what format they should have (of an internal module or of an external module).

I have got TypeScript to import the monaco editor ambient types via adding this to `typings/index.d.ts`:
```
/// <reference path="../node_modules/monaco-editor/monaco.d.ts" />
```

and then using it:
```
import CompletionItemProvider = monaco.languages.CompletionItemProvider;
```

I am sorry I don't have a better answer, I also don't understand how I should ship the .d.ts file (given the editor is not a commonjs module).

**Comment by alexandrudima** [comment]
ping @jrieken @dbaeumer any advice on how the `monaco.d.ts` should look like -- I am confused and unsure what is the latest thinking in TypeScript. Please note that the editor is not commonjs, even though we distribute it through npm.

**Comment by Coleim** [comment]
Hi

Thanks a lot, I'll check if the workaround with typings is enough and I'll tell you.

Cheers

**Comment by Coleim** [comment]
I added it in the `typings.json` as a global dependency.
```

    {
      "globalDependencies": {
        "core-js": "registry:dt/core-js#0.0.0+20160725163759",
        "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
        "node": "registry:dt/node#6.0.0+20160831021119",
        "monaco-editor": "file:./node_modules/monaco-editor/monaco.d.ts"
      }
    }
```
With that, it seems to work. 
It should be enough for me as a first workaround.
Thanks

**Comment by rezonant** [comment]
The problem is the typing has `declare module monaco` instead of the correct `declare module "monaco-editor"`

**Comment by meriturva** [comment]
any news here? i think that @rezonant has right!

**Comment by alexandrudima** [comment]
Well, the editor API sits behind a big fat global named "monaco". That is what `monaco.d.ts` defines, an ambient global and not a module.

**Comment by rezonant** [comment]
Yes, to get Monaco to work with Angular 2 I had to load `loader.js` via <script> tag, which I did dynamically within a MonacoEditorComponent (there are examples of this technique available online). I think the bigger issue here is that one cannot easily load Monaco via CommonJS require() or ES6 `import` as is done with most libraries. Getting Monaco loaded properly was the most challenging part about integrating it with my project.

**Comment by Yogu** [comment]
First of all thanks for making this awesome editor open source! Really appreciate that.

I think the problem is that the `monaco.d.ts` declares several modules (`declare module`), although monaco does not ship in modules but in one big object called `monaco` on the global object. To reflect this, you should rather use `declare namespace`. I just copied the file and replaced `declare module` by `declare namespace` and I could access the typings without any `import`.

However, of course, it would be great if monaco would actually ship in ES6 modules, so that webpack could handle that, but there is already another issue for that.

**Comment by GaryChangCN** [comment]
```typescript
declare interface Window {
    monaco: typeof monaco
}
```

**Comment by j3gb3rt** [comment]
I'm linking to the documentation on generating d.ts files from typescript's website.
[Library Structures](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)

In it's current form, monaco is loaded into a global variable. So the _Global Libraries_ section is the section the d.ts file should follow.

In the subsection _Global Library Template_, there is a [link](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html) to example of how global d.ts files should be setup.

It seems from their example that monaco should be using namespace instead of module.
The function declarations and interface declaration don't apply to monaco from their comments

@Yogu Can you link to the edits you made to get this working? Where did you copy the file to so that import was not needed?

**Comment by Yogu** [comment]
@j3gb3rt I literally just replaced `declare module` by `declare namespace` and put it as `monaco.d.ts` into my source directory.

**Comment by DevidCIC** [comment]
I am using [ngx-monaco-editor](https://github.com/atularen/ngx-monaco-editor) with Angular 4. Now I want to create a custom language, because of that d.ts file is very important for me. Would be really cool if this is fixed.

**Comment by alexandrudima** [comment]
The `typings` of the editor `package.json` now points to an "external module" variant of the `monaco.d.ts`. See also https://github.com/Microsoft/monaco-editor/issues/18#issuecomment-373086721
