### ISSUE TITLE
Support multiple classes per token

### ISSUE THREAD

**Issue by dhakehurst** [microsoft/monaco-editor#1869]
I am creating a custom tokenizer.
I want to add multiple 'classes' for each token.

I see the  support for '.' in between individual token classes, but that implies a hierachy.

I want to simply add multiple tokens, without a hierarchy.
I.e. an array of scopes/token classes.

I spotted this issue  [https://github.com/Microsoft/monaco-editor/issues/929]

but it does not seem to solve the issue.

**Comment by SimonCockx** [comment]
+1. This would also enable support for TextMate. See https://github.com/zikaari/monaco-editor-textmate/issues/24

**Comment by SimonCockx** [comment]
@alexdima (and @svenefftinge ?) In https://github.com/Microsoft/monaco-editor/issues/929 you state that the issue of accepting multiple scopes per token is resolved. That's not the case however; see [this line](https://github.com/microsoft/monaco-editor/blob/9375d4ba65a3b50fd28569c588d2e279a13a757e/website/typedoc/monaco.d.ts#L5703). However, having an array of scopes is necessary to fully support a tokenizer such as TextMate, which is why it's [current implementation](https://github.com/zikaari/monaco-editor-textmate) is limited.

The workaround for picking the first scope that has a theme defined (which is how [theia](https://github.com/eclipse-theia/theia/commit/110492578ae1aad53b4b574a0637b31e7c4d59e0) and [monaco-textmate](https://github.com/zikaari/monaco-editor-textmate/blob/6c19af487e7bc917cd2616bfb3cfc760b4662ab5/src/tm-to-monaco-token.ts) have done it) is only a partial fix. It doesn't allow you to do:
1. theme merging. If multiple theme rules match scopes at different levels, their styles should be merged if they're non-conflicting (e.g., one a red foreground color and one italics).
2. match multiple scopes at once. E.g.,
```
{
    "scope": "comment.block.documentation string.quoted",
    "settings": {
        "foreground": "#6A9955"
    }
}
```
-> this will only match tokens that have the scope `string.quoted` preceded by `comment.block.documentation`, which is impossible if you only pick a single scope.

These features are supported by VSCode, but not by Monaco.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Comment by dhakehurst** [comment]
yes I disagree :)

it is very important to me to be able to add multiple classes

**Comment by SimonCockx** [comment]
Not only to @dhakehurst though. :) It's very important if Monaco wants to fully support TextMate based tokenization, which is the most popular way of supporting syntax highlighting, simply because it is how [VS Code's tokenization engine is powered](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#tokenization).

See [my comment above](https://github.com/microsoft/monaco-editor/issues/1869#issuecomment-1381457819).

**Comment by hediet** [comment]
> It's very important if Monaco wants to fully support TextMate based tokenization

But why is this not an issue in VS Code? It also uses textmate and the monaco editor is an extraction of VS Code.

**Comment by SimonCockx** [comment]
@hediet Good question. I've just been scrolling through VS Code's code and it seems that an array of scopes is represented as a string separated by spaces. So... I take back the statement that having an array of scopes is strictly necessary.

It makes me wonder. When performing the action "Inspect Tokens", does Monaco support a space-separated string of scopes, like VS Code does?

If the answer is yes, I wonder why repo's such as monaco-textmate reverts to ugly workarounds such as picking only a single scope. If the answer is no, I wonder where Monaco and VS Code diverge exactly.

Similarly, where does VS Code's support for theme merging and scope matching come from? Can the same mechanism be reused in Monaco?

Sorry, the realization that this issue is actually non-blocking for TextMate support in Monaco just gives me a load of different questions. :)
