### ISSUE TITLE
Support SQLite highlighting in .sqlite files

### ISSUE THREAD

**Issue by hoffm** [microsoft/monaco-editor#1870]
The Monaco SQL language configuration works decently well out of the box for SQLite files (`.sqlite` extension). However, because SQL proper has more features, using the existing SQL language for SQLite files will highlight some commands (e.g. `DROP COLUMN` or `RIGHT OUTER JOIN`) that SQLite does not in fact support.

In order to support `.sqlite` files, the options are, therefore:

1. Add `.sqlite` to the extensions using the existing `sql` language, with the drawbacks noted above.
2. Add a new language for SQLite.

**Comment by rcjsuen** [comment]
@hoffm Probably need to make a copy of [this folder](https://github.com/microsoft/monaco-languages/tree/a4e1adf14168e87e6c9e1277a5e8a4b0e27d9b5a/src/sql) to implement that.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
