### ISSUE TITLE
Code completion icons are missing on Safari

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/monaco-editor#1888]
**Browser:** Safari 13.0.3 (15608.3.10.1.4)
**OS:** macOS Catalina 10.15.1

Seeing a strange behaviour on the webpage. The icons are all bad in Safari. They render fine for me in Chrome though.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/15629116/77652960-797ec880-6f45-11ea-953c-a9e9a4f166ae.png">

**Comment by rators** [comment]
on chrome gutter icons don't seem to render either

**Comment by nrayburn-tech** [comment]
Icons seem fine for me, not sure if it is due to a version difference or something else going on.
**Browser:** Safari 13.1
**OS:** Catalina 10.15.4
<img width="265" alt="Screen Shot 2020-03-28 at 1 45 09 PM" src="https://user-images.githubusercontent.com/52075362/77831006-75e07280-70fa-11ea-8e8a-59d041d010b8.png">

**Comment by alexdima** [comment]
They appear to be fine in the meantime:

https://microsoft.github.io/monaco-editor/

![image](https://user-images.githubusercontent.com/5047891/93617212-f743fe00-f9d5-11ea-8fdd-5dccb7bee8c3.png)

**Comment by rcjsuen** [comment]
Confirmed that I am seeing them although my system has since changed.

**Browser:** Safari 13.1.12 (15609.3.5.1.3)
**OS:** macOS Catalina 10.15.6
