### ISSUE TITLE
Bindings to Blazor/ASP.NET Core WebAssembly

### ISSUE THREAD

**Issue by inf9144** [microsoft/monaco-editor#1902]
It would be really nice if we could embed Monaco into a Blazor WebAssembly project.
I think there would be a bunch of JSInterop and a component facade needed.
There were some open source approaches started to build something like that (as example Blazaco) but none of them are active and none of them are exposing the full api into Blazor. 
As ASP.NET Core / Blazor is a microsoft product, it would be nice if you could directly support it.

**Comment by kluetkemeyer** [comment]
That would be really great. I've been looking for a blazor interface for a code editor component like Monaco for some time, but without success regarding my requirements. I'm not familiar enough with TypeScript to wrap the API in a good pattern by myself and dont want to produce another semi-finished wrapper construct.

**Comment by Astn** [comment]
I'm also looking into using Monaco for a Blazor project. 
👍

**Comment by serdarciplak** [comment]
Check out https://github.com/serdarciplak/BlazorMonaco
This is a new repo I've started and currently working on. It's not the full api yet but it will be. If a specific feature that you need is missing, please tell me and I'll prioritize it.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
