### ISSUE TITLE
it's too diffcult to understand what can one api do something for me, do you have a book to help?

### ISSUE THREAD

**Issue by SY199505** [microsoft/monaco-editor#1910]
some api can do things, but I don't know which api I should use to finsh my work. Thank you!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
