### ISSUE TITLE
Make it possible to override addDisposableListener, addStandardDisposableListener etc.

### ISSUE THREAD

**Issue by marclerman** [microsoft/monaco-editor#1912]
Hello,

We wrap the Monaco editor in an Angular component. But key and mouse events will trigger Angular's change detection, which is totally unnecessary and can lead to slow downs while editing (e.g. holding down the Shift key for while would make Angular trigger its change detection constantly until the key is released).
In our code, we monkey-patched esm/vs/base/browser/dom's addDisposableListener, addStandardDisposableListener, addDisposableNonBubblingMouseOutListener and addDisposableThrottledListener to run outside of Angular's zone.

This works as long as we compile our modules using "es5" as a target. If we change the target to "es2015" for example, JavaScript is much more strict and gives a runtime error disallowing the modification of these functions.

The feature request is to make it possible to override these functions, so that in our case the overrides would call NgZone.runOutsideAngular((node, type, handler, useCapture) => super.addDisposableListener(node, type, handler, useCapture)) and so on.

Thanks!

**Comment by MarcDAFrame** [comment]
any update on this? I need to be able to override the default paste listener and I can't find a good way to do it.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
