### ISSUE TITLE
The editor doesn't check the xml syntax.

### ISSUE THREAD

**Issue by ZhangYuri** [microsoft/monaco-editor#1914]
**monaco-editor version:** 0.20.0
**Browser:** Chrome 80.0.3987.163
**OS:** Windows10
**Playground code that reproduces the issue:**
When I input some incorrect text like this, it doesn't remind me I have a syntax error.
```xml
   <?xml version="1.0"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <connectionStrings> 12346474567658
    <add name="MyDB" 
      connectionString="value for the deployed Web.config file" 
      xdt:Transform="SetAttributes" xdt:Locator="Match(name)"/>
  </connectionStrings>
</configuration>
```
Steps:
1. Open monaco editor in https://microsoft.github.io/monaco-editor/
2. Select xml language.
3. Input some incorrect text like above.

**Comment by spahnke** [comment]
That's because the Monaco Editor only supports basic syntax highlighting for XML. Rich editor support like diagnostics and intellisense is only supported for TypeScript, JavaScript, CSS, LESS, SCSS, JSON, HTML, as stated on the website.

**Comment by harshadsindhav** [comment]
Hi, By when we expect syntax validations for xml, java and python languages in moneco editor ?

Thank you.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
