### ISSUE TITLE
Problem when serving Project Monaco from subfolder

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/monaco-editor#1938]
**monaco-editor version:** 0.19.0
**Browser:** Chrome and Edge latest versions
**OS:** Windows

When compiling the sample application with the provided sample, in the dist folder I get the following files:

 Directory of C:\Users\dacuri\Source\Repos\RobotStudioPOC\CodeEditor\dist

04/24/2020  12:57 PM    <DIR>          .
04/24/2020  12:57 PM    <DIR>          ..
04/24/2020  12:57 PM             5,152 0.CodeEditor.js
04/24/2020  12:57 PM             6,041 10.CodeEditor.js
04/24/2020  12:57 PM             5,332 11.CodeEditor.js
04/24/2020  12:57 PM             4,002 12.CodeEditor.js
04/24/2020  12:57 PM               879 13.CodeEditor.js
04/24/2020  12:57 PM             1,876 14.CodeEditor.js
04/24/2020  12:57 PM             2,068 15.CodeEditor.js
04/24/2020  12:57 PM             9,674 16.CodeEditor.js
04/24/2020  12:57 PM             3,621 17.CodeEditor.js
04/24/2020  12:57 PM             4,566 18.CodeEditor.js
04/24/2020  12:57 PM             1,450 19.CodeEditor.js
04/24/2020  12:57 PM             4,520 20.CodeEditor.js
04/24/2020  12:57 PM             1,867 21.CodeEditor.js
04/24/2020  12:57 PM             3,014 22.CodeEditor.js
04/24/2020  12:57 PM             2,688 23.CodeEditor.js
04/24/2020  12:57 PM             2,209 24.CodeEditor.js
04/24/2020  12:57 PM             6,193 25.CodeEditor.js
04/24/2020  12:57 PM             4,577 26.CodeEditor.js
04/24/2020  12:57 PM             1,132 27.CodeEditor.js
04/24/2020  12:57 PM             3,000 28.CodeEditor.js
04/24/2020  12:57 PM             3,470 29.CodeEditor.js
04/24/2020  12:57 PM             3,927 30.CodeEditor.js
04/24/2020  12:57 PM             2,154 31.CodeEditor.js
04/24/2020  12:57 PM             3,830 32.CodeEditor.js
04/24/2020  12:57 PM             2,610 33.CodeEditor.js
04/24/2020  12:57 PM             4,943 34.CodeEditor.js
04/24/2020  12:57 PM            14,529 35.CodeEditor.js
04/24/2020  12:57 PM            47,404 35bb8d560db5205616671eab8c4d0303.ttf
04/24/2020  12:57 PM             2,433 36.CodeEditor.js
04/24/2020  12:57 PM             3,017 37.CodeEditor.js
04/24/2020  12:57 PM             2,031 38.CodeEditor.js
04/24/2020  12:57 PM             8,286 39.CodeEditor.js
04/24/2020  12:57 PM            17,661 40.CodeEditor.js
04/24/2020  12:57 PM             8,058 41.CodeEditor.js
04/24/2020  12:57 PM             7,887 42.CodeEditor.js
04/24/2020  12:57 PM            16,970 43.CodeEditor.js
04/24/2020  12:57 PM             3,300 44.CodeEditor.js
04/24/2020  12:57 PM             4,859 45.CodeEditor.js
04/24/2020  12:57 PM             3,271 46.CodeEditor.js
04/24/2020  12:57 PM             2,866 47.CodeEditor.js
04/24/2020  12:57 PM             8,481 48.CodeEditor.js
04/24/2020  12:57 PM             3,587 49.CodeEditor.js
04/24/2020  12:57 PM            11,813 50.CodeEditor.js
04/24/2020  12:57 PM             8,534 51.CodeEditor.js
04/24/2020  12:57 PM             3,953 52.CodeEditor.js
04/24/2020  12:57 PM             1,860 53.CodeEditor.js
04/24/2020  12:57 PM             1,798 54.CodeEditor.js
04/24/2020  12:57 PM             6,440 55.CodeEditor.js
04/24/2020  12:57 PM             2,957 56.CodeEditor.js
04/24/2020  12:57 PM            18,628 57.CodeEditor.js
04/24/2020  12:57 PM             2,795 58.CodeEditor.js
04/24/2020  12:57 PM            18,270 59.CodeEditor.js
04/24/2020  12:57 PM             7,417 60.CodeEditor.js
04/24/2020  12:57 PM             4,157 61.CodeEditor.js
04/24/2020  12:57 PM             3,626 62.CodeEditor.js
04/24/2020  12:57 PM             6,009 63.CodeEditor.js
04/24/2020  12:57 PM             5,099 64.CodeEditor.js
04/24/2020  12:57 PM             5,848 65.CodeEditor.js
04/24/2020  12:57 PM             1,770 66.CodeEditor.js
04/24/2020  12:57 PM             3,573 67.CodeEditor.js
04/24/2020  12:57 PM            22,776 68.CodeEditor.js
04/24/2020  12:57 PM           119,127 7.CodeEditor.js
04/24/2020  12:57 PM           706,826 8.CodeEditor.js
04/24/2020  12:57 PM           424,904 9.CodeEditor.js
04/24/2020  12:57 PM         2,427,128 app.CodeEditor.js
04/24/2020  12:57 PM           838,291 css.worker.CodeEditor.js
04/24/2020  12:57 PM           139,592 editor.worker.CodeEditor.js
04/24/2020  12:57 PM           555,216 html.worker.CodeEditor.js
04/24/2020  12:57 PM               622 index.html
04/24/2020  12:57 PM           248,983 json.worker.CodeEditor.js
04/24/2020  12:57 PM         4,725,479 ts.worker.CodeEditor.js

(In my project I have renamed the bundle file name to CodeEditor).

When I deploy the app, it is deployed in a subfolder of my website.

For the worker files, I have modified the self.MonacoEnvironment/getWorkerUrl function, providing the correct path. In face all these files are loaded correctly.

But: there are many other files, in my case 68.CodeEditor.js, 10.CodeEditor.js and 35bb8d560db5205616671eab8c4d0303.ttf, that are still referenced from the root folder. So this fails.

My questions are:
* do I really need these XX.CodeEditor.js files?
  As they are there, I would suppose so... but then why I need only the 68 and 10 files and not all the others?
* can I bundle these files with the other files?
  Btw, for me, it would be fine to bundle ALL files in a single file, containing all *.CodeEditor.js (but really all the circa 70 files) and the ttf file
* otherwise, where can I also provide the path for these XX.CodeEditor.js files?

**Comment by alexdima** [comment]
@curia-damiano

> When compiling the sample application with the provided sample

Which of the samples have you used to get started? There are multiple samples at https://github.com/microsoft/monaco-editor-samples which cover multiple bundlers (just for webpack there are 4 samples).

> do I really need these XX.CodeEditor.js files? As they are there, I would suppose so... but then why I need only the 68 and 10 files and not all the others?

I will assume maybe you are using webpack? The editor has support for many programming languages. But the support is loaded only on demand, to keep the load size as small as possible. So, if you instantiate an editor and use the `javascript` language, only the `javascript` parser definition and the `javascript` support code will load and only the `javascript` web worker will be instantiated. Later, if you instantiate a model and use the `css` language, only those pieces will be additionally loaded, etc.

> can I bundle these files with the other files?
Btw, for me, it would be fine to bundle ALL files in a single file, containing all *.CodeEditor.js (but really all the circa 70 files) and the ttf file

> otherwise, where can I also provide the path for these XX.CodeEditor.js files?

These two questions appear to be very specific to the bundler you are using. I am personally not a webpack expert, but I can recommend that **the absolute easiest way to bundle the monaco editor is to use the `monaco-editor-webpack-plugin`**.

And here is a self-contained sample -- https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-monaco-plugin . Please start by doing the following:
* check out that repository
* cd `browser-esm-webpack-monaco-plugin`
* run `npm install`
* run `npm build`
* go back to the root and run `npm run simpleserver`
* open a browser at http://localhost:8888/browser-esm-webpack-monaco-plugin/dist/

Please observe how in that sample, the files are hosted in a subfolder called `dist`.

From my past webpack experience, I have found that it is very difficult to write a good `webpack.config.js` file. So rather than starting with one from scratch, my personal recommendation is to tweak the one in the sample as much as possible until it matches whatever your project wants to do, verifying that it works correctly after each edit you do, and then finally moving it into your project.

**Comment by curia-damiano** [comment]
Hi Alex,
Thank you very much for your info.

In my case, I have used the sample https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-typescript, that is not using the monaco-editor-webpack-plugin.

Still, I have opened the sample `browser-esm-webpack-monaco-plugin`, and followed your bulleted points.
Like the other sample, at runtime I see this:

<img width="1104" alt="screenshot" src="https://user-images.githubusercontent.com/18611507/82185303-50493b80-98e9-11ea-90a8-cc22631e5fa5.png">

This sample too loads _1.bundle.js_ and _5.bundle.js_.

My point is: if the JavaScript files are hosted in a subfolder of the main application, these files are searched in the root folder and not in the subfolder.

You see from the second screenshot that my apps needs _68.CodeEditor.js_ and _10.CodeEditor.js_.
The files are existing, but in a _codeEditor_ subfolder.

Project Monaco anyway tries to load them from the root path.
How can I override their path?

**Comment by curia-damiano** [comment]
Hi Alex,
I have found that my issue was already described here: https://stackoverflow.com/questions/57377496/react-monaco-editor-not-finding-workers-produced-by-monaco-editor-webpack-plugi

Luckily the solution still applies: add a **publicPath** folder to the _output_ section of the WebPack configuration.

Once done it, at runtime all the resources are searched from this folder. This includes the 10.bundle.js and so on, plus the ttf font.

I close this issue.
