### ISSUE TITLE
Focus is not reset after a model change

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#194]
Steps to reproduce:
1. call editor.focus
2. call editor.setModel with a new model

the editor should be focused after a change but it is not

**Comment by alexandrudima** [comment]
Most likely happening because we destroy and recreate the view when a model changes, so the dom node that holds focus gets detached from the DOM and a new `textarea` is created.

You can workaround on your side by restoring focus via `editor.focus()` if `editor.isFocused()` is true before the model is set.

**Comment by akosyakov** [comment]
@alexandrudima yes, i do exactly that, but there is one undesirable effect: if one has already started typing before `editor.focus()` is called, then the cursor jumps to the start of a model

**Comment by alexandrudima** [comment]
@akosyakov Can you explain in greater detail the order of things, or the shape of your code, how could one start typing before `editor.focus()` if the code is written synchronously:

```js
function setModelMaintainFocus(editor, model) {
  let isFocused = editor.isFocused();
  editor.setModel(model);
  if (isFocused) {
    editor.focus();
  }
}
```

**Comment by akosyakov** [comment]
@alexandrudima I see, you are right. 

We create a model just to change an URI and expect that the state of an editor will be preserved, e.g. focus and position of the cursor. But it happens that the cursor is moved to the beginning of an editor after a model change. We could also store a cursor offset and reset it after, similar to focus.

**Comment by alexandrudima** [comment]
Yes, the view state is reset when changing models (e.g. cursor position, scroll position, folding state, etc.) because we can't assume that we get 100% the same text as it appears to be in your case. I suggest using `editor.saveViewState()` and `editor.restoreViewState()`.

**Comment by akosyakov** [comment]
@alexandrudima will it help with focus either, or we still have to apply the workaround?

**Comment by alexandrudima** [comment]
The focus preserving is a valid bug.

`restoreViewState` will restore the scroll position, the selection state, etc. This is usually useful when implementing something as tabs, where there is one editor instance that consistently gets calls to `setModel(..)` to switch from one tab to another. For each tab, the view state can be maintained via `saveViewState()` and `restoreViewState()`.

The view state gets reset with each `setModel(...)` call because one file could have 1000 lines and the next could have only 10, etc. So the cursor position, the scroll state from one file don't necessarily make sense for the next file...

**Comment by akosyakov** [comment]
got it, thx
