### ISSUE TITLE
Action ids are replaced by a prefixed id

### ISSUE THREAD

**Issue by CGNonofr** [microsoft/monaco-editor#1953]
**monaco-editor version:** 0.X.Y
**Browser:** any
**OS:** any
**Playground code that reproduces the issue:**

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

editor.addAction({
    id: 'test',
    label: 'Test action',
    run: (editor, arg) => {
        alert('Command executed with args: ' + arg)
    }
})

try {
    editor._commandService.executeCommand('test', 'arg1')
} catch (err) {
    alert(err)
}

try {
    editor._commandService.executeCommand('vs.editor.ICodeEditor:1:test', 'arg2')
} catch (err) {
    alert(err)
}
```

Currently, actions are registered using a generated global unique id. The reason is that we want to prevent conflicts between action sharing the same id across multiple editors.

We use the same generated id in the code that is specific to a single editor (in the `standaloneKeybindingService`). I see no reason to do so, since providing the same action id twice to an editor will result in an identical `uniqueId` as well.

It seems to cause no issue in the normal usage of monaco-editor, but it makes some tweaks  impossible, especially in conjunction with monaco-languageclient

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

---

Also, see here: https://github.com/microsoft/vscode/pull/96789#pullrequestreview-404907136
