### ISSUE TITLE
Services are global singletons rather than per-editor

### ISSUE THREAD

**Issue by jackwickham** [microsoft/monaco-editor#1957]
**monaco-editor version:** master
**Browser:** Chrome and Firefox
**OS:** MacOS

It's not possible to have a different version of a service for each editor loaded on the page, because they are stored in the global namespace. Instead, the service used by the first editor (potentially the default one) is used for all the editors. This is particularly an issue in single page apps, which might have multiple editors that have very different behaviour.

### Playground code that reproduces the issue:
With the first editor enabled 
```js
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

// Uncomment this block to reproduce:
/*
monaco.editor.create(document.getElementById("container"), {
  value: "function hello() {\n\talert('Hello world!');\n}",
  language: "javascript"
});
*/

class MyEditorService {
  addCodeEditor(editor) {
        throw new Error("This error should be thrown, but isn't if the above editor is uncommented");
  }
}

monaco.editor.create(document.getElementById("container"), {
  value: "function hello() {\n\talert('Hello world!');\n}",
  language: "typescript"
}, {
    codeEditorService: new MyEditorService(),
});
```

As far as I can see, this is because StaticServices is a global singleton https://github.com/microsoft/vscode/blob/master/src/vs/editor/standalone/browser/standaloneServices.ts, so `_all` gets populated when the first editor instantiated, and `this._value` in each service entry is populated with the service used by that editor.

**Comment by ackava** [comment]
I guess it is by design to save memory, unnecessary too many services will eat up all memory. Mostly in editor kind of application we have different views (editors) but with same underlying model and services, think of having diff view, and code split, tabbed pages where each page has one editor for one file but all files are in same project sharing all dependencies.

You can easily solve your issue by wrapping your code inside an IFrame where each IFrame will be its own editor with its own services. You will notice linear 2x memory growth with each IFrame added on the page.

**Comment by alexdima** [comment]
Multiple editors also share things like web workers or text models. So only 1 typescript language service web worker will service any amount of instantiated editors. Also, it is possible to set the same text model to multiple editors, so editors are not isolated from each other and it is an intentional use-case that they can share things between them (text models).
