### ISSUE TITLE
folding top margin

### ISSUE THREAD

**Issue by qbodk** [microsoft/monaco-editor#1959]
Hello and thank you for building such a nice code editor!
It would be nice if the editor had an option for adding custom extra top margin to code blocks for code clarity for both UX and accessibility (astigmatism).
(maybe by adding extra top margin or line-height to the first line of the code block the same way code blocks determined in folding or indentation)
thank you!
![VSCBM](https://user-images.githubusercontent.com/53770247/81473468-050d9980-9214-11ea-8dd9-986c010a32e6.jpg)

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
