### ISSUE TITLE
Cobol language Support

### ISSUE THREAD

**Issue by maustand** [microsoft/monaco-editor#1963]
Hi

Just i would like to ask/request if there is a chance that monaco editor has support for cobol ?

Is there a plan for supporting this legacy programing language ?
Or someone has already done this feture via[ extending the editor ?](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages)

Due the current global situation, there is a high demand for cobol and i work for a company that creates "middlewares" for old legacy systems ( mostly hospitals and banks)  and modern apis and sometimes we have to get a input of a piece of cobol code, so it would be nice if monaco editor has plans for supporting cobol.

That's all.

I thank you in advance for your help !

Regards

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
