### ISSUE TITLE
Embedded autocomplete (nextEmbedded + registerCompletionItemProvider)

### ISSUE THREAD

**Issue by Prinzhorn** [microsoft/monaco-editor#2015]
This might be somewhat similar to #732, but it's a much more general issue. I've implemented syntax highlighting for `http` using `setMonarchTokensProvider`. It uses `nextEmbedded` for syntax highlighting of bodies based on the `Content-Type` header. This works great.

Now I've implemented autocomplete for HTTP headers using `registerCompletionItemProvider`, which works great as well. However, I was confused why I get header-suggestions inside a JavaScript body. It seems like the autocomplete just ignores the fact that there's a different language embedded.

So maybe this should even be considered a bug? For me it seems like Monaco uses the wrong `CompletionItemProvider` when it should be using the one of the embedded language.

So am I doing something wrong or is this a feature that just doesn't exist right now? How does VS Code handle that? In the screenshots you can see that the tokens are definitely JavaScript but I still get suggestions from my http completion provider.

![Selection_624](https://user-images.githubusercontent.com/679144/85109821-3bc2d080-b212-11ea-9586-3d6d7ef2d64e.png)
---
![Selection_625](https://user-images.githubusercontent.com/679144/85109832-40878480-b212-11ea-9a68-91c6172f7843.png)
---
![Selection_626](https://user-images.githubusercontent.com/679144/85109839-42e9de80-b212-11ea-9262-909618529bc6.png)

**Comment by alexdima** [comment]
Here is our philosophy around embedded languages, let's take HTML as an example since it is so well known and understood.

```html
<html>
<head>
	<style>
		:root { --main-bg-color: brown; }
 	</style>
	<style>
		body { background-color: var(--main-bg-color); }
 	</style>
</head>
<body></body>
</html>
```

The coloring story is pretty straight-forward, basically because it is non-semantic. We have built infrastructure into Monarch such that parsers can be embedded in other parsers and they have a pop condition, etc. So each content of each `<style>` tag can be colorized independently. It does not matter what other `<style>` tags contain, each `<style>` tag is self-contained from a coloring point of view.

But things get trickier if you begin to consider a simple feature like suggestions. As you can see, it would be expected that in the second `<style>` tag you get suggestions from the first `<style>` tag. This indicates that an embedded language is not self-contained in the embedded section. It could even be that there is a `<link>` tag somewhere above and that would define the CSS variable, etc.

It is therefore our philosophy that rich language features, such as completions, highlights, etc must be provided by the outer language. For the HTML case, there is an HTML completion provider that should figure out where the suggest request is positioned in the HTML document and either return HTML completions or compute CSS completions. This is a complicated story that works only in VS Code because it involves the HTML language server pulling in the typescript language services and the CSS language services in order to offer good quality completions.

But the idea is that the outer language knows a lot about its domain and it should figure out what to do at each position. The editor cannot do anything language agnostic.
