### ISSUE TITLE
Symbol icon colors are broken

### ISSUE THREAD

**Issue by misolori** [microsoft/monaco-editor#2016]
![image](https://user-images.githubusercontent.com/35271042/85310349-aff6b180-b468-11ea-9d7b-3673a98f1034.png)

I believe this is because `.monaco-workbench` is in the class name here:

https://github.com/microsoft/vscode/blob/5e6729d9bdfda6b758cfff96b0d224e6703cbe06/src/vs/editor/contrib/documentSymbols/outlineTree.ts#L559-L577

cc @alexdima @rebornix

**Comment by alexdima** [comment]
Since these are now shared between the monaco editor and the workbench, we can either duplicate everything and have both `.monaco-workbench` and `.monaco-editor` as preselectors or we can just remove the preselector. I opt to remove the preselector, since the rules are about `.codicon` and that is a name made up for vs code so it shouldn't collide with people's CSS.
