### ISSUE TITLE
partly readonly default model 

### ISSUE THREAD

**Issue by Foroughi** [microsoft/monaco-editor#2024]
Im expecting the user to provide a specific piece of code like this : 

```
function Render($logger , $renderer , $element) {

    //Write your code here

}
```

Where user can only change the commented line or in better words im expecting the user to be able to only change the inside the function block. So it would be nice if we can provide a default-readonly-model for the editor. and eventually we can be sure what user has provided is exactly as what we were expecting.

**Comment by GNSubrahmanyam** [comment]
Reference: https://github.com/microsoft/monaco-editor/issues/953

**Comment by GNSubrahmanyam** [comment]
Hi @Foroughi Can you able to achieve this ?

**Comment by Foroughi** [comment]
Hi, @GNSubrahmanyam.  Ill have a look tomorrow, but just to clarify, the "SetEditableRange"  does not exist in 0.20.X version? this means they have removed it in the new versions ?!

**Comment by GNSubrahmanyam** [comment]
Yes, From the past few months i am exploring. Eventually i am endup using event.preventDefault() in keyDown, keyUp, mouseDown, mouseUp in those range. But this not working properly. Reference: https://github.com/eclipse/eclipse.jdt.ls/issues/1505

**Comment by GNSubrahmanyam** [comment]
If we can sync together we can acheive this.

**Comment by GNSubrahmanyam** [comment]
Hi @Foroughi , Did you get time to explore this ?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
