### ISSUE TITLE
Does not match a mouse position when zooming in browser

### ISSUE THREAD

**Issue by shxowlstjnoh** [microsoft/monaco-editor#2026]
Monaco-editor version: 0.20.0
Browser: Chrome
OS: Mac

Steps:

1. Zoom in a browser (using shortcut : cmdctrl -)
2. Doing Until 80%
3. The cursor, selection and highlighting don't match a mouse position.

I found out this bug using the Theia at first. 

Could you fix it? 

Thanks

**Comment by alexdima** [comment]
I could not reproduce at https://microsoft.github.io/monaco-editor/ . I have zoomed out, and while I see some rendering artefacts (caused by browser zoom rounding errors) the cursor position / selection are rendered OK:

![Kapture 2020-09-09 at 11 32 05](https://user-images.githubusercontent.com/5047891/92581563-21881400-f290-11ea-9f70-e8badcd89330.gif)

**Comment by shxowlstjnoh** [comment]
The problem doesn't occur now. Thanks for checking this out.
