### ISSUE TITLE
Support for Kusto

### ISSUE THREAD

**Issue by SaiBalaji202** [microsoft/monaco-editor#2032]
Does this editor support Kusto Query Language?

**Comment by 0xThiebaut** [comment]
Would it be possible to consider transferring the [Azure/monaco-kusto](https://github.com/Azure/monaco-kusto) repository under this one to ensure this Microsoft language is shipped by default?

**Comment by yrue** [comment]
Any update about this request? Would it be possible to transfer the [@kusto/monaco-kusto](https://www.npmjs.com/package/@kusto/monaco-kusto) under this one?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
