### ISSUE TITLE
Too aggressive tokenization

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#2054]
**monaco-editor version:** 0.20.0
**Browser:** Chrome 80-something
**OS:** macOS 10.14
**Playground code that reproduces the issue:**

The code is available [here](https://gist.github.com/fabiospampinato/470ef58744a98bddee818b2a846494f8), I posted it as a gist as it weighs megabytes.

The issue seems essentially that the entire document is being tokenized, leading to a huge amount of work for very long documents:

![image](https://user-images.githubusercontent.com/1812093/88436011-4e28bf00-cdfb-11ea-846e-93c15ede3b18.png)

Pretty much all of the work seems to be spent tokenizing:

![image](https://user-images.githubusercontent.com/1812093/88436040-5bde4480-cdfb-11ea-817d-be0e64090cd9.png)

And there really weren't that many characters to render at all, I'd expect this to render within a few frames:

![image](https://user-images.githubusercontent.com/1812093/88436085-7adcd680-cdfb-11ea-99d3-7b230669422b.png)

I think lines should be tokenized as soon as they become visible essentially, and there seems to be the code required for doing that already, but for some reason that doesn't seem what's going on here. Is that optimization disabled for Monarch language definitions? Can I do anything to achieve reasonable performance in this case?

**Comment by fabiospampinato** [comment]
vscode seems to be affected by this as well, it sounds like a pretty big perf issue probably worth fixing.

**Comment by rcjsuen** [comment]
> vscode seems to be affected by this as well, it sounds like a pretty big perf issue probably worth fixing.

If Visual Studio Code is also affected, I suggest you open a ticket over there for more visibility and then link it to this one.

**Comment by nrayburn-tech** [comment]
One thing that comes to mind, if the lines are not tokenized then the minimap wouldn't have the correct highlighting.  Right?  Outside of that, I don't know all of what is included in tokenization.

**Comment by fabiospampinato** [comment]
@nrayburn-tech That's only right if the last line of the document is shown in the minimap, which is not the case for my snippet, which has the minimap disabled even.

**Comment by alexdima** [comment]
- tokenization is done eagerly for the entire document.
- the reason is to allow that you jump to any place (even at the end of the document) and see correct colors immediately.
- we have an approximate colorizing of the viewport, where we take the lines with decreasing indent from before the viewport and try to use those as a way to get an initial state at the beginning of the viewport, but that is not correct, it works OK in about 90% of cases. Unfortunately, tokenization must be done entirely top - current viewport in order to colorize a viewport correctly. That is because something like `/*` can be tucked away somewhere above the viewport, anywhere, and it would make everything a comment, etc.
- the eager tokenization is implemented with yielding every 5ms or so and is only executed for visible text models. It would be good to move it to a web worker, but currently it runs on the UI thread.

**Comment by fabiospampinato** [comment]
Currently tokenization doesn't block the main thread for too long so even if it takes multiple seconds for the initial tokenization it's not too bad. Moving that to a worker thread sounds like a good idea too.

A few rough ideas on how to potentially improve this further for huge documents:

- maybe if tokenization is taking already longer than a second, and the user's cursor is more than 10k lines away from the last tokenized line, maybe tokenization should be paused and then resumed later on when the user gets closer to the remaining untokenized portion of the document
- maybe after a point further non-visible lines should be tokenized only when `requestIdleCallback` says there's some spare time available
- maybe the position of the cursors in the last few seconds or so should be taken into account too, like if I happen to insert some text at the very top of a huge document and that happens to be the first token of a multi-line comment it's unlikely that I will actually want the entire thing to become a comment, so re-tokenizing an arbitrary number of lines is probably going to be excessive if the user keeps typing

**Comment by nrayburn-tech** [comment]
@alexdima any pointers for moving the tokenization into a web worker?  I can look into that.

**Comment by alexdima** [comment]
I have started this for vscode with textmate and last time it could be turned on via https://github.com/microsoft/vscode/blob/e3f0a1bea54381eee3c4122a0ef30a4f765456a8/src/vs/workbench/services/textMate/electron-browser/textMateService.ts#L30 <- if you follow that through you should see how this could be done.

IMHO this is not necessarily very difficult to implement, but there are some conceptual blocking problems, where some editor commands (including typing) assume that tokenization can be done synchronously. There are some editor features where editing can be influenced by if the text is a string, a comment, etc (autoclosing characters, electric brackets, etc).

**Comment by Rheeseyb** [comment]
> the eager tokenization is implemented with yielding every 5ms or so

@alexdima this appears to not be the case for files with long lines, since (from what I understood by digging into the vs code repo) the tokenization process operates on a line at a time. I'm not sure if it's worth looking into further breaking that down to allow more yielding?

The example I was using to test this is https://github.com/google/draco/blob/master/javascript/draco_wasm_wrapper.js

**Comment by alexdima** [comment]
Yes, the "smallest" tokenization step is to tokenize one line. So if a line takes longer to tokenize than 5ms, then the yielding will be delayed.

**Comment by hediet** [comment]
VS Code has async tokenization now (however, not the monaco editor, as it uses monarch).

Please create individual feature requests for actionable steps (e.g. for the ideas you listed). For some of those, we might accept PRs.

I'll close this issue, as we don't plan to change the eager tokenization.

Thanks for understanding!
