### ISSUE TITLE
Tagged string w/ their own document types

### ISSUE THREAD

**Issue by arcanis** [microsoft/monaco-editor#2056]
I'm having a file similar to the following:

```tsx
doSomething({
  stylesheet: css `
    .foobar {
      color: red;
    }
  `,
});
```

The problem is that it gets interpreted as pure JS (which it technically is), so the CSS content is displayed as a simple string. In a perfect world it would however be nice if Monaco was able to "attach" the internal CSS highlighter to specific template strings.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
