### ISSUE TITLE
Add opacity to ITokenThemeRule or allow colors to have #RRGGBB[AA] for tokens

### ISSUE THREAD

**Issue by dmnsgn** [microsoft/monaco-editor#2061]
Similarly to https://github.com/microsoft/monaco-editor/issues/1247, some more customisation of the tokens would be nice.

I am specifically referring to **opacity** as many vscode themes use #RRGGBB[AA] it and the color regex in the tokenization phase is excluding alpha:

```js
        var colorRegExp = /^#?([0-9A-Fa-f]{6})([0-9A-Fa-f]{2})?$/;
        var match = color.match(colorRegExp);
        if (!match) {
            throw new Error('Illegal value for token color: ' + color);
        }
        color = match[1].toUpperCase();
```

Issue encountered when converting a vscode theme for `monaco-textmate`

**Comment by alexdima** [comment]
This can be easily sorted out on your side. If the background color consists of `br`, `bg`, `bb` and your color of `r`,`g`,`b`,`a` you can remove the opacity by computing the new color `r * a + br * (255-a)`, `g * a + bg * (1-a)`, `b * a + bb * (1-a)`. This is much better suited for the editor because it will allow the minimap to render colors correctly (the minimap does not render the alpha channel).

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
