### ISSUE TITLE
How I can know certain line is folded? If this line is in a folded region, which method I can use to unfold this region?

### ISSUE THREAD

**Issue by piaoliusihai** [microsoft/monaco-editor#2089]
I need to know the status of one line that whether it's in a folded region or not ? If is's in a folded region, which method in the API I can use to unfold this region?

Could someone help me with this problem and thanks a lot!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
