### ISSUE TITLE
text is not visible when using Grammarly chrome extension

### ISSUE THREAD

**Issue by dudif91** [microsoft/monaco-editor#2109]
Hi, I'm using Monaco editor on my web site, and also I have a chrome extension called Grammarly.
whenever this extension is on, my text doesn't appear in the Monaco editor until I open chrome developer tools and then the text suddenly appears

**monaco-editor version:** newest
**Browser:** chrome

**Comment by Pranomvignesh** [comment]
@dudif91 I recently faced a similar issue on using Grammarly ... I wanted to clarify something before jumping on to the workaround, 

1. Are you initiating Monaco-editor inside an iframe? 
2. Are you using src tags to load the HTML content inside the iframe?

**Comment by dudif91** [comment]
@Pranomvignesh no i'm using monaco-editor as an npm module inside Vue.js application

**Comment by Pranomvignesh** [comment]
@dudif91 are you able to reproduce this in Monaco-editor playground?

**Comment by dudif91** [comment]
@Pranomvignesh no

**Comment by dudif91** [comment]
@Pranomvignesh so you think you have a workaround that can help me solve this case?

**Comment by Pranomvignesh** [comment]
@dudif91 I had the same issue, it is because the iframe's readyState is getting modified by those chrome extensions, and so I watched the readyState for its change and after the complete, I initiated the Monaco editor, This solved the problem for me

Your case seems to be different from mine, so I think my workaround won't help you

**Comment by dudif91** [comment]
@Pranomvignesh actually your advice was helpful.
I've delayed the monaco-editor initialisation with a timeout and it seems to solve the issue.

tnx!

**Comment by Pranomvignesh** [comment]
@dudif91 That's nice. If possible, consider using **requestAnimationFrame**, as settimeout and setinterval will require an arbitrary value for watching,  and that arbitrary value may not be sufficient if the internet connection is slow (or) slowness in loading due to some other reasons
```javascript 
// this is what i did for watching
const checkForReadyState = function(){
  const doc = iframe.contentDocument; // here you have to use your document
  if(doc.readyState === 'complete'){
    initiateMonacoInside(iframe);
  }else{
    window.requestAnimationFrame(checkForReadyState)
  }
}
checkForReadyState();
```
I don't know for some reason, `onreadystatechange` method is not properly working for me, so I made this
This won't overload the event queue, with a lot of async calls

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
