### ISSUE TITLE
Monaco TypeScript master broken in amd build?

### ISSUE THREAD

**Issue by orta** [microsoft/monaco-editor#2111]
**monaco-editor version:** 2a99615
**Browser:** N/A
**OS:** N/A
**Playground code that reproduces the issue:** I don't think its set up to run on commits

The TS site builds a nightly version of both Monaco Editor and Monaco TS [here](https://github.com/microsoft/TypeScript-Make-Monaco-Builds/)

The build yesterday broke at runtime in what I think is monaco-typescript code:

- Two days ago: 🟢   https://www.typescriptlang.org/play?ts=4.1.0-dev.20200906#code/MYewdgzgLgBAFgUwDZJDAvDARAdxAJyQBMsAoIA
- One day ago: 🟢  https://www.typescriptlang.org/play?ts=4.1.0-dev.20200907#code/MYewdgzgLgBAFgUwDZJDAvDARAdxAJyQBMsAoIA
- This morning: 🔴  https://www.typescriptlang.org/play?ts=4.1.0-dev.20200908#code/MYewdgzgLgBAFgUwDZJDAvDARAdxAJyQBMsAoIA

The raised issue is `n.Emitter is not a constructor` and when you go back in the trace it is requiring `monaco.contribution.ts` where it fails, [likely here](https://github.com/microsoft/monaco-typescript/blob/70d1cb17042917b13cf8e817ab41a9f8b75b2b4f/src/monaco.contribution.ts#L465-L466):

```ts
private _onDidChange = new Emitter<void>();
private _onDidExtraLibsChange = new Emitter<void>();
```

Maybe https://github.com/microsoft/monaco-typescript/commit/ee95401a407e42e1044813087ba6dc621ecc25e9 ? 

( Left notes because I'm about go to hit meetings for the day )

**Comment by spahnke** [comment]
I had the same problem when I tried to put a current monaco-typescript build into the 0.20.0 editor ~10 hours ago. But I also assume this is maybe fixed by https://github.com/microsoft/monaco-editor/commit/2a996151d74d0e48102c47ea4c15836023d32f94#diff-b9e12334e9eafd8341a6107dd98510c9R199-R202 (that was ~5 hours ago, and I don't know what "morning" means to you 😄 ).

**Comment by spahnke** [comment]
Hmm, seems I misread the error message last night. So yesterday I wanted to test if I could put a current build of monaco-typescript in the existing 0.20.0 version (AMD) and got the error `cannot read property Emitter of undefined` meaning the global `monaco` instance was not available. For you though it is available but the `Emitter` cannot be constructed. My error is indeed fixed by the diff that I referenced (I just added the `"vs/editor/editor.api"` part into the contribution part) and now everything works for me.

Comparing the monaco-typescript contribution in `editor.main.js` in your broken build with how it works for me I see the following:
Your build (I omitted some stuff from the beginning of the line, this starts at colum 234)
```js
define("vs/language/typescript/fillers/monaco-editor-core",[],(function(){return self.monaco})),define("vs/language/typescript/monaco.contribution",["require","exports","./lib/typescriptServicesMetadata","./fillers/monaco-editor-core","vs/editor/editor.api"],
```
What works for me
```js
define("vs/language/typescript/fillers/monaco-editor-core",["vs/editor/editor.api"],(function(a){return self.monaco})),define("vs/language/typescript/monaco.contribution",["require","exports","./lib/typescriptServicesMetadata","./fillers/monaco-editor-core"]
```

I think the `"vs/editor/editor.api"` dependency might be in the wrong place for you and you're missing `"./fillers/monaco-editor-core"` in the second `define`.

**Comment by orta** [comment]
I see, makes sense @spahnke - maybe the build was triggered in between the updates of monaco and monaco-ts. 

Thanks for the deep dive, I think your point is right. I'll test it locally with both masters and see if it works 👍🏻

**Comment by alexdima** [comment]
I've pushed quite some refactorings to get rid of the usage of the global `monaco` in the ESM case.

When running the AMD variant from source, `fillers/monaco-editor-core` must be redirected to `fillers/monaco-editor-core-amd` via an AMD `paths` config. The two samples [from here](https://github.com/microsoft/monaco-typescript/tree/master/test) show this.

The built version generated in `/release/` will have this AMD module already substituted.

Please LMK if you need any more help.

**Comment by orta** [comment]
Cool, yeah, the TS site uses the release versions- _I think_ it was that the change to add the dep wasn't applied to all the parts in an amd release build. See #2118

**Comment by alexdima** [comment]
:+1: The minified variants were using `"` instead of `'`. This was a problem for all the `monaco-*` plugins, not just for TS. I hope things will work now.

**Comment by orta** [comment]
Confirmed that the above PR fixes it 👍🏻
