### ISSUE TITLE
Disable Cache is not preventing workerMain.js from loading twice

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2113]
Check the comment for the old issue [here](https://github.com/microsoft/monaco-editor/issues/1983#issuecomment-687239481)

I guess disable cache, **will not solve the issue**, as the **network call is initiated from Monaco** and disable cache just gets the response directly from the server and not looks into the browser cache

<img width="1680" alt="Screen Shot 2020-09-04 at 9 41 19 PM" src="https://user-images.githubusercontent.com/29809906/92261893-e5ebf380-eef7-11ea-8db4-daf22fdeeb5c.png">

**I have created a new issue, as the old issue was closed and I still face the same problem**

_Originally posted by @Pranomvignesh in https://github.com/microsoft/monaco-editor/issues/1983#issuecomment-687246636_

**Comment by spahnke** [comment]
If you're using JavaScript or TypeScript as your editor language then the monaco-typescript contribution starts two web workers to enable code completion, etc. Each of those web workers needs to load the `workerMain.js` file. That's why you're seeing it twice in the network panel.
![grafik](https://user-images.githubusercontent.com/25029871/92574005-d4ec0b00-f286-11ea-92ba-cedfd444af4d.png)

**Comment by Pranomvignesh** [comment]
@spahnke Thanks for clarifying this issue
