### ISSUE TITLE
Provider for alternative display of json objects

### ISSUE THREAD

**Issue by altoblond** [microsoft/monaco-editor#2114]
Hello,

I am trying to setup a language where some of my functions take complex objects as parameters, for example:
`myFunction({type:"complexObject",name:"object1", hasValue:true}, {type:"complexValue", value:2})`

I would like to be able to ease reading for the user by folding json objects and display them in an alternative short way while still providing a mean for the user to unfold them to see full content.

So by default the IDE would show:
`myFunction(_object1_,_2_)`

and user would be able to click on _object1_ or _2_ to display the full json content. Edition would require typing the full json object, I do not have issue with this.

Any advice on how to proceed?

**Comment by altoblond** [comment]
Maybe extending folderProvider could solve my issue?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
