### ISSUE TITLE
addExtraLib but with exat library name

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/monaco-editor#2142]
Hello,

I use monaco editor to add scripting functionality to my app.
So the script's are run directly, no backend compilation done.

Problem is now, if i add a lib like this:
 
      monaco.languages.typescript.typescriptDefaults.addExtraLib('....',  '/dist/queryT.js')

you could also import the lib with this line:

       import { QueryT } from '/dist/queryT';

without using the extension. But then it will fail to run in browser. Is there a way to say, the import has to exactly look how it is defined?

**Comment by alexdima** [comment]
There are many ways to write `.d.ts` files. You can use `declare module '...' { ... }` or other patterns inside the `.d.ts` file itself. Please consult the TypeScript documentation about this.

**Comment by jogibear9988** [comment]
????

did you read my question?

the problem is, that a import without the ".js" extension is also valid.
I wanted to know, is there a way, that monaco checks that the import matches the exact filename, hand over to addExtraLib call.

**Comment by alexdima** [comment]
@jogibear9988 Can you please search existing questions -- https://github.com/microsoft/monaco-editor/issues?q=is%3Aissue+addExtraLib . You can see there are many patterns for how to write definition files: e.g. https://github.com/microsoft/monaco-editor/issues/2092

This is due to a lot of flexibility in the TypeScript compiler and language service and is implemented by the TypeScript project itself, not by the Monaco Editor. There is an entire section on Declaration Files in the TypeScript documentation -- https://www.typescriptlang.org/docs/ , https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
