### ISSUE TITLE
Editor not localizing VSCode error messages

### ISSUE THREAD

**Issue by tomatesoup** [microsoft/monaco-editor#2174]
When running a VM in Chinese, the editor displays error messages in English. The editor seems to be using the [default error message from VSCode](https://github.com/microsoft/vscode/search?q=cannot%20edit%20in%20read-only%20editor&unscoped_q=cannot%20edit%20in%20read-only%20editor), and not localizing the message correctly.

**monaco-editor version:** 0.20.0-bugfix.1
**Browser:** Google Chrome 85.0.4183.121
**OS:** Windows 10

Screenshot of the error message:
![image](https://user-images.githubusercontent.com/8763531/95072966-5d39c080-070c-11eb-8774-0fe2cce7fca7.png)

```js
```

**Comment by alexdima** [comment]
Two things:
- that appears to be an older version of the editor (<0.20.0) or perhaps you show that message on your side because read only editors no longer show that message on the web since 0.20.0. See https://github.com/microsoft/monaco-editor/issues/1873
- Chinese works fine for me when I try it out with the sample at https://github.com/microsoft/monaco-editor-samples/tree/master/browser-amd-localized and with the change:
![image](https://user-images.githubusercontent.com/5047891/95076387-0c2ccb00-0712-11eb-9d95-5b10e6759a08.png)

![image](https://user-images.githubusercontent.com/5047891/95076423-19e25080-0712-11eb-9e5a-ceba21e36b26.png)
