### ISSUE TITLE
Add support for Nim syntax highlighting

### ISSUE THREAD

**Issue by 6543** [microsoft/monaco-editor#2185]
Issue Source: https://github.com/go-gitea/gitea/issues/13089
Issue Source Route: https://codeberg.org/Codeberg/Community/issues/305

2. Otherwise, provide steps that reproduce the problem in VS Code web at:
 -- https://vscode-web-test-playground.azurewebsites.net/

 - create a new file `test.nim`
 - copy content from https://codeberg.org/tanmatsu/fika/src/branch/master/src/fika.nim
 - -> no highlighting

**monaco-editor version:** 0.20.0 (go-gitea/gitea)
**Browser:*firefox*
**OS:*Linux*
**Playground code that reproduces the issue:**

```
just use playground of azure or gitea's code editor ....
```

**Comment by Prinzhorn** [comment]
Is this a bug or a feature request? Has Nim syntax highlighting worked before and is now broken? Or has it never worked? I don't see Nim here https://github.com/microsoft/monaco-languages/tree/master/src but you can contribute Nim support like others have done with other languages https://github.com/microsoft/monaco-languages/pull/98

**Comment by 6543** [comment]
@Prinzhorn I think it's a feature request

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
