### ISSUE TITLE
Suggest code actions based on the hover position

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2193]
I register a hover provider and a code action provider as follows:

```
  let da = new DiagnosticsAdapter(LANGUAGE_ID) // where we set markers by monaco.editor.setModelMarkers

  monaco.languages.registerHoverProvider(LANGUAGE_ID, {
    provideHover: (model, position, token) => {
        ... ...
    }
  });

  monaco.languages.registerCodeActionProvider(LANGUAGE_ID, {
    provideCodeActions: (model, _range, context, token) => {
        console.log("_range", _range)
        // use markers to make code actions
       ... ...
    }
  });
```

The result of this code is that, unlike `provideHover`, `provideCodeActions` does not have information like `position`. Thus, the code actions provided by Quick Fix are always the same no matter where we hover in the editor. 

I tried to use `_range`, but I observed that `_range` printed in `provideCodeActions` is always the superset of the area of all the markers, it is not related to the position of the hover.

Coud anyone help?

**Comment by alexdima** [comment]
Please see this JSDoc:
```
		/**
		 * Provide commands for the given document and range.
		 *
		 * @param document The document in which the command was invoked.
		 * @param range The selector or range for which the command was invoked. This will always be a selection if
		 * there is a currently active editor.
		 * @param context Context carrying additional information.
		 * @param token A cancellation token.
		 * @return An array of commands, quick fixes, or refactorings or a thenable of such. The lack of a result can be
		 * signaled by returning `undefined`, `null`, or an empty array.
		 */
```

**Comment by rexar-fr** [comment]
The problem is having two nested markers, when hovering on the outer one the context passed for `provideCodeActions` has both markers.
 
Here is an example to illustrate the problem: 
![image](https://user-images.githubusercontent.com/61843370/122563791-eac40300-d044-11eb-8e57-562876927126.png)
Using `monaco.editor.setModelMarkers` I setup a marker for the outer IF and the inner IF. 
Hovering on the outer IF would show the message only for the outer marker (as expected). 
![image](https://user-images.githubusercontent.com/61843370/122564088-41314180-d045-11eb-852d-f0de0c54d6c1.png)
But the markers found in the context passed for `provideCodeActions` have both markers the inner one and the outer one. Since I am using the markers in the context to provide an action, I am providing actions for both the inner marker and the outer marker (not as expected). 
![image](https://user-images.githubusercontent.com/61843370/122564660-e77d4700-d045-11eb-9068-231bf4838e9a.png)

**The expected behavior is to get only the outer marker in `context.markers` passed for `provideCodeActions`  while hovering on the outer marker.**
