### ISSUE TITLE
[DiffEditor] enableSplitViewResizing setting doesn't work

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#2203]
**monaco-editor version:** 0.21.2
**Browser:** Edge 86, Chrome 86, Firefox 82
**OS:** Windows 10

If try to grab the separator in the middle of the split view to resize the editors nothing happens. The last version where I can confirm that it worked is 0.18.1. I didn't test 0.19.x and 0.20.x unfortunately, so I can't tell where exactly the regression happened.

**Playground code that reproduces the issue:**

```js
var originalModel = monaco.editor.createModel("heLLo world!", "text/plain");
var modifiedModel = monaco.editor.createModel("hello orlando!", "text/plain");

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
    enableSplitViewResizing: true
});
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});
```

**Comment by x24git** [comment]
This appears to be fixed in the [VS Code source code](https://github.com/microsoft/vscode/commit/2f15e9d441094b2fac6536752c07898706155b69). It seems that the stylesheet controlling the sash (separator) width was moved to the VSC Workbench which is not normally included as part of the Monaco Editor.  As a result the sash has a width of zero in the current Monaco Editor. The linked commit puts back the sizing stylesheet for the sash into locations that get shimmed into Monaco Libraries.  I will assume the next version of Monaco Editor will automatically include this change.

If you need an immediate fix, you can manually inject your own stylesheet with these properties:
```cs
:root {
	--sash-size: 4px;
}
.monaco-sash.vertical {
	cursor: ew-resize;
	top: 0;
	width: var(--sash-size);
	height: 100%;
}

.monaco-sash.horizontal {
	cursor: ns-resize;
	left: 0;
	width: 100%;
	height: var(--sash-size);
}

.monaco-sash:not(.disabled).orthogonal-start::before, .monaco-sash:not(.disabled).orthogonal-end::after {
	content: ' ';
	height: calc(var(--sash-size) * 2);
	width: calc(var(--sash-size) * 2);
	z-index: 100;
	display: block;
	cursor: all-scroll; position: absolute;
}

.monaco-sash.orthogonal-start.vertical::before { left: -calc(var(--sash-size) / 2); top: -var(--sash-size); }
.monaco-sash.orthogonal-end.vertical::after { left: -calc(var(--sash-size) / 2); bottom: -var(--sash-size); }
.monaco-sash.orthogonal-start.horizontal::before { top: -calc(var(--sash-size) / 2); left: -var(--sash-size); }
.monaco-sash.orthogonal-end.horizontal::after { top: -calc(var(--sash-size) / 2); right: -var(--sash-size); }

```

You can also insert this into the sash.css document within the Monaco Distro. `/esm/vs/base/browser/ui/sash/sash.css`

**Comment by spahnke** [comment]
Thanks for the analysis and the workaround!
