### ISSUE TITLE
JSONata language support

### ISSUE THREAD

**Issue by Steve-Mcl** [microsoft/monaco-editor#2207]
Hi, I would love to replace ACE Editor in the node-red project with monaco (and mostly I have succeeded) but there is one last hurdle before I can raise a PR for it - lack of JSONata support.

I have found [this](https://www.npmjs.com/package/@crft/jsonata-code-completion) and [this](https://github.com/Allam76/jsonata-code-completion) but I have no idea how to implement this. 

If adding JSONata is a "no-go" then perhaps instructions on how I might achieve this in a fork OR worst case, how to do very basic keyword colouring & simple syntax checks (closed brackets / quotes, comments etc)

**Comment by Prinzhorn** [comment]
> how to do very basic keyword colouring & simple syntax checks (closed brackets / quotes, comments etc)

https://microsoft.github.io/monaco-editor/monarch.html

**Comment by RajuSuranagi** [comment]
Did we make any progress here? Interested in the JSONata support for Monaco Editor

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
