### ISSUE TITLE
Line Number Mappings for Compiled Typescript

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/monaco-editor#2216]
I'd like to have a way to access the mapping for the compiled Typescript (wich I get via getEmitOutput())

I run the javascript, but to display the error on the correct line, I need the mapping for the lines JS<=>TS

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Comment by jogibear9988** [comment]
@hediet isn't this information already somewhere? you include the whole typescript compiler, or am I wrong? Maybe a callback to the the sourcemap is possible?

**Comment by hediet** [comment]
> Maybe a callback to the the sourcemap is possible?

I think you can request them somehow from the ts worker, but I'm not sure.
