### ISSUE TITLE
Duplicate suggestion in auto completion

### ISSUE THREAD

**Issue by sinanasiriamirbande** [microsoft/monaco-editor#2217]
I'm working with Monaco on Angular project.

the problem is here when route change in onDestory i dispose the editor but registerCompletionItemProvider does not destroy and  i have duplicate suggestions.

```

// call in onInit
  initMonaco(): void {

    this._editor = monaco.editor.create(this.editorContent.nativeElement, this._options);
    this._editor.focus();
    this.listenToChange();
    this.subscribeToWindowResize();

 monaco.languages.registerCompletionItemProvider('sql', this.getSqlCompletionProvider());
  }

 

  ngOnDestroy() {
    monaco.languages.registerCompletionItemProvider('sql', {
      provideCompletionItems: () => {
        return {suggestions: []};
      },
    }).dispose();
    if (this._editor) {
      this._editor.dispose();
      this._editor = undefined;
    }
}
```

**Comment by Pranomvignesh** [comment]
@sinanasiriamirbande , I think instead of disposing the `CompletionItemProvider` which you have created in `initMonaco` function you are creating a new `CompletionItemProvider` inside `ngOnDestroy` and disposing it.
The dispose inside the `ngOnDestroy` function will only dispose the `CompletionItemProvider`  created inside the `ngOnDestroy` not the one that is created in `initMonaco` function

```javascript 
  initMonaco(): void {

    this._editor = monaco.editor.create(this.editorContent.nativeElement, this._options);
    this._editor.focus();
    this.listenToChange();
    this.subscribeToWindowResize();
   // Save the disposable here
   this.completionProvider = monaco.languages.registerCompletionItemProvider('sql', this.getSqlCompletionProvider());
  }

 

  ngOnDestroy() {
   // dispose that instance 
    this.completionProvider.dispose();
    if (this._editor) {
      this._editor.dispose();
      this._editor = undefined;
    }
}
``` 
**I think this might work ...**

For More info , Check [Api Doc of Monaco](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registercompletionitemprovider)

**Comment by sinanasiriamirbande** [comment]
@Pranomvignesh   thank you, it worked

**Comment by ArcherWong** [comment]
bang
