### ISSUE TITLE
Line separator is not appearing for removed part in inline diff view

### ISSUE THREAD

**Issue by harshadsindhav** [microsoft/monaco-editor#2224]
**monaco-editor version:** 0.21.2
**Browser:** any
**OS:** any
**Playground code that reproduces the issue:**
```
var originalModel = monaco.editor.createModel("{\n\t\"parameters\":\n\t{\n\t\t\"id\":{\n\t\t\t\"widgetId\":{\n\t\t\t\t\"id\":\"10000\"\n\t\t}\n\t}\n\t}\n}\", \"json");
var modifiedModel = monaco.editor.createModel("{\n\t\"parameters\":\n\t{\n\t\t\"id\":{\n\t\t\t\n\n\t\t\t\t\"id\":\"10000\"\n\t\t\t}\n\t\t}\n\t}\n}\", \"json");

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
// You can optionally disable the resizing
enableSplitViewResizing: false,

// Render the diff inline
renderSideBySide: false
});
diffEditor.setModel({
original: originalModel,
modified: modifiedModel
});
```

Hi team,

Hope you all are doing great!!

I am seeing a issue with diff editor that vertical line separator is not appearing for removed (red) text in inline diff mode.

Can anyone please help ?

Please refer image for reference.
![Inline diff line separator](https://user-images.githubusercontent.com/13543626/99768161-5afbbc00-2b2a-11eb-8e88-0024fa0d3901.jpg)

**Comment by Prinzhorn** [comment]
🛑 STOP 🛑 STOP 🛑 STOP 🛑

1. Try to reproduce in VS Code and file issue directly at:
 -- https://github.com/microsoft/vscode/issues

2. Otherwise, provide steps that reproduce the problem in VS Code web at:
 -- https://vscode-web-test-playground.azurewebsites.net/

3. Otherwise, provide steps that reproduce the problem at the Monaco Editor homepage
 -- https://microsoft.github.io/monaco-editor/

4. Otherwise, provide a Playground code snippet
 -- https://microsoft.github.io/monaco-editor/playground.html

5. Otherwise, provide a self-contained git repository / HTML page

**Comment by harshadsindhav** [comment]
Hi @Prinzhorn ,
Thanks for your reply.

I have updated description, please have a look.

-Harshad

**Comment by Prinzhorn** [comment]
Your code is broken and cannot be copied, please properly format it using markdown code blocks https://guides.github.com/features/mastering-markdown/

**Comment by harshadsindhav** [comment]
@Prinzhorn , Thanks for drewing my attention. I have updated the description. :)

**Comment by alexdima** [comment]
@harshadsindhav That is not a "line separator". That is the indent guide from the modified editor. The indent guide appears on the content of the modified editor and scrolls with that content.
