### ISSUE TITLE
When my language is set to JavaScript, I want to turn off the html prompt suggestion. The suggestion that is triggered when I enter a point contains the variables I wrote.

### ISSUE THREAD

**Issue by shiyabin** [microsoft/monaco-editor#2234]
![image](https://user-images.githubusercontent.com/31621564/100432784-0aa9ce80-30d5-11eb-96e1-92de5a3e6bd1.png)

**Comment by alexdima** [comment]
This is the behavior of the TypeScript language service (which is used for computing suggestions) for JavaScript. It always also proposes identifiers from your file. AFAIK this cannot be turned off via any option.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
