### ISSUE TITLE
Accept string for `fontSize`

### ISSUE THREAD

**Issue by silverwind** [microsoft/monaco-editor#2242]
It'd be great if [`fontSize`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#fontsize) could also be accepted as a string that's inserted as-is into CSS. This will allow usage such as `fontSize: "var(--font-size)"` or `fontSize: "1em"` instead of only pixel size like now.

Related: https://github.com/microsoft/monaco-editor/issues/1092

**Comment by limitedmage** [comment]
Please add support for this, this is an accessibility issue since currently the font size needs to be in pixels, which prevents users from modifying their browsers settings for larger default fonts.

**Comment by mofux** [comment]
The font size is used for various height calculations in the editor. Allowing a non-pixel value would mean that the actual font size in pixels would have to be measured by the editor before the first render.

This is not easy to do, because the font family used by the editor may not have loaded at the time the editor is rendered the first time.

However, you could try to implement this functionality on you own:

- Create a `div` with one ore more big characters (e.g. `W`) and set the desired editor font-family and font-size (e.g. `1em`) as its style.
- Add the div to your document (you'll want to hide it visually, e.g. `opacity: 0; pointer-events: none`)
- Measure the height of your div (in px)  - e.g. `div.getBoundingClientRect()`
- Run `editor.updateOptions({ fontSize: yourMeasuredSize })`
- Bonus: You may want to add a `ResizeObserver` to your span, so you can re-measure and update the editor font size whenever the text inside your span changes (e.g. when the user zooms in on his browser or the font has finished loading)

---

Here is a sample that should work (paste in the playground)
https://microsoft.github.io/monaco-editor/playground.html

```javascript
// create the editor
var e = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

// create measure element
const measureEl = document.createElement('div');
measureEl.innerText = 'W';
measureEl.style.position = 'absolute';
measureEl.style.fontSize = '1em';
measureEl.style.fontFamily = e.getOption(monaco.editor.EditorOption.fontFamily);
measureEl.style.opacity = '0';
measureEl.style.pointerEvents = 'none';
document.body.appendChild(measureEl);

// re-measures the height of our measure element and updates the editor font size accordingly
const updateFontSize = () => {
    const rect = measureEl.getBoundingClientRect();
    const fontSize = rect.height;
    e.updateOptions({
        fontSize
    });
    console.log('update font size', fontSize, measureEl);
};

// update font size initially
updateFontSize();

// observe size changes
const observer = new ResizeObserver(() => updateFontSize());
observer.observe(measureEl);
```

**Comment by mike-lischke** [comment]
In a complex application with lots of editors this manual measuring is tricky as well. It would be better if monaco would just use a CSS font size. It can use `calc()` to determine relative sizes in other parts of the editor.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
