### ISSUE TITLE
Line Number not displayed in Manaco Editor createDiffEditor()

### ISSUE THREAD

**Issue by Aravin** [microsoft/monaco-editor#2248]
I am using the same code as playground sample: https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-multi-line-example

```js
      const monaco = require('monaco-editor');

      const originalModel = monaco.editor.createModel(leftText, 'text/plain');
      const modifiedModel = monaco.editor.createModel(rightText, 'text/plain');

      const diffEditor = monaco.editor.createDiffEditor(document.getElementById('diff-result'), {
        // You can optionally disable the resizing
        enableSplitViewResizing: true,
      });
      diffEditor.setModel({
        original: originalModel,
        modified: modifiedModel
      });
```

Result

![image](https://user-images.githubusercontent.com/4869265/101287338-b5c53100-3815-11eb-9137-866d1e359a96.png)

You can reproduce in realtime: https://www.epix.io/text/compare

**monaco-editor version:** 0.21.2
**Browser:** Chrome Web
**OS:** Windows 10
**Playground code that reproduces the issue:**

**Comment by alexdima** [comment]
@Aravin It looks like you have some piece of CSS on your page that is affecting the editor. You can try to use inspect element on the editor dom nodes that look out of place (like the text on the left overimposed with the hashed area) and investigate what CSS from your page ends up affecting the editor. Otherwise, you can try commenting out portions of your CSS until you discover which one it is.

**Comment by Aravin** [comment]
@alexdima 

I don't see any CSS override here.

**Comment by alexdima** [comment]
I am happy to take a look if you can provide a sample that reproduces in an empty `html` page.
