### ISSUE TITLE
vs-dark+ theme for monaco editor

### ISSUE THREAD

**Issue by JakubJaworskiPL** [microsoft/monaco-editor#2260]
Hi,

Have you considered adding vs-dark+ theme to monaco editor or replacing/improving regular vs-dark to "plus"?

Thanks
JJ

**Comment by ten-petr** [comment]
+1 This feature would be very helpful

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
