### ISSUE TITLE
Spaces char is different after past to OneNote and copying it back to the editor

### ISSUE THREAD

**Issue by raronen** [microsoft/monaco-editor#2268]
Reproduction steps:
1) open https://vscode-web-test-playground.azurewebsites.net/
2) Write "a b" in the editor:
![image](https://user-images.githubusercontent.com/50779771/102373693-249a4b00-3fc9-11eb-821a-ad2a568735c5.png)
2) Copy it to **OneNote** and the ReCopy it to the editor:
 
![image](https://user-images.githubusercontent.com/50779771/102373730-30860d00-3fc9-11eb-81fd-8425027359cd.png)

3) Go to Text compare site and there's a difference in the spacing:
![image](https://user-images.githubusercontent.com/50779771/102373856-527f8f80-3fc9-11eb-9cdc-52a1dd7de41e.png)

In our use case we save the text in a storage, and when we compare between the two - they doesn't equal because the spaces are different.

**Comment by alexdima** [comment]
When copying, the Monaco Editor writes two distinct entries to the OS clipboard: it writes the plain text, but also the text as HTML. AFAIK this is standard application behavior. For the HTML variant, in order to get whitespace alignment on monospace fonts, we use &nbsp; . This allows that indentation aligns. The application where the paste occurs gets to decide if it wants to paste the plain text content or the HTML content. Office suites usually offer an icon when pasting to choose which variant users want:
![image](https://user-images.githubusercontent.com/5047891/102694569-3dea0400-4222-11eb-8358-7660bc93a146.png)
The user needs to decide what is important for them, to get a good presentation (then they can keep the HTML version) or to get semantic content (then they can keep the plain text version).

**Comment by alexdima** [comment]
@raronen There is already an existing editor option that you can use to turn this off: `copyWithSyntaxHighlighting`, so you can use e.g.:

```
monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript",
    copyWithSyntaxHighlighting: false
});
```
