### ISSUE TITLE
Supporting all tokens for notIn clauses

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#2281]
I'd basically like to disable some auto-closing pairs in Markdown code blocks, the "notIn" property of auto-closing pairs objects seem to be exactly what I need, but it doesn't really work, it supports only a very limited list of hard-coded tokens:

https://github.com/microsoft/vscode/blob/7dde16206fd7a52577241b864c0349a2f0270ba6/src/vs/editor/common/modes/languageConfiguration.ts#L270-L286

All tokens should be supported for this to be useful for me.

**Comment by alexdima** [comment]
The root problem here is that tokens are dropped almost as soon as they are computed. For memory saving reasons, only color information (foreground, background), font style (bold, italic, underline), standard token type (regex, comment, string, other) and language id are stored per token.

**Comment by fabiospampinato** [comment]
I see 🤔 How do you suggest this should be fixed then? Is keeping all those tokens in memory _until_ the whole thing is tokenized actually a problem? Or maybe there should be an "auto-closing pair provider" that tells the editor in which ranges what auto-closing pairs are active etc. but that seems eccessive.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

---

This is a nice feature request, but it is very unlikely we can do this for the monaco editor.
