### ISSUE TITLE
API for determining if keypress would cause completion

### ISSUE THREAD

**Issue by rgov** [microsoft/monaco-editor#2291]
I would like to be able to handle the <kbd>Enter</kbd> key, but only if the user did *not* press it to accept a suggested completion. There does not appear to be an API for detecting this.

The closest I could come was,

```javascript
editor.onKeyDown((e) => {
    if (e.keyCode === monaco.KeyCode.Enter) {
        // If the editor is suggesting a completion of the user's input, we
        // should not intercept the key event.
        //
        // See vscode/src/vs/editor/contrib/suggest/suggestWidget.ts
        // See https://stackoverflow.com/q/62395001
        const suggestWidgetData = 
            editor._contentWidgets["editor.widget.suggestWidget"];
        const isSuggestWidgetOpen = 
            (suggestWidgetData !== undefined) &&
            (suggestWidgetData.widget.state === 3 /* Open */);
        if (isSuggestWidgetOpen) { return; }

        // ...
        e.stopPropagation();
        e.preventDefault();
    }
});
```

But it requires using some implementation details of the editor.

I'm not sure if it would be appropriate to also check whether the key is in `commitCharacters` of a potential completion entry.

**Comment by alexdima** [comment]
@rgov You can use context keys and negate the completion accepting keybinding:

The completion accepting keybinding is (you can find this by running vscode and using `F1 > Preferences: Open Default Keyboard Shortcuts (JSON)`:
```
{ "key": "enter",
  "command": "acceptSelectedSuggestion",
  "when": "acceptSuggestionOnEnter && suggestWidgetVisible && suggestionMakesTextEdit && textInputFocus" }, // let's call this X
```

You want that your keybinding executes when the focus is in the editor (and not in the find widget for example), so you want `editorTextFocus && !X`. `textInputFocus` is an alias for `editorTextFocus` that is there even for simple editor widgets, so you would end up with the when condition: `editorTextFocus && (!acceptSuggestionOnEnter || !suggestWidgetVisible || !suggestionMakesTextEdit)`. That needs to be distributed because the context key language does not support parens, arriving at `editorTextFocus && !acceptSuggestionOnEnter || editorTextFocus && !suggestWidgetVisible || editorTextFocus && !suggestionMakesTextEdit`

e.g. at https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance
```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

editor.addCommand(monaco.KeyCode.Enter, function() {
    alert('my command is executing!');
}, 'editorTextFocus && !acceptSuggestionOnEnter || editorTextFocus && !suggestWidgetVisible || editorTextFocus && !suggestionMakesTextEdit')
```
