### ISSUE TITLE
AutoComplete/ Suggest  - Highlighting Customization

### ISSUE THREAD

**Issue by Acampbell13** [microsoft/monaco-editor#2300]
Is there a way to highlight only continuous sub-strings for the suggestion popup. 
Because currently the editor highlights the first character which was found from the subString and not the continuous sub-strings.

**Example:**

![image](https://user-images.githubusercontent.com/43473488/103774694-48333d00-502d-11eb-8a6f-8824ea3fb71c.png)

- For the first suggestion ( isEmpty() ) it is correctly highlighted because within the suggestion no **"e"** occurs before within the subString.

- For the second suggestion ( elementAt()) I would like to highlight the continuous substring **"em"** and not the first **"e"** that occurs and then the **"m"*

Is there any way to influence the highlighting of the suggestion? 
Because the suggestion of my Editor, only contains suggestions that contain the already typed part as a continous substring. This might cause the user to think that the list allows non-continous substrings, confusing them when it does not.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
