### ISSUE TITLE
Accessing clipboard when opening suggestions list

### ISSUE THREAD

**Issue by izikl** [microsoft/monaco-editor#2307]
Users are prompt with clipboard access alert while they type:
<img src="https://user-images.githubusercontent.com/8294298/104661642-d2a71c80-567d-11eb-8418-38f992107482.png" width="300" height="200">

Expected: only show this alert when copy or pasting.
Actual: alert is shown when typing

To repro, go to : 
https://dataexplorer.azure.com/clusters/help/databases/Samples?query=H4sIAAAAAAAAA3POL8tMMbSMT8tJLOHlqlEoz0gtSlUISi3ILypxSSxJVbADACBs9toiAAAA

Login, if prompted, and TYPE (don't copy paste, type) `ago(2` after `| where ReportDate >`. 

After typing `2`, the clipboard access alert is shown, or if using Chrome incognito, a clipboard icon is shown: 
<img src="https://user-images.githubusercontent.com/8294298/104662156-09c9fd80-567f-11eb-86e1-c289c88cfd78.png" width="300" height="50">

This might be a duplicate of https://github.com/microsoft/monaco-editor/issues/2298 but in my use case the problem is the access itself to the clipboard and not any failures happen afterwards. 

### investigation
The error is coming from the suggestModel.ts in the `trigger` method when `existingItems` is not empty which happens when user starts a new word while IntelliSense shows. 

In code: 
When user types something _onNewContext is triggered which runs this code:
```typescript
if (ctx.leadingWord.word.length !== 0 && ctx.leadingWord.startColumn > this._context.leadingWord.startColumn) {
  // started a new word while IntelliSense shows -> retrigger

  // Select those providers have not contributed to this completion model and re-trigger completions for
  // them. Also adopt the existing items and merge them into the new completion model
  const inactiveProvider = new Set(CompletionProviderRegistry.all(this._editor.getModel()!));
  this._completionModel.allProvider.forEach(provider => inactiveProvider.delete(provider));
  const items = this._completionModel.adopt(new Set());
  this.trigger({ auto: this._context.auto, shy: false }, true, inactiveProvider, items);
  return;
}
```

if the "if statement" passes, then it calls method `trigger` with a non-empty list `items`. method `trigger` runs this code: 
```typescript
let clipboardText: string | undefined;
if (completions.needsClipboard || isNonEmptyArray(existingItems)) {
  clipboardText = await this._clipboardService.readText();
}
```

and since existingItems is not empty it will read from the clipboard. 

### questions 
1. Why intellisence logic reads from the clipboard? 
2. Is there a way to work around it? 

**monaco-editor version:** 0.21.2
**Browser:** tested on chrome and edge, but probably will repro on other browsers.
**OS:** all
**Playground code that reproduces the issue:** see above

**Comment by jrieken** [comment]
Very likely already fixed via https://github.com/microsoft/vscode/commit/96d61842bae1e5dd11f9ff6139fad9e3e5141401

**Comment by jrieken** [comment]
Closing as this is fixed in master. 

> Why intellisence logic reads from the clipboard?

Intellisense supports snippet insertions and snippets have the `$CLIPBOARD` variable. To support that variable we need to read the clipboard. We usually analyse completions for the usage of that variable and only read the clipboard when it is needed. However, when merging existing suggestions with new suggestions (which happens when a providers return an incomplete suggest result) we have "forgotten" what the original suggestions wanted and in that case we read the clipboard again. The [change](https://github.com/microsoft/vscode/commit/96d61842bae1e5dd11f9ff6139fad9e3e5141401) which is on master already does carry this knowledge around so that we don't read the clipboard unless needed. 

> Is there a way to work around it?

Not really, unless you can easily tweak your provider to not return incomplete completion lists.
