### ISSUE TITLE
License conflict MIT vs. Apache

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/monaco-editor#2315]
**monaco-editor version:** 0.20.0
**Browser:** any
**OS:** any

monaco-editor is built with a number of submodules, which is described in [CONTRIBUTING.md](https://github.com/microsoft/monaco-editor/blob/master/CONTRIBUTING.md). One of the modules is [monaco-typescript](https://github.com/Microsoft/monaco-typescript), which is released under MIT as well.

In one of my React projects I use the monaco-editor as an important part. The production build generated by Babel puts a file ts.worker.js.LICENSE in the output dir, which mentions that the license is Apache, not MIT. I would expect that the module and the worker use the same license (assuming here that the worker is actually implemented in that module).

Is this an oversight or do I misunderstand something here?

**Comment by alexdima** [comment]
The `monaco-typescript` project uses the TypeScript compiler. The TypeScript compiler is licensed under Apache. For development purposes (due to how we need to "massage" the `.js` files of the typescript compiler to make it compatible with AMD or ESM), we had to inline the typescript compiler sources inside `monaco-typescript`.

That is why there is an accompanying `ThirdPartyNotices.txt` file in the root of the `monaco-typescript` repository which credits the extra OSS present in the repository -- https://github.com/microsoft/monaco-typescript/blob/master/ThirdPartyNotices.txt

So to clarify, the `monaco-typescript` project uses the MIT license for all of its own sources (what is actually developed in that repository), but maintains and respects the license of the TypeScript project for the TypeScript compiler (which is inlined in the repository at https://github.com/microsoft/monaco-typescript/tree/master/src/lib ).

---

If you install the `monaco-editor` from npm, it will also come with a `LICENSE` file and a `ThirdPartyNotices.txt` file. The `LICENSE` file is MIT and the `ThirdPartyNotices.txt` lists the licenses of other OSS software that is bundled inside with the editor. e.g.:
- nodejs path library (https://github.com/nodejs/node/tree/43dd49c9782848c25e5b03448c8a0f923f13c158)
- string_scorer version 0.1.20 (https://github.com/joshaven/string_score)
- chjj-marked
- typescript
- HTML 5.1 W3C Working Draft version 08 October 2015
- JS Beautifier version 1.6.2
- Ionic documentation version 1.2.4
- vscode-swift version 0.0.1

**Comment by mike-lischke** [comment]
I see, thanks for the explanation. Very useful info!
