### ISSUE TITLE
registerCompletionItemProvider does not work for YAML

### ISSUE THREAD

**Issue by stanislavHamara** [microsoft/monaco-editor#2333]
**monaco-editor version:** 0.21.2
**Browser: Google Chrome Version 88.0.4324.96 (Official Build) (x86_64)**
**OS: macOS Catalina 10.15.7**
**Playground code that reproduces the issue:**

As initially raised in https://github.com/microsoft/monaco-editor/issues/1768 YAML suggestions do not work

```js
function createDependencyProposals(range) {
    // returning a static list of proposals, not even looking at the prefix (filtering is done by the Monaco editor),
    // here you could do a server side lookup
    return [
        {
            label: '"lodash"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "The Lodash library exported as Node.js modules.",
            insertText: '"lodash": "*"',
            range: range
        },
    ];
}


monaco.languages.registerCompletionItemProvider('yaml', {
    provideCompletionItems: function(model, position) {
        var word = model.getWordUntilPosition(position);
        var range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn
        };
        return {
            suggestions: createDependencyProposals(range)
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "yaml"
});
```

Working JSON:
![image](https://user-images.githubusercontent.com/6816380/106744537-cf1d0a80-6617-11eb-9b58-00539e5b839d.png)

Broken YAML:
![image](https://user-images.githubusercontent.com/6816380/106744692-ff64a900-6617-11eb-8eff-d6380d408e33.png)

**Comment by alexdima** [comment]
It turns out that the yaml tokenizer decides that everything is a string and then suggestions do not show by themselves (i.e. while typing), they only appear when pressing ctrl+space. The suggestions do not automatically appear because according to yaml's grammar, you are typing in a string and by default suggestions don't pop up by themselves in a string.

This can be configured using the `quickSuggestions` editor option e.g.:

```
monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "yaml",
    quickSuggestions: { other: true, strings: true }
});
```

See also https://github.com/microsoft/monaco-editor/issues/2273#issuecomment-768629737
