### ISSUE TITLE
Electron sample of text editor with file i/o

### ISSUE THREAD

**Issue by PerBothner** [microsoft/monaco-editor#2341]
It would be nice to see a sample for a complete minimal text editor that reads and writes files. I didn't see anything like that in monaco-editor-samples. I suggest an Electron or nwjs application that reads a file name from the command line, opens the file in Monaco, with actions (keybindings and/or menu items) to write the modified file, reload a different files, quit etc.  It might go so far as being able to open multiple top-level windows with one editor per window, but no sidebar, sub-windows, task bar, drag-n-drop etc (that's what VsCode is for).

I.e. a minimal but usable text editor application, that could be used as the value of the `EDITOR` environment variable (on Unix), but not so big that it would be hard to understand what it does, or to extend/modify/embed it as needed.

Perhaps something like that exists, but I haven't found it.  Perhaps the monaco-editor-samples page could also link to a page that lists projects that use Monaco.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
