### ISSUE TITLE
Add Go to last edit location

### ISSUE THREAD

**Issue by chenjie100** [microsoft/monaco-editor#2352]

**Comment by alexdima** [comment]
Press F1. Type Go To Last Edit Location. Look at keybinding.

![image](https://user-images.githubusercontent.com/5047891/108033475-587b0680-7034-11eb-9df6-e1c9d61a2d8b.png)

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
