### ISSUE TITLE
Support for RTL editing

### ISSUE THREAD

**Issue by khooz** [microsoft/monaco-editor#2371]
Hi,

Thanks for this great project.

There is 1. an issue (which I didn't create since I think this whole type of usage is not supported, yet) and 2. a feature request.
First the issue: if you set the direction on parent DOM element, which sets the children direction by inheritance, to `rtl`, the whole editor gets messed up.
Now the feature request which also may solve the problem, is to consider an option for whole layout and writing/editing to become right to left, either by an explicit configuration option or by observing the inherited attribute/style.

Cheers!

**Comment by xlmnxp** [comment]
this feature will be great to support Arabic Markdown or Arabic scripts

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
