### ISSUE TITLE
Content shift on search when scrollBeyondLastLine is disabled

### ISSUE THREAD

**Issue by silverwind** [microsoft/monaco-editor#2438]
**monaco-editor version:** 0.23.0
**Browser:** Firefox
**OS:** macOS
**Playground code that reproduces the issue:** 

```js
monaco.editor.create(document.getElementById("container"), {
    scrollBeyondLastLine: false
});
```
Hit Super+F. Editor content will shift down unexpectedly by the height of the search panel.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/115237/114927246-8eb8e480-9e31-11eb-922b-b48b0d7060c5.png">

With `scrollBeyondLastLine: true` is works as expected and no content shift is seen:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/115237/114927337-a3957800-9e31-11eb-9840-f49ae25aa73e.png">

Reproduces on https://vscode-web-test-playground.azurewebsites.net/ as well but not on native vscode.

**Comment by alexdima** [comment]
This is how the find widget works. It adds a view zone equal in height with it in order to be able to see any text that might be behind it. When using `scrollBeyondLastLine: false` and having few lines, there is no scrollbar so the content will shift. When using `scrollBeyondLastLine: true` or when using `scrollBeyondLastLine: false` and having many lines that lead to a scrollbar, the content will not shift when the view zone is added. There is currently no way to disable the insertion of the view zone by the find widget.

**Comment by alexdima** [comment]
VS Code works 100% the same:


https://user-images.githubusercontent.com/5047891/117981733-9cc92a80-b335-11eb-888a-7a0bb72e99d8.mp4

**Comment by silverwind** [comment]
You're right, I see the content shift when running VSCode with a pristine profile. For some reason, I was not able to reproduce with my configured profile, so I guess some other setting must have interfered. Given that this issue is not specific to Monaco, I'll close this.
