### ISSUE TITLE
Markdown support in defaultSnippets descriptions defined in JSON Schema 

### ISSUE THREAD

**Issue by stanislawosinski** [microsoft/monaco-editor#2440]
It would be very handy if Monaco supported Markdown descriptions in snippet definitions in JSON Schema. I was hoping to use a Markdown description to show a multi-line preview of the snippet so that the user has a chance to see the snippet before it is inserted into the document.

I tried the `markdownDescription` property along the lines of

```json
"defaultSnippets": [
  {
    "label": "Test",
    "markdownDescription": "Testing **Markdown**",
    "body": {
      "snippet": "test"
    }
  }
]
```

but it doesn't seem to be supported in `defaultSnippets`.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
