### ISSUE TITLE
Enter the icon for the assist

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2476]
I have seen that VS Code will appear some small ICONS that are customized to represent different files when it comes to import files. I want to know how to add custom icon to "registerCompletionItemProvider -- -- -- -- -- kind"

**Comment by alexdima** [comment]
I'm sorry but I also don't know because I didn't write that code. Please consider consulting the source code of the suggest feature at https://github.com/microsoft/vscode/tree/main/src/vs/editor/contrib/suggest.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community!

I'll close this issue, but if you have specific follow up questions, we'll try to help as good as we can given the limited resources that we have.

Thanks for your understanding!
