### ISSUE TITLE
[bug usability] Multiple cursors bug on phone

### ISSUE THREAD

**Issue by cmarincia** [microsoft/monaco-editor#2482]
On phone I experience the following issue, I tap to a position in the editor and sometimes the old position remains in its position
![image](https://user-images.githubusercontent.com/35623921/118413574-b6a59d00-b6a8-11eb-9951-68c635f3f050.png)
The monaco-editor embedded in the https://github.com/x1unix/go-playground . The author said it is best to open the issue here.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
