### ISSUE TITLE
Diff: random horizontal lines while scrolling

### ISSUE THREAD

**Issue by oldrich-svec** [microsoft/monaco-editor#2487]
**monaco-editor version:** 0.24.0
**Browser:** Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:**

```js
const text1 = `a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
`

var originalModel = monaco.editor.createModel(text1, "text/plain");
var modifiedModel = monaco.editor.createModel("", "text/plain");

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"));
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});
```

scroll up and down

I get random horizontal lines as shown here:

![image](https://user-images.githubusercontent.com/44394662/118811280-1a001c80-b8ad-11eb-8933-67069d96706f.png)

**Comment by alexdima** [comment]
I think this might be happening due to using a zoom factor on the browser or on the OS level. That makes that the positions for all our rectangles that are positioned at integer coordinates are multiplied with the zoom factor, and then the browser rounds the resulting float positions and it looks like they sometime round down, sometime up, thus causing overlaps or gaps. But at the DOM level, there are no gaps between the lines.

**Comment by oldrich-svec** [comment]
That is correct => I have 125% on "Scale and layout, Change the size of text, apps and other items" in Windows.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
