### ISSUE TITLE
Notebooks feature

### ISSUE THREAD

**Issue by stefnotch** [microsoft/monaco-editor#2526]
VS Code recently gained support for notebooks, which is absolutely awesome. Since monaco brings VS Code's excellent editor to the browser, it would seem that bringing notebooks to the browser could be a doable step.

This could prove to be especially useful for building web-based notebooks. Think Jupyter/Observable/Pluto.jl, but built on top of monaco.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
