### ISSUE TITLE
htmlworker

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2545]
I know you can get a tyepscriptworker like this.

export const getTypeScriptWorker: () => Promise<(...uris: Uri[]) => Promise<TypeScriptWorker>>;
 But there is no API to get an HTMLWorker. I want to know how do I get HTMLWorker

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
