### ISSUE TITLE
[Feature] Syntax highlight text should have option to applying semantic tokens

### ISSUE THREAD

**Issue by fabioz** [microsoft/monaco-editor#2566]
The following issue: https://github.com/Microsoft/monaco-editor/issues/1171

describes how to get syntax highlighting for some text, but even if semantic token highlighting is enabled, it doesn't seem possible to apply it to the code in the `monaco.editor.colorize` API, so, this is a request to be able to do that.

**Comment by hediet** [comment]
Unfortunately, we don't have the resources to address this in the forseeable future.

I doubt this can be implemented easily, but if I'm wrong I'm happy to help getting a PR by the community merged!

**Comment by fabioz** [comment]
Ok... I don't know if I'll be able to allocate time for it on my side, but if that becomes something required for me, I may end up implementing it (in which case it's possible I create a PR -- if that's the case I'll get in touch to get directions after studying a bit of the related code myself).

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
