### ISSUE TITLE
How to remove markers?

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/monaco-editor#257]
Hi, how can I remove markers?

I can add markers via: `monaco.editor.setModelMarkers(editor.editor.getModel(), 'java', monacoErrors);`

But I cannot remove them as passing an empty array or null leads to ' invalid marker service state'.

**Comment by JKillian** [comment]
Hi @tomitrescak, this is caused by a known bug, #230. It's already fixed in the core code base, the fix just hasn't been released yet.

If you want a version where this is fixed, you can just depend on my [build here](https://github.com/JKillian/monaco-editor-dist), just add something like the following to your package.json:

```
"monaco-editor": "git+https://git@github.com/jkillian/monaco-editor-dist.git",
```

**Comment by tomitrescak** [comment]
Thanks @JKillian ! Will wait for release!
