### ISSUE TITLE
Suggestions from previous model

### ISSUE THREAD

**Issue by MrRinsvind** [microsoft/monaco-editor#2577]
Reproduction steps:

- Go to playground
- Paste code below
- Run
- Right click on created editor
- Add `u` to `f` 

Autocomplete will suggest functions from previous selected models

Is it correct behaviour (if yes, how to disable it?)

**Playground code that reproduces the issue:**

```
const editor = monaco.editor.create(document.getElementById("container"), {});

const model = monaco.editor.createModel("const fu = () => {}", 'javascript', monaco.Uri.parse('file1.js'))

const model2 = monaco.editor.createModel("const fu2 = () => {}", 'javascript', monaco.Uri.parse('file2.js'))

const model3 = monaco.editor.createModel("f", 'javascript', monaco.Uri.parse('file3.js'))


editor.setModel(model)
editor.setModel(model2)
editor.setModel(model3)


```

<img width="907" alt="Снимок экрана 2021-07-15 в 19 33 46" src="https://user-images.githubusercontent.com/21083214/125824527-c7e3ff23-2d9e-479a-b8ef-f8e4ba08ccc0.png">

**Comment by spahnke** [comment]
That is expected behavior AFAIK. If your JS files don't look like modules (i.e. have neither an `import` nor an `export` statement), TypeScript will treat those definitions as global across all files/models. You can see the same behavior if you open a folder in VSCode with these files added.
![grafik](https://user-images.githubusercontent.com/25029871/125904161-1283fde8-7cf3-46da-9408-b8a51442b7ad.png)

There is no setting to force a model into "module" mode, IIRC, but there are two options to work around that: a) wrap the code of every model into a block, or b) and that's what we do in our code base for a similar use-case, switch all models that are not currently attached to the editor to "plaintext". If you attach a model to the editor switch that to "javascript", and the detached model to "plaintext". That way the definitions don't conflict with each other.

```js
monaco.editor.setModelLanguage(detachedModel, "plaintext");
monaco.editor.setModelLanguage(attachedModel, "javascript");
```

Hope that helps!

**Comment by spahnke** [comment]
Or c) if you don't need the old models anymore, you could also just dispose them without doing the language switching 😅

**Comment by hediet** [comment]
Closing as this is intentional behavior.

Disposing old models should work for you.
