### ISSUE TITLE
Support wrapping when colorizing to HTML

### ISSUE THREAD

**Issue by Mani-108** [microsoft/monaco-editor#2631]
I want the multiple monaco editor for giving expression in same page. If multiple editor instance rendered in same page that web page become over weighted. So I thought attaching to DOM was enough when focusing. Otherwise rendered only the monaco colorize element for as look like editor. Therefore I used editor colorize api for highlight code. But monaco colorize api return html not equal to actual editor content html

Colorized html:
<img width="325" alt="Screen Shot 2021-08-24 at 3 56 24 PM" src="https://user-images.githubusercontent.com/85018114/130604755-59f7247b-0bf5-435a-8bfe-8ec7439d9647.png">

Actual editor content html:
<img width="466" alt="Screen Shot 2021-08-24 at 4 27 07 PM" src="https://user-images.githubusercontent.com/85018114/130604963-afbfa2b0-fb9b-4ba5-b036-15d0d16e0add.png">

Is there any API for get exact editor content as html? Version - 0.24.0

**Comment by alexdima** [comment]
@Mani-108 Can you please provide a snippet that executes at https://microsoft.github.io/monaco-editor/playground.html and that demonstrates the problem?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
