### ISSUE TITLE
Get monaco CompletionItemProvider list

### ISSUE THREAD

**Issue by QuevedoIB** [microsoft/monaco-editor#2684]
Monaco API describes only the method to register new CompletionProviders (registerCompletionItemProvider). 

It would be nice to have a method to retrieve all the CompletionProviders, that way we could get all the providers, look for one of our interest an apply that specific Provider to a custom language. 

For example if we wanted to use default language providers of TypeScript in another language.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
