### ISSUE TITLE
Include language support for Apache Velocity

### ISSUE THREAD

**Issue by rawdog71** [microsoft/monaco-editor#2686]
I'd like to see support for the Apache Velocity template script language as syntax highlighting.

https://velocity.apache.org

Thanks guys.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
