### ISSUE TITLE
When I use diff, if the delete content is too long, there will be obvious lag

### ISSUE THREAD

**Issue by longhonour** [microsoft/monaco-editor#2693]
![image](https://user-images.githubusercontent.com/13929056/137062494-8c0a73ae-acff-47cc-9929-2437011085b8.png)

![image](https://user-images.githubusercontent.com/13929056/137060815-9497a323-aadb-48d8-a712-f316b3a1f616.png)

When renderSideBySide = false is set, if the files are all delete, the nodes will be displayed instead of the virtual list, and there will be obvious lag

**Comment by alexdima** [comment]
This is indeed a limitation of the inline diff editor. The inline diff editor does not virtualize deleted regions.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
