### ISSUE TITLE
when i use setHiddenAreas in diff editor, use addZone can't work normally

### ISSUE THREAD

**Issue by Greensleeves0906** [microsoft/monaco-editor#2707]
**monaco-editor version:** 0.24.0
**Browser:** chrome
**OS:** mac OS big sur 11.13.1
**Playground code that reproduces the issue:**

i hope addZone to modified editor can be like this:
![image](https://user-images.githubusercontent.com/26403160/138990834-1fd4d22a-0c0b-4901-890c-cecf81c551da.png)

but when i use `setHiddenAreas`,addZone to modified cause dislocation, it can't work in original editor part
 
![image](https://user-images.githubusercontent.com/26403160/138991025-94b3617e-4ea1-43ec-89dc-8c2ec750e9d7.png)

```
var originalModel = monaco.editor.createModel("This line is removed on the right.\njust some text\nabcd\nefgh\nSome more text", "text/plain");
var modifiedModel = monaco.editor.createModel("just some text\nabcz\nzzzzefgh\nSome more text\nThis line is removed on the left.", "text/plain");

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
	// You can optionally disable the resizing
	enableSplitViewResizing: false,

	// Render the diff inline
	renderSideBySide: false
});
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});

var div = document.createElement('div');
div.innerHTML = "test";

diffEditor.getModifiedEditor().setHiddenAreas([new monaco.Range(3, 1, 3, 1)]);
diffEditor.getOriginalEditor().setHiddenAreas([new monaco.Range(3, 1, 3, 1)]);

diffEditor.getModifiedEditor().changeViewZones((accessor) => {
    accessor.addZone({
        afterLineNumber: 1,
        heightInPx: 50,
        domNode: div
    });
})
```
how can i fix it ?

**Comment by mattmutt** [comment]
Following up to this request a year later, I was hoping this could get some traction as it could prove especially useful in the diff editor use case.  Imagine the ability to have a mode to completely hide unchanged lines from a diff, but preserve the actual line numbers of changed lines in the editor.

If there were an API or configuration mode to use, I'm sure such a feature would be well received since large diffs sometimes only have a few changes. As a developer, and _it depends on the kind of diff being examined_, it just makes sense to hide the unchanged lines as they serve little purpose.  However, showing _a few unchanged lines_ **before** and **after** the changes is good for context and cognitive load.

For now, using the `createDiffNavigator` to jump from one diff to the next in a large document was helpful, but getting a more scalable diff editor options would be great.

**Comment by hediet** [comment]
> I was hoping this could get some traction as it could prove especially useful in the diff editor use case. Imagine the ability to have a mode to completely hide unchanged lines from a diff, but preserve the actual line numbers of changed lines in the editor.

I think this deserves a feature request in VS Code!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
