### ISSUE TITLE
improve the typing of IEditorOverrideServices

### ISSUE THREAD

**Issue by gabor** [microsoft/monaco-editor#2710]
currently IEditorOverrideServices is only typed as 
```typescript
    export interface IEditorOverrideServices {
        [index: string]: any;
    }
```

when we need to override a service, for example, `storageService`, we need to implement this interface https://github.com/microsoft/vscode/blob/ff1e16eebb93af79fd6d7af1356c4003a120c563/src/vs/platform/storage/common/storage.ts#L37 , but there is no help from typescript. if this changes in the next version of monaco, we will only find out about it when things start to crash. considering that there is a correct type for `storageService`, it would be nice to add it to `IEditorOverrideServices`.

**Comment by alexdima** [comment]
Defining each and every service would explode the typings necessary for `monaco.d.ts` and would introduce tens of breaking changes that we would need to document each month. For this reason, it is unlikely that we will ever type each and every service.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
