### ISSUE TITLE
how to config in nuxt.config.js?

### ISSUE THREAD

**Issue by sujiangyin** [microsoft/monaco-editor#2733]
i use this plugin in nuxt project,and config in the file **nuxt.config.js** like:
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = {
 plugins: [
        { src: '~/plugins/monaco', ssr: false }
    ],
 build: {
        plugins: [
            new MonacoWebpackPlugin({
                languages: ['json'],
                features: ["coreCommands", "find"]
            })
        ]
    },
}
```
at **plugins/monaco.js** , code that:

```
const monaco = !process.client ? null : require('../components/mods/monaco').default
export default monaco
```

at **components/mods/monaco**， code that:

```
import * as monaco from 'monaco-editor'
export default monaco
```

but when run ,it still load all api in js requuest,but not on-demand loading，what is wrong in my code?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
