### ISSUE TITLE
Trying to use `export` d.ts typings with monaco

### ISSUE THREAD

**Issue by kirjs** [Microsoft/monaco-editor#276]
Hello, I am trying to use monaco in a browser. I want to add a number of existing .d.ts files (angular2 actually) to the project.

What I've tried was: 
```TypeScript
 const dog = `        
export class Dog {
  public bark(): string;
}`;
monaco.languages.typescript.typescriptDefaults.addExtraLib(dog, 'dog.d.ts');            
```
When I go to the editor, and try to `import {Dog} from 'dog';` the dog module is not found.

Using module types worked for me 
```TypeScript
const dog = `       
declare module 'dog' {
  export class Dog {
    public bark(): string;
  }
}`;
monaco.languages.typescript.typescriptDefaults.addExtraLib(dog, 'dog.d.ts');            
```
When I go to the editor, and try to `import {Dog} from 'dog';` it works. 

Thanks!

**Comment by darind** [comment]
You could prefix your typing definition key with the special `node_modules/@types` and set the `typeRoots` compiler option:

```javascript
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ES2016,
    allowNonTsExtensions: true,
    moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
    module: monaco.languages.typescript.ModuleKind.CommonJS,
    noEmit: true,
    typeRoots: [ "node_modules/@types" ]
});

monaco.languages.typescript.typescriptDefaults.addExtraLib(
    `export class Dog {
        public bark(): string;
    }`,
    "node_modules/@types/dog.d.ts");

monaco.editor.create(document.getElementById("container"), {
    model: monaco.editor.createModel(
        `import {Dog} from "dog";
console.log(new Dog().bark());`,
        "typescript",
        new monaco.Uri("main.ts")
    )
});
```

**Comment by jrieken** [comment]
Yeah, what is the issue here?

**Comment by darind** [comment]
@jrieken, actually I tried applying this approach to the @angular typing definition files but it doesn't quite work because there are also `package.json` files involved in the folders with `typings` property in it pointing to non-standard definition files (different from `index.d.ts`). So I was just wondering if this could be generalized somehow to work with any package out there. Do you know if those `package.json` files could somehow be fed into the Monaco editor when providing additional type libraries?
