### ISSUE TITLE
Inline completions: uncaught (in promise) canceled

### ISSUE THREAD

**Issue by blois** [microsoft/monaco-editor#2771]
**monaco-editor version:** 0.30.1(829382514cb1065f5ebb90f436e1c6103e153953)
**Browser:** Chrome
**OS:** OSX
**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById('container'), {
  value: "function hello() {\n\talert('Hello world!');\n}",
  language: 'javascript',
  inlineSuggest: {
      enabled: true,
  }
});
 
class InlineCompleter {
  async provideInlineCompletions() {
      await new Promise((resolve) => setTimeout(resolve, 100));
      return {items: [{insertText: 'hellooooooo!'}]};
  }
  freeInlineCompletions() {}
}
monaco.languages.registerInlineCompletionsProvider('javascript', new InlineCompleter());
```

Then type some with the completion requests getting canceled. Possibly from a missing catch at https://github.com/microsoft/vscode/blob/c775da5f0f5398de907e453796396e7f5b268e75/src/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.ts#L365?

Similar to https://github.com/microsoft/monaco-editor/issues/2612.

**Comment by pennywort** [comment]
It would be great to see some progress with this issue

**Comment by hediet** [comment]
[Fixed in latest nightly](https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0-dev.20230424#XQAAAAI3AgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0rjx0nmJTiNUtu5Yj0D5LgrNuggVQZBx0HLbfzaewGAXoaTNV6vdk_iDHP1RxBhmLpe2jhJ8_XYqy2Ov_Hrutca649khwcqxh0CQRHTVhmhw8Gv3vXY5Cwd93LwHtBzEPmsCOqaj8teVznJrKbOyYQXx7RVoscEb_TEbkRJuCG-giAmV_3y5hXP4NpM1q3YwROmpjJM4R7Id1YHEz6F-7Bz7j64O9ONWYR_naMzqgyB5UC3uZ907MN3znMR510qXaNCDluI2BBZBic4GN2Dl_vcr8V22qk8EFr_WkXq8o-nrF5lCbYGY6NHvSE6t7b4Ipmkah8ac5mheWNAtOowBtbqX4Mhp2NbRsCaWD_xYYdOnSIqghMBJftqBKYRnEUCAh-WchjhvVznujv99t6gFkzhZ6WISujsxxzr_qUk_gA).

**Comment by SuperManito** [comment]
> [Fixed in latest nightly](https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0-dev.20230424#XQAAAAI3AgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0rjx0nmJTiNUtu5Yj0D5LgrNuggVQZBx0HLbfzaewGAXoaTNV6vdk_iDHP1RxBhmLpe2jhJ8_XYqy2Ov_Hrutca649khwcqxh0CQRHTVhmhw8Gv3vXY5Cwd93LwHtBzEPmsCOqaj8teVznJrKbOyYQXx7RVoscEb_TEbkRJuCG-giAmV_3y5hXP4NpM1q3YwROmpjJM4R7Id1YHEz6F-7Bz7j64O9ONWYR_naMzqgyB5UC3uZ907MN3znMR510qXaNCDluI2BBZBic4GN2Dl_vcr8V22qk8EFr_WkXq8o-nrF5lCbYGY6NHvSE6t7b4Ipmkah8ac5mheWNAtOowBtbqX4Mhp2NbRsCaWD_xYYdOnSIqghMBJftqBKYRnEUCAh-WchjhvVznujv99t6gFkzhZ6WISujsxxzr_qUk_gA).

This bug has been present since version 0.37. This have to stay in the old version of 0.36.1. Please fix this bug. I used vite and Vue3.
