### ISSUE TITLE
monaco.d.ts vs vscode.d.ts: diff'ing the two

### ISSUE THREAD

**Issue by mbana** [Microsoft/monaco-editor#279]
I'm looking at the two files and there is a lot of similarity between the two. is there any chance of unifying them @alexandrudima , e.g.,:

a. the naming of the classes, some contain **I**, e.g., `IPosition`.
b. some interfaces in monaco are classes in vscode, e.g., `CompletionItem`.
c. naming of the fields of interfaces etc. to match.

i'm trying to get the client, https://github.com/Microsoft/vscode-languageserver-node/tree/master/client/src, to run in the browser and i am now faced with getting the types to match - vscode vs monaco.

example: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/codeConverter.ts#L32

much appreciated,

---

launch code with the two files in diff mode:

```sh
~/dev/vscode $ ( \
  echo "monaco.d.ts" "vscode.d.ts" \
    | xargs -n1 -I {}  find `pwd` -name {} -print0 -quit \
    | xargs -0 -n2 code --diff \
)
```

**Comment by alexandrudima** [comment]
@mbana 

`vscode.d.ts` represents a **designed** API for vscode extensions. It is kept stable at all cost through an API implementation layer that eventually converts everything into types and concepts that are actually implemented in the `src` folder. It also talks about a lot of things that are IDE specific (e.g. file watching, opened folder, status bar, message boxes, etc.)

`monaco.d.ts` represents a **generated** API from the actual editor implementation. It contains only concepts regarding what a single editor would be able to do and reflects truthfully the underlying implementation (i.e. no API layer).

The APIs have different goals and are inherently solving different problems, a product API vs a widget API, etc.

There is no plan to make them fully aligned, the reason being that `monaco.d.ts` is free to change due to implementation changes (e.g. improvements in tokenization, improvements in rendering decorations, etc.), meanwhile `vscode.d.ts` is not.
