### ISSUE TITLE
Can't select text when editor is hosted inside Fluent Panel/Callout

### ISSUE THREAD

**Issue by dehoward** [microsoft/monaco-editor#2799]
[Sandbox](https://codesandbox.io/s/nostalgic-kilby-e4i64?file=/src/App.js)

When the `MonacoEditor` is hosted inside a [Panel](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel) or [Callout](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout), selecting text with the mouse does not work.
This seems to be a regression as this functionality previously worked.

Possibly related to #2503.

**Comment by alexdima** [comment]
@dehoward Not sure what's wrong, but the root cause is that `mousemove` events are not reaching the `document` on that page. My best guess is that some script (not the editor) is intercepting all those events and calling `e.stopPropagation()`.

In your test page, you can open `editor.main.js` and pretty-print it. You can then search for the `startMonitoring` function. That is the function that is called when we begin monitoring the page for mouse move (e.g. for dragging the selection or the scrollbars):

On line 13902 there is a listener for `mousemove` installed on `document`. The breakpoint on line 13903 never fires, which indicates that the `mousemove` event does not reach the `document`. Can you please validate my findings?

![image](https://user-images.githubusercontent.com/5047891/144326470-38411cde-e8be-4baa-962c-8850e60b2864.png)

**Comment by dehoward** [comment]
@alexdima yup, I see this as well - so I'm guessing this issue was introduced by the Fluent team then since without the wrappers the selection/scrollbars are just fine.
