### ISSUE TITLE
[Bug] How to prevent default functionality of paste event in monaco editor

### ISSUE THREAD

**Issue by Aayush04** [microsoft/monaco-editor#2848]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- Reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// javascript code
var jsCode = [
    '"use strict";',
    'function Person(age) {',
    '   if (age) {',
    '       this.age = age;',
    '   }',
    '}',
    'Person.prototype.getAge = function () {',
    '   return this.age;',
    '};'
].join('\n');

var editor = monaco.editor.create(document.getElementById('container'), {
    value: jsCode,
    language: 'javascript'
});

// One way to handle event. 
editor.getContainerDomNode().addEventListener('paste', (event) => {
    console.log("paste handle in monaco editor contianer");
    event.preventDefault();
});

// Another way to handle event. Uncomment below lines to run
// let textarea = editor.getContainerDomNode().querySelectorAll("textarea.inputarea.monaco-mouse-cursor-text")[0];
// textarea.addEventListener('paste', (event) => {
//     console.log("paste handle in monaco textarea");
//     event.preventDefault();
// });

// Testing the behavior independent of monaco editor
var input = document.getElementById("textarea");
input.addEventListener('paste', (event) => {
    console.log("paste handle in sample input");
    event.preventDefault();
});
```

// Html code
```
<div id="parent1">
     <textarea id="textarea"></textarea>
</div>

<div id="container" style="height: 100%"></div>
```

### Actual Behavior

When we click on browser menu
Edit -> Paste

Copied text get pasted into the editor.

### Expected Behavior

When we click on browser menu
Edit -> Paste

It should not paste any text inside the editor. If we have prevented the functionality using 
`event.preventDefault()`

### Additional Context

How can I prevent default functionality for paste event **(when trigger from browser menu option Edit->Paste)** for monaco editor? I am handling paste event in the following way:

```    
    editor.getContainerDomNode().addEventListener('paste', (event) => {
        event.preventDefault();
        event.stopPropagation();
    }
```

I also tried to handle the paste event on the textarea which is the source element in event propagation. 
```    let textarea = editor.getContainerDomNode().querySelectorAll("textarea.inputarea.monaco-mouse-cursor-text")[0];
    textarea.addEventListener('paste', (event) => {
        event.preventDefault();
        event.stopPropagation();
    });
```
But here also seems like preventDefault is not working. It is pasting into editor whatever the text is copied.

Also , same thing is working fine when I add paste event handler on a simple textarea independent of monaco editor
`<textarea id="textarea"></textarea>
`

Bascially I want to disable paste action when triggered from **browser Edit menu.** Need to know how this can be achieve in monaco-editor. Am I doing anything wrong here or it is a bug of monaco editor?

**Comment by alexdima** [comment]
@Aayush04 Have you tried adding a capturing event listener to the editor's container which prevents default and stops propagation?

**Comment by Aayush04** [comment]
@alexdima Thank you. Yes, by capturing the event in the editor's container  and I am able to disable paste.

```
    editor.getContainerDomNode().addEventListener('paste', (event) => {
        console.log("paste handle in monaco editor contianer");
        event.preventDefault();
        event.stopPropagation();
    }, true);   

```
But I also wonder, to achieve this why I need to do both i.e. prevent default and stop propagation ?
and Secondly why this is not working when not capturing ?

**Comment by alexdima** [comment]
> But I also wonder, to achieve this why I need to do both i.e. prevent default and stop propagation ?
and Secondly why this is not working when not capturing ?

`e.preventDefault()` typically means you would like to prevent the default action that the browser would have taken. We don't check all incoming events for `e.defaultPrevented` before handling them. So `e.preventDefault()` doesn't have any consequence for our code.

Regarding capturing and `stopPropagation()`, these are the fundamental mechanisms through which the DOM dispatches an event. From memory, I remember that dispatching an event has three phases: capturing, at target, and bubbling. In the capturing phase the event is dispatched from `document > body > ... ` through all dom hierarchy towards the target. In the target phase the event is at the target. In the bubbling phase the event is dispatched `... > body > document` through all dom hierarchy towards the document. We listen for the event at the target. In order to prevent it from reaching us, you need to install a capturing listener and then stop its propagation. I suggest to read more about this at MDN, I'm writing all of this just from memory.
