### ISSUE TITLE
[Feature Request] Laravel blade syntax support

### ISSUE THREAD

**Issue by Yendric** [microsoft/monaco-editor#2858]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Laravel Blade is a templating engine that is used in the hugely popular PHP framework Laravel. It has it's own syntax, which is currently missing from the monaco-editor package.
Although there is a [VSCode plugin for Blade syntax support ](https://marketplace.visualstudio.com/items?itemName=amirmarmul.laravel-blade-vscode), it uses a [tmLanguage format](https://github.com/amirmarmul/laravel-blade-vscode/blob/master/src/syntaxes/blade.tmLanguage.json) which isn't easily usable (it will *work* by following [this guide](https://github.com/bolinfest/monaco-tm), but not very well and it's a hassle to set up).
That's why I am requesting Laravel Blade syntax support to be built-in into the monaco-editor package.

Thanks in advance.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
