### ISSUE TITLE
[Bug] Add comment command not working with custom language

### ISSUE THREAD

**Issue by EnricaEnrica** [microsoft/monaco-editor#2869]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
https://microsoft.github.io/monaco-editor/monarch.html
```

### Actual Behavior

If I click on "Add line comment" nothing happens (this only happens with custom languages). 

### Expected Behavior

If I click on "Add line comment" the selected line will be commented

**Comment by spahnke** [comment]
That's because the Monarch definition is only concerned about the colorization not the behavior of the language. To enable the comment commands you need to provide a language configuration in addition to the Monarch tokenizer. The "add line comment" command for instance doesn't work in this playground example out of the box: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

But if you add the following code the command works as expected. Same goes for other settings like bracket pairs, etc. See also https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#setLanguageConfiguration and https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.LanguageConfiguration.html.
```js
monaco.languages.setLanguageConfiguration('mySpecialLanguage', {
    comments: {
        lineComment: '//',
        blockComment: ['/*', '*/']
    }
});
```

**Comment by EnricaEnrica** [comment]
This solved the problem, thank you.
