### ISSUE TITLE
Undo action is wrongly changing the editor decorations ranges

### ISSUE THREAD

**Issue by ManojkumarV** [microsoft/monaco-editor#2933]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById('container'), {
	value: jsCode,
	language: 'javascript'
});

var decorations = editor.deltaDecorations(
	[],
	[
		{
			range: new monaco.Range(3, 1, 5, 1),
			options: {
				isWholeLine: true,
				linesDecorationsClassName: 'myLineDecoration'
			}
		},
		{
			range: new monaco.Range(7, 1, 7, 24),
			options: { inlineClassName: 'myInlineDecoration' }
		}
	]
);
```

### Actual Behavior

When the surrounding range of decoration ranges are removed and undo action is triggered the decorations are applied to the complete range of text which are added by undo action. 
For example if a decoration is applied to line number 10, lines 7 to 15 are removed and undo action is triggered then the decoration is applied for lines 7 to 15. 

### Expected Behavior

The undo action should only bring back the actual decoration range before undo.

**Comment by hediet** [comment]
Related: #2784

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
