### ISSUE TITLE
[Feature Request] Ability to center align expressions

### ISSUE THREAD

**Issue by tijmendaa** [microsoft/monaco-editor#3043]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

We're using monaco editor to display expressions in our decision table editor which looks like this:
![image](https://user-images.githubusercontent.com/99200020/160372534-e5b6170a-8c1f-427c-88d7-c63ee4237187.png)
In order to improve the readability of these tables, We'd like to be able to center the expressions in certain cells, which would look like this:
![image](https://user-images.githubusercontent.com/99200020/160373437-cf599554-7f0d-4421-99e0-dc1133ef7655.png)
We didn't find a way to achieve this yet. Such a feature would be highly appreciated.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
