### ISSUE TITLE
[Feature Request] Way to see only differences without unmodified changes in monaco code diff component

### ISSUE THREAD

**Issue by harshadsindhav** [microsoft/monaco-editor#3062]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Monaco code difference editor is a great editor, but to make it even greater I think following feature could help.
Sometime user may want to see only changes which are modified and skip the unmodified changes from the diff view when there is large content in file.

It will help us in meeting much needed product functionality if support is provided.

Please see the attached screenshot to understand more.

![monaco code diff editor](https://user-images.githubusercontent.com/13543626/162130663-bf9f6fa0-a2b4-4390-ae6b-bc9dbf29cbc9.jpg)

**Comment by ricenoddle** [comment]
I think you mean a diff mode like in github code review ?

**Comment by kazuki-hanai** [comment]
I want this feature too.

**Comment by rawbin-** [comment]
need too

**Comment by hediet** [comment]
Related: https://github.com/microsoft/monaco-editor/issues/2707

This is out of scope for just the monaco editor, but please create a detailed feature request for VS Code.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
