### ISSUE TITLE
Setting the full model range as editable breaks completions

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#312]
To reproduce:
1. go to https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults
2. add `editor.getModel().setEditableRange(editor.getModel().getEditableRange());` as the last line
3. run
4. add a new empty line at the beginning of the document
5. apply a completion at the beginning of the document

Only the part after the inserted text is editable when the whole document should be editable.

**Comment by alexandrudima** [comment]
The model editable range uses two markers for tracking.

The root cause is that applying a suggestion sends an edit with `forceMoveMarkers: true`. That causes all markers sitting at that position to move, including the editable range start marker. I recommend listening to model content change events, reading the editable range and if it has moved unexpectedly, to adjust accordingly (i.e. recompute it on your side).

![image](https://cloud.githubusercontent.com/assets/5047891/21923765/3621d8c4-d976-11e6-997c-df14aa02b0d0.png)
