### ISSUE TITLE
[Feature Request] Completion for SQL

### ISSUE THREAD

**Issue by vanillajonathan** [microsoft/monaco-editor#3132]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I would like that when I press <kbd>Ctrl</kbd>+<kbd>Space</kbd> when using the "sql" language mode that I get presented with a completion popup.

https://microsoft.github.io/monaco-editor/
Change language to "sql", press <kbd>Ctrl</kbd>+<kbd>Space</kbd>, and it says "No suggestions".

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
