### ISSUE TITLE
[Bug] typescript worker errors when using `customWorkerPath` in module workers

### ISSUE THREAD

**Issue by okikio** [microsoft/monaco-editor#3151]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

The typescript worker crashes when using `customWorkerPath`

```ts
monaco.languages.typescript.typescriptDefaults.setWorkerOptions({
  customWorkerPath: "/ts-worker-factory.js"
});
```
due to `importScript` not being allowed in module workers. A possible solution would be to use the `TypescriptWorker` class to manually extend the typescript language worker, but as monaco doesn't export `TypescriptWorker` there is nothing I can do.

Right now monaco only exports the `create` method from the [...esm/vs/language/typescript/ts.worker.js](https://unpkg.com/browse/monaco-editor@0.33.0/esm/vs/language/typescript/ts.worker.js), which supports `customWorkerPath` via `importScripts`. 

The problem is that for module workers `importScripts` isn't supported, so all you get is an error if you try to use `customWorkerPath` in module workers.

### Expected Behavior

To solve this issue, monaco should export the `TypescriptWorker` class (together with any necessary dependencies) so it can easily be extended by the user, while avoiding the need to call `importScripts` in a module workers.

The source code for [langauage/tsWorker.ts](https://github.com/microsoft/monaco-editor/blob/main/src/language/typescript/tsWorker.ts) shows that the expected behavior is an export, all that would be required would be for the [languages/typescript/ts.worker.ts](https://github.com/microsoft/monaco-editor/blob/main/src/language/typescript/ts.worker.ts) file to add 

```ts
export * from "./tsWorker";
``` 

to the source code.

### Additional Context

This is a problem that affects all the language workers for monaco, it would be best to add exports for all the supported languages in monaco, so extending the source is much easier.

**Comment by okikio** [comment]
I have created a pr that fixes this issue #3152

**Comment by hediet** [comment]
To be honest, I don't fully understand the current worker implementation we have, but I have the feeling it is quite messy.
But I also think that this issue is not about the real problem (which I also don't fully understand), but already about a problem in some solution for the real problem.

Because this issue is already a year old and does not seem to get a lot of interest by the community, I'm going to close this issue, but encourage to create a new issue that describes your goal (e.g. I guess you want to customize typescript behavior without implementing your own typescript mode from scratch? And you want to use ES modules in your customization?).

**Comment by hediet** [comment]
Actually, thinking about the issue I think #4035 is a decent fix.
