### ISSUE TITLE
[Feature Request] Minimum compatibility browser version

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#3156]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Hi, I request the monaco editor team, to reconsider the idea of providing a list of compatible browser versions for monaco editor in the documentation. Previously, when I created an issue regarding this @alexdima replied, `Defining a version matrix is not really possible` https://github.com/microsoft/monaco-editor/issues/2423#issuecomment-839167317

For us, It will not be possible to ask our users to upgrade to the latest browser version every-time a new feature is released in monaco editor _( to be sure that nothing breaks due to browser incompatibility )_. It will be better, if we have a table indicating the minimum browser version limit in which the monaco editor works properly, in the documentation.

Alternatively, a relative browser version compatibility will also be a better idea. Like **monaco editor supports a `x` number of browser versions before the latest browser version**. By this we get a timeframe within which we can ask our users to upgrade to the latest browser versions.

So, kindly provide a list of compatible browser versions in docs

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
