### ISSUE TITLE
[Bug] Syntax error in editor.main.js on Safari 13.1.1

### ISSUE THREAD

**Issue by hillin** [microsoft/monaco-editor#3161]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
Just open monaco editor playground!
```

### Actual Behavior

Shows nothing, the Javascript console says:

> SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.
> [f] (anonymous function) - editor.main.js:756

### Expected Behavior

Opens the playground page correctly.

### Additional Context

Safari (macos) version: 13.1.1 (15609.2.9.1.2)

**Comment by hillin** [comment]
Thanks @hediet , I understand that version is old enough to drop support, but a few clients of ours is still using it and they are somewhat stuck on that version. Is there a place I can find the last version of monaco that supports Safari 13?

**Comment by caracal7** [comment]
The same issue with Safari 13.1.2

**Comment by caracal7** [comment]
@hillin @hediet

0.30.1, 0.31.0 Monaco-editor working well in Safari 13.1.2

0.32 and higher is not working

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
