### ISSUE TITLE
[Feature Request] suggestion item could be wrap line

### ISSUE THREAD

**Issue by xaios** [microsoft/monaco-editor#3176]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

![image](https://user-images.githubusercontent.com/23434033/177297304-c2ae90f1-2f3b-4d7e-a11a-9b24dfc6fd15.png)

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
