### ISSUE TITLE
[Feature Request] 3-way merge editor

### ISSUE THREAD

**Issue by AndersMad** [microsoft/monaco-editor#3268]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Will the 3-way merge editor (https://github.com/microsoft/vscode/labels/merge-editor) be availble as a part of monaco/web editor? 

Will it contain diffing from 3 sources? (or is it only visuals/merging based on a diffing tool)

Also a minor issue - the "Tags" section of the releases is no longer updated - but there are new versions available @ npm : https://github.com/microsoft/monaco-editor/tags

**Comment by hediet** [comment]
It would take significant effort to pull this off, as the 3 way merge editor uses many components that are currently not bundled with the monaco-editor.
It is not impossible, but we would rather use that engineering time to improve the merge editor in VS Code.

---

We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Comment by AndersMad** [comment]
@hediet thanks for the answer! I know I am going off "monaco code" topic here, but will it be a part of https://vscode.dev/ then? cause an alternative would then be to call that site with 3 urls (or a proj.) pointing to 3 e.g. WebDAV files

for others FYI reading this: the only alternative seems (still to be) https://codemirror.net/5/demo/merge.html and thats in v5 only - that is now legacy.
