### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by luonmincuoi872** [microsoft/monaco-editor#3278]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Some language such as java, hcl ... not have format document option in context menu when click right mouse.
Bellow code is also not work
`editor.getAction("editor.action.formatDocument").run().then(r => console.log('formatDocument'));`

Please support format document feature for java, hcl ... like other languages
Thanks!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
