### ISSUE TITLE
[Feature Request] Expose semantic tokens API

### ISSUE THREAD

**Issue by AXeL-dev** [microsoft/monaco-editor#3291]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Hello,

I'm trying to get the semantic tokens &/or modifiers of the current loaded model, but i didn't find any exposed API to do so, i was forced to use something like the following on typescript to get the semantic tokens of a specific line:
```typescript
const model = editor.getModel();
const tokens = (model as any)._tokenization._textModel._semanticTokens._pieces[0].getLineTokens(4);
```
Is there any way to make an exposed method, for example: `getSemanticTokens` on the model class which will return the semantic tokens for the current model?

Thanks!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
