### ISSUE TITLE
Multi-part IME compositions reset cursor in Edge

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/monaco-editor#339]
Testing https://github.com/Microsoft/vscode/issues/19061

monaco-editor npm version: https://github.com/Microsoft/monaco-editor/commit/d38a5e5bb798c34d39be111522a554608443bb29
Browser: Edge 38.14393.0.0
OS: Windows 10

Related to https://github.com/Microsoft/monaco-editor/issues/320 but the "collapsing" happens when you switch some characters to kanji and start a new string with the Microsoft Japanese IME.

Turn on IME, type "watashi" (わたし):

![image](https://cloud.githubusercontent.com/assets/2193314/22262616/8095a7a6-e226-11e6-8b65-92ff53dd8044.png)

Press space to confirm 私:

![image](https://cloud.githubusercontent.com/assets/2193314/22262650/9d393706-e226-11e6-9090-702d054402bb.png)

Type "ha" (は), it incorrectly overrides 私:

![image](https://cloud.githubusercontent.com/assets/2193314/22262688/bbddcf14-e226-11e6-8996-62ca31a468d6.png)

Pressing enter to confirm the composition results in the correct string:

![image](https://cloud.githubusercontent.com/assets/2193314/22262721/db67b444-e226-11e6-84a4-c430d5e2c5df.png)

---

This is vscode's behavior:

![image](https://cloud.githubusercontent.com/assets/2193314/22262746/f71de492-e226-11e6-8c13-f2a100cda6a1.png)

**Comment by rebornix** [comment]
IE and Edge are doing differently from Chrome(not v55, v56)/Safari/Firefox about composition update:

In Chrome/Safari/Firefox, type `watashi` first, you can get composition update of `わたし` and then if you press `ha`, and you'll get composition update of `わたしは ` if you don't press enter to confirm  `わたし`.

However in Edge/IE, type `watashi` first, you can get composition update of `わたし` and then if you press `ha`, and you'll get composition update of は `  **even if** you don't press enter to confirm  `わたし`.

Here again we have to rely on textarea to get the correct composition input. The fix is clean however it's making our composition logic really complex.

**Comment by weinand** [comment]
This now works in VSC 1.12.0 on Windows 10 in Edge browser.

**Comment by bpasero** [comment]
Also seems to be working in Windows 10 VSC standalone.
