### ISSUE TITLE
Expose precondition in actions API (action keybindingContext not respected in context menu)

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/monaco-editor#340]
monaco-editor npm version: 0.7.0+, 0.8.0
Browser: Chrome
OS: Mac

An action's keybindingContext isn't respected when populating the context menu. When the context key doesn't apply, it would be great if the context menu didn't show the action. 

In the following case, the save action (Ctrl + S) only works when the editor is not in read only mode.
```
       this.editor.addAction({
                id: "save",
                label: "Save",
                keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_S],
                keybindingContext: "!editorReadonly",
                contextMenuGroupId: "0_navigation",
                contextMenuOrder: 0.2,
                run: () => Promise.resolve(this.parent.save())
            });
```

I've verified that the keybindingContext is working, and that the action doesn't run when its in read only mode. However, it still shows in the context menu regardless: 

<img width="279" alt="screen shot 2017-01-24 at 9 49 48 pm" src="https://cloud.githubusercontent.com/assets/16690124/22279337/0f67e16c-e27f-11e6-99e7-e7273c7b54da.png">

**Comment by alexandrudima** [comment]
Internally we have two concepts:
* precondition
* keybindingContext

An action is triggerable from the keyboard when both precondition & keybindingContext are true.
An action is shown in the context menu when precondition is true

**Comment by microsoftsam** [comment]
Okay cool. Precondition isn't surfaced in the d.ts which is okay, but are you saying that if I set the precondition of an action that it should work? Or is it much more intricate?

**Comment by alexandrudima** [comment]
We need to expose more of the internal API (namely the precondition). A precondition is something that must hold true for the action to make sense. e.g. "!editorReadOnly" would be a precondition for an action that needs to make edits. That in itself is not sufficient because multiple actions can be bound to the same keybinding, and in order to disambiguate there exists the `keybindingContext`. Today, in our monaco.d.ts API we only expose `keybindingContext` and we should expose both.
