### ISSUE TITLE
[Feature Request] Add addAction to Original text in Diff editor

### ISSUE THREAD

**Issue by ZiTAL** [microsoft/monaco-editor#3411]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

When I create a action in diff editor only adds to modified one, it will be fine to add to both or choose where to add:
```
		editor.addAction(
		{
			// An unique identifier of the contributed action.
			id: 'itzuli',
		
			// A label of the action that will be presented to the user.
			label: 'Itzuli',
		
			// An optional array of keybindings for the action.
			keybindings:
			[
				monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter
			],
		
			// A precondition for this action.
			precondition: null,
		
			// A rule to evaluate on top of the precondition in order to dispatch the keybindings.
			keybindingContext: null,
		
			contextMenuGroupId: 'navigation',
		
			contextMenuOrder: 1.5,
		
			// Method that will be executed when the action is triggered.
			// @param editor The editor instance is passed in as a convenience
			run: function (ed)
			{
				alert("i'm running => " + ed.getPosition());
			}
		})
```

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
