### ISSUE TITLE
extension support for the monaco-editor

### ISSUE THREAD

**Issue by Xsmael** [microsoft/monaco-editor#343]
It will be very nice that we could make extensions for the monaco-editor, as for VS code
thanks!

**Comment by Danieladu** [comment]
Is this work on the agenda?

**Comment by gonzojive** [comment]
I would like to hear more about this as well.

There is a note in the README of the project:

> Note: If the extension is fully based on the [LSP](https://microsoft.github.io/language-server-protocol/) and if the language server is authored in JavaScript, then it would be possible.

What does this mean? Is there a guide to making some extensions work?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
