### ISSUE TITLE
[Feature Request] ship *.d.ts for every file inside esm version

### ISSUE THREAD

**Issue by troy351** [microsoft/monaco-editor#3434]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Shipped `monaco-editor` and `monaco-editor-core` has no type definition file inside `esm/vs/**/*`, adding it will makes customize `monaco-editor` easier when trying to using some internal apis via `TypeScript` :)

**Comment by hediet** [comment]
We try to limit API surface as much as possible, as we want to be free to refactor internals without thinking about breaking users of the monaco editor.

---

We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
