### ISSUE TITLE
Can you Hook Into Callbacks for When a User Folds Text?

### ISSUE THREAD

**Issue by k-simons** [microsoft/monaco-editor#347]
monaco-editor npm version: 0.8.1
Browser: Chrome 55
OS: Linux

Is there anyway to hook into callbacks when the user folds text in the monaco editor? For example, if they folded together lines 3 to 9 is there a callback I could register that (ideally) returns information about what lines were folded? Nothing jumped out in the API. If not then this would turn into a FR :)

**Comment by alexandrudima** [comment]
Folding is not exposed in the API at this time.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
