### ISSUE TITLE
is there any way to get AST of editor code. if not please add it.It will be very useful

### ISSUE THREAD

**Issue by SabariRavikumar** [microsoft/monaco-editor#3485]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I am passing my sdk code as extra library.i need to get AST of code on editor so that i will use it to vaidate with my code. i didn't get any method to get AST.if any method is available please let me know

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
