### ISSUE TITLE
Less formatting and includes

### ISSUE THREAD

**Issue by jws305** [microsoft/monaco-editor#359]
Is there anyway to format less files?  I have formatting working with HTML and Typescript files.

Is there any way to get the intellisense working with variables defined inside a less import similar to how you can add extra libs with Typescript.

**Comment by aeschli** [comment]
For VSCode there are extensions that format LESS. For Monaco there is not and is also not planned.
Inetllisense across files for LESS: Again there is an extensions for VSCode (Less Intellisense), nothing planned for Monaco.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
