### ISSUE TITLE
Custom Parser/Lexer

### ISSUE THREAD

**Issue by JoshClose** [Microsoft/monaco-editor#361]
I need language support (highlight and intellisense) for SQLite. The only grammar I have found is in ANTLR 4. https://github.com/antlr/grammars-v4/blob/master/sqlite/SQLite.g4

How would I go about integrating a custom parser/lexer into monaco? ANTLR can apparently build into a JavaScript parser/lexer that I can use. https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md

Looking at the given grammar, would it be easy to just convert to Monarch instead? Looks like it's in EBNF.

**Comment by alexandrudima** [comment]
The editor supports two types of colorizers:

a) a Monarch based one (via [`setMonarchTokensProvider`](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#setmonarchtokensprovider) which then needs to be written with the Monarch rules in mind.

b) a custom one (via [`setTokensProvider`](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#settokensprovider). The custom one must adhere to the [`TokensProvider`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.tokensprovider.html) interface:

```
	/**
	 * A "manual" provider of tokens.
	 */
	export interface TokensProvider {
		/**
		 * The initial state of a language. Will be the state passed in to tokenize the first line.
		 */
		getInitialState(): IState;
		/**
		 * Tokenize a line given the state at the beginning of the line.
		 */
		tokenize(line: string, state: IState): ILineTokens;
	}

	/**
	 * The result of a line tokenization.
	 */
	export interface ILineTokens {
		/**
		 * The list of tokens on the line.
		 */
		tokens: IToken[];
		/**
		 * The tokenization end state.
		 * A pointer will be held to this and the object should not be modified by the tokenizer after the pointer is returned.
		 */
		endState: IState;
	}
	/**
	 * A token.
	 */
	export interface IToken {
		startIndex: number;
		scopes: string;
	}
```

The contract of a custom tokenization provider is that it will execute line-by-line in a single top-bottom pass. I don't think all grammars fit these requirements (i.e. the look ahead is limited to the current line being tokenized). For JS/TS we use a custom tokenizer which uses the TypeScript lexer (but not the full grammar). The reason is that in the editors land we would like to have a very fast colorizer that will change tokens in a strict, but perf-friendly way. e.g. editing a line will result in that line and possibly all the ones after it being retokenized, but never in the lines above being retokenized.

We will at one point add the option to have semantic highlighting, but we don't have that at this time.

**Comment by JoshClose** [comment]
Thanks Alexandru! I asked more specific questions in the microsoft/vscode project and you've been working me there. I'll keep any subsequent questions on that thread. Thanks again for the help!

**Comment by jeanbenitez** [comment]
For future references, this is "that" issue 😄 
https://github.com/microsoft/vscode/issues/25472
