### ISSUE TITLE
how to change the display languge

### ISSUE THREAD

**Issue by Leezheng357** [Microsoft/monaco-editor#375]
i need to change the display language, don`t know how to do?

**Comment by mattgodbolt** [comment]
If you're referring to the language the syntax highlight uses, then I think
```javascript
editor.updateOptions({
  language: "cpp"  // or whatever language you need here, javascript, or go or whatever
});
```
should do the trick.

**Comment by Leezheng357** [comment]
`{ 'vs/nls': { availableLanguages: { '*': 'zh-cn' } } }`

**Comment by Lewiskong** [comment]
it doesn't work when i use 
```
editor.updateOptions({
  language: "cpp"  // or whatever language you need here, javascript, or go or whatever
});
```
with `editor.updateOptions` , i can only change theme ,but the language change doesn't work

**Comment by akosyakov** [comment]
You should change a language on a model: `monaco.editor.setModelLanguage(editor.getModel(), "cpp")`

**Comment by SoftTimur** [comment]
Are you sure `monaco.editor.setModelLanguage(editor.getModel(), "cpp")` works? I have got an error `TypeError: monacoeditor.setModelLanguage is not a function` in [this code](https://jsbin.com/pogolazule/3/edit?html,output).

In my code `monacoeditor` seems to be `ICommonCodeEditor`, I also tried `monacoeditor.getModel().updateOptions({ "language": newValues[key] })`, it did not raise any error, but it just did nothing.

Note that it is not the problem of the directive, because it works well to change `lineNumbers`.

Could anyone help?

**Comment by datummm** [comment]
@SoftTimur I believe `monaco.editor.setModelLanguage(editor.getModel(), "cpp")` should work as written (note that it is `monaco.editor` and not `monacoeditor`) as long as the `editor` of `editor.getModel()` is an editor instance created by monaco.editor.create();

It's confusing because `setModelLanguage` is a function in the `monaco.editor` *module*, and not a method of any particular monaco editor/model *instance*, as some (myself included) would expect.

**Comment by SGissubel** [comment]
I have tried `window.monaco.editor.setModelLanguage(editor.getModel(), "cpp")` and `window.monaco.editor.setModelLanguage(window.monaco.editor.getModel(), "cpp")`
The latter is half way there I think?  But i get "Cannot read property 'toString' of undefined" when I try to use this (which is stemming from the getModel method).... 

I have been at this for hours. (Using Angular 5). Can anyone be of assistance?

**Comment by SGissubel** [comment]
Welp... hackin my way through.... 

`window.monaco.editor.setModelLanguage(window.monaco.editor.getModels()[0], 'typescript')
`

**Comment by rcjsuen** [comment]
@SGissubel The `getModel(URI)` function takes a `URI` parameter.

https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#getmodel

You can't just call `window.monaco.editor.setModelLanguage(editor.getModel(), "cpp")` as you're not satisfying fulfilling the function's parameter requirements. You need to give it something so that Monaco knows which model to give you.

**Comment by SGissubel** [comment]
Umm.. Nope? But thank you! Like I said previously, that was not working for me.  Editor was coming up undefined.  I went through the docs for hours.

As mentioned though....
`window.monaco.editor.setModelLanguage(window.monaco.editor.getModels()[0], 'typescript')
`
this works! So, all good!

**Comment by SGissubel** [comment]
@rcjsuen Absolutely... the documents are a maze of mine-fields and dead ends.  As I said, I combed those documents thoroughly for most of the day.  URI is still a bit ambiguous to me, how it's recieved, what it is... So for now, the getModels()[0] works for me and does the job.

**Comment by rcjsuen** [comment]
Here is some code that you can try in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html). If you click on the button you can toggle between JavaScript syntax highlighting and HTML syntax highlighting. Good luck with your project!

**JavaScript:**
```JavaScript
const value = `function test() {
}
<button onclick="change()">Click</button>
<div id="container" style="height:90%;"></div>`;

const model = monaco.editor.createModel(value, "javascript");
monaco.editor.create(document.getElementById("container"), {
	model: model
});

var js = true;

function change() {
    js = !js;
    var language = js ? "javascript" : "html";
    monaco.editor.setModelLanguage(monaco.editor.getModel(model.uri), language);
}
```
**HTML:**
```HTML
<button onclick="change()">toggle language</button>
<div id="container" style="height:90%;"></div>
```

**Comment by krikz** [comment]
> i have solved the issue:
> `(<any>window).require.config({ 'vs/nls': { availableLanguages: { '*': 'zh-cn' } } });`

Where you are put this code? I trying in monacoConfig.onMonacoLoad but it doesn't work :(

**Comment by Symbolk** [comment]
Anyone knows how to change the language according to code file extension or first line like "#!/usr/bin/env python"?
