### ISSUE TITLE
Add flag to not merge adjacent tokens of same type

### ISSUE THREAD

**Issue by MakullaMa** [microsoft/monaco-editor#378]
Hello,

I have a custom language which is defined in the following way:

```javascript
monaco.languages.register({ id: "custom" });

monaco.languages.setMonarchTokensProvider("custom", {
  tokenizer: {
    root: [
      [/\[(b|i)\]/, { token: "keyword.$0" }]
    ]}
});

// five tokens, all is fine
var tokens = monaco.editor.tokenize("[b][i]test[i][b]", "custom")[0];

// why do I get three tokens instead of five...?
tokens = monaco.editor.tokenize("[b][b]test[b][b]", "custom")[0];
```
In the first case I get five tokens from the tokenizer (all adjacent tokens have different types). In the second case I only get three tokens. Seemingly the tokenizer merges adjacent tokens of identical types. I would like to treat all `[b]`'s as individual tokens. Is there a way to achieve this?

monaco-editor npm version: 0.8.1
Browser: All
OS: Win10

**Comment by alexandrudima** [comment]
This is where the Monarch tokenizer merges adjacent equal tokens:

https://github.com/Microsoft/vscode/blob/2af6c114c3a48fd06e86683260483780727ffd0b/src/vs/editor/common/modes/monarch/monarchLexer.ts#L258

We could look into adding a flag that adjacent equal tokens do not get merged.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

---

Having said that, we would be open for community contributions though. In case you provide a PR, please open a new issue first and reference this issue.
