### ISSUE TITLE
Partial CompletionItems?

### ISSUE THREAD

**Issue by JacobEvelyn** [Microsoft/monaco-editor#379]
Hi there! I'm wondering if there's a way to modify the `CompletionItemProvider` behavior so that `provideCompletionItems` doesn't have to provide the complete list of items (even using `resolveCompletionItem` it appears that the entire list needs to be provided on the first character of the word). I'm concerned about having to provide an enormous list of possible `CompletionItem`s for cases like the Monaco Playground example in which the completion item could be any `npm` package.

**Comment by alexandrudima** [comment]
I think there is a specific flag you can set in your result (if you return a [`CompletionList`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionlist.html)) where you can set the flag `isIncomplete` to true and fill up the `items` with the ones you have matching so far. 

This will result in the subsequent typing in the editor to call `provideCompletionItems` again on each additional typed letter, rather than filtering locally.

**Comment by leolorenzoluis** [comment]
@alexandrudima I may be missing here, but does that mean the flag using `resolveCompletionItem` with `isIncomplete` property on the `items` should somehow resolve issues when having a extremely large completion list? Right now I've tested that it doesn't show any completion at all if the items are at 100k.

**Comment by alexandrudima** [comment]
@jrieken might have further insights.

AFAIK if you have very many items, `isIncomplete` can be used successfully to filter some of the items on your side and on subsequent typing the completion provider will be invoked again.

**Comment by jrieken** [comment]
Yes, the `isIncomplete` flag is to signal to the editor that further typing needs further completion request. Usually, when having typed `f` and triggered intellisense further typing doesn't re-trigger but filters down the list of suggestions. However, when you query some database for suggestions, thing of all tags in your GitHub project, you might have more results as more characters are typed `f -> top 100 results` and `fo -> top 100 results which are disjunct`
