### ISSUE TITLE
[Feature Request]: Get last token from document object

### ISSUE THREAD

**Issue by JJ810** [microsoft/monaco-editor#3921]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

## Description

We are trying to implement our custom language editor but I wanted to ask if there is a method which we can use to get the last token.

i.e:
if expression input is `email.substring(1, 2)`
We want to have `getLastToken()` method which returns `substring(1, 2)`
```ts
document.getLastToken() //  returns substring(1, 2)
```

We are currently using our own helper function by splitting inputs with space
```ts
export const getCurrentTextToken = (
  document: monaco.editor.ITextModel,
  position: monaco.Position
): string => {
  const { lineNumber, column } = position;
  const currentText = document
    .getLineContent(lineNumber)
    .slice(0, column - 2);
  const tokens = currentText.split(" ");
  return tokens[tokens.length - 1];
};
```

The reason why we are NOT splitting it by `.` is because we also have namespaces(i.e: `user.data.email`) and we should get the entire object in order to get the return type and show corresponding suggestions.

Please let me know if there is a way to make this work. Thanks in advance!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
