### ISSUE TITLE
[Bug] Marker endColumn appears to be off by 1

### ISSUE THREAD

**Issue by raopg** [microsoft/monaco-editor#3977]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAKoAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2LesRwLINgRABDcFm89fBOSueOLTYt0aaEwnsLoPwmLxwedOn8Q8TDA7HdG2A53dB9AMwMH_c2UsEDCPbL8A6wc1PFBazlo2fy7TfNZymcFwybCgcaeSebsDkbJ--zzabpsV4SOUUQl0t2NVQaDdjOIcrRaxzomgNv4fxdZ2Z6Iv1zEsomQZKlA8oNE7Brf1mlfhJP0ESTSX_B_fkcZL5n1WLKkTEoZqa7tK0BtkCcOa6ZCjxzvHlLfr2TSPaq0q2eJqGCOMFznWO9JHcWMUR__fY5PQJ00Ltv80GFlZtzDtteYPBfRPYvF8JBI78xd-E3P5CCYwX_lkpDcAhpfDDwouONv5y47--Ph9Sc81UgQxuzVttcwXDQC6hsjT0E2cblgkd1FcZx03CeChmCNTS2PE43rc_dXujj6JctOojmSQJ0pXkg9_6faklZwxFw2KMmkzt51fwJqSi0lOCxn89xUU

### Monaco Editor Playground Code

```typescript
function validate(model) {
	const markers = [];
	// lines start at 1
	markers.push({
				message: "not an integer",
				severity: monaco.MarkerSeverity.Warning,
				startLineNumber: 1,
				startColumn: 1,
				endLineNumber: 1,
				endColumn: 4,
			});
	monaco.editor.setModelMarkers(model, "owner", markers);
}

const value = `12345`;
const uri = monaco.Uri.parse("inmemory://test");
const model = monaco.editor.createModel(value, "demoLanguage", uri);
const editor = monaco.editor.create(document.getElementById("container"), {
	model,
});
validate(model);
model.onDidChangeContent(() => {
	validate(model);
});
```

### Reproduction Steps

Copy and paste the above code in the playground. You will notice that the squiggly lines don't appear on the character 4, but it is expected to, given how the marker is being created.

### Actual (Problematic) Behavior

The squiggly line only appears on `123`

### Expected Behavior

The squiggly line appears on `1234`

### Additional Context

I believe that both the lines and columns start at one. The `endColumn` is not behaving as expected.

**Comment by spahnke** [comment]
I believe this is just a documentation issue. A position in the editor is defined here https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/core/position.ts#L15 and it states that "the first character in a line is between column 1 and column 2". So `column` can be interpreted as a place where the cursor could be placed. Hence you need to add one to your result because you want to stretch the squiggle to the cursor position after the last character you want to mark. As another example: to only mark the first character in a line you would set `startColumn: 1` and `endColumn: 2`.

**Comment by raopg** [comment]
Thanks for the explanation!
