### ISSUE TITLE
The error does not show correctly in Safari on macOS

### ISSUE THREAD

**Issue by Hongbo-Miao** [Microsoft/monaco-editor#417]
The error does not show correctly in Safari on macOS.
Link to https://github.com/OfficeDev/script-lab/issues/298.

monaco-editor version: 0.8.3
Browser: Safari 10.1
OS: macOS 10.12.4

![image](https://cloud.githubusercontent.com/assets/3375461/24978682/6b36c352-1f86-11e7-9592-213d80485173.png)

**Comment by rebornix** [comment]
This problem is actually worse as any hover on Safari doesn't work at all as the child element doesn't inherit correct visibility from parent when we change parent element's visibility from 'hidden' to 'inherit' through Code.

I don't have a minimal html/js code to demonstrate this problem but what I noticed is if we change the visibility manually in Developer Tools, the child element inherits correct visibility.

**Comment by rebornix** [comment]
BTW, we didn't make any code/css change in this area. It's a bug introduced in Safari 10.1, which was released on March 27, 2017.
