### ISSUE TITLE
Consider adding `will-change: transform` even if translate3d if disabled

### ISSUE THREAD

**Issue by nbdd0121** [Microsoft/monaco-editor#426]
monaco-editor version: 0.8.3
Browser: Chrome 57
OS: Windows 10
Steps or JS usage snippet reproducing the issue: set `disableTranslate3d: true` in options

Currently in Chrome, if the browser is not having integer pixel ratio, using `translate3d` will cause texts to be blurry. So I set `disableTranslate3d` to `true` to workaround this issue. However, using `top` instead `translate3d` results in bad performance, since the whole editor has to be repainted when scrolls. The issue is caused since `.lines-content` is not in its own layer. Simply adding `will-change: transform` seems sufficient to keep the div in its own layer without causing the blurry issue.

**Comment by AndersMad** [comment]
check out this one https://github.com/Microsoft/vscode/issues/24599 (covering the first part)

**Comment by nbdd0121** [comment]
@AndersMad I knew about the linked issue and that's why I choose to disable `translate3d`. What I am suggesting here is to add a `will-change: transform` CSS property so that we can get comparable rendering performance even if `translate3d` is disabled.

**Comment by alexandrudima** [comment]
@nbdd0121 So `will-change: transform` by itself acts as a hint to create a new GPU/render layer?

**Comment by nbdd0121** [comment]
@alexandrudima Yes, on Chrome `will-change: transform` creates a new layer (can be verified using DevTools)

**Comment by alexandrudima** [comment]
[Source](https://github.com/operasoftware/devopera/pull/330)

**Comment by alexandrudima** [comment]
I have experimented with `will-change: transform` and read up more about it.

Here are some observations:

### Firefox
on Firefox, we don't use `transform:translate3d(...)` due to [issues with hit-testing](https://bugzilla.mozilla.org/show_bug.cgi?id=1083132). However, when using `paintflashing on`, it appears that Firefox has gotten quite smart and figures out all by itself that only new lines being scrolled into the editor need to be painted, and the other lines moving up can just be moved up by copying pixels around and without needing additional painting. I'm pretty sure this was not the case ~3 years ago, but hooray Firefox:

![ezgif-2-369ca10bc1](https://user-images.githubusercontent.com/5047891/27127887-ea4de13c-50fc-11e7-83b8-426d05ba35e5.gif)

### Chrome

#### Chrome without `transform:translate3d(...)`
When disabling the use of `transform:translate3d(...)` for scrolling, it appears that Chrome paints the entire editor area on each frame. On the bright side, there is no overdraw. From looking at the Layer borders, it appears the editor does not get its own layer:
![editor-426-no-translate3d](https://user-images.githubusercontent.com/5047891/27128283-31362536-50fe-11e7-9df1-715826e73b1d.gif)

#### Chrome with `transform:translate3d(...)`
When using `transform:translate3d(...)`, Chrome figures out that only new lines being scrolled into the editor + regions around old lines being scrolled out of the editor need to be painted:
![editor-426-chrome-translate3d](https://user-images.githubusercontent.com/5047891/27128104-9c602e8e-50fd-11e7-8e0f-3a998602e6fe.gif)

#### Chrome without `transform:translate3d(...)`, but with `will-change:transform`
![editor-426-no-translate-will-change](https://user-images.githubusercontent.com/5047891/27128539-304e0ba6-50ff-11e7-8032-064a3413ae09.gif)

---

I'm not sure yet, but perhaps we can drop the usage of `translate3d` altogether and just use `will-change:transform`. But do we suffer from blurry text with `will-change:transform` too ? @nbdd0121 did you experiment with this ?

I'll do additional measurements...

**Comment by alexandrudima** [comment]
Here I'm just running the ballistic scroll recording I did a while ago:

---

#### Chrome without `transform:translate3d(...)`
<img width="826" alt="screen shot 2017-06-14 at 13 01 09" src="https://user-images.githubusercontent.com/5047891/27129146-94c3de2e-5101-11e7-9fcf-4b54844d269b.png">
<img width="274" alt="screen shot 2017-06-14 at 13 01 49" src="https://user-images.githubusercontent.com/5047891/27129163-a73ebede-5101-11e7-91f2-fd35d376ca04.png">

---

#### Chrome with `transform:translate3d(...)`
<img width="840" alt="screen shot 2017-06-14 at 13 03 19" src="https://user-images.githubusercontent.com/5047891/27129222-dfdc542c-5101-11e7-93ab-627656966b6b.png">
<img width="275" alt="screen shot 2017-06-14 at 13 03 42" src="https://user-images.githubusercontent.com/5047891/27129272-e8affcd4-5101-11e7-8110-1239b4007cc1.png">


---

#### Chrome without `transform:translate3d(...)`, but with `will-change:transform`
<img width="816" alt="screen shot 2017-06-14 at 12 58 44" src="https://user-images.githubusercontent.com/5047891/27129037-3fa9685a-5101-11e7-9039-007ab4249b21.png">
<img width="271" alt="screen shot 2017-06-14 at 12 59 30" src="https://user-images.githubusercontent.com/5047891/27129065-54eea090-5101-11e7-805b-66ffd1778c6c.png">

**Comment by alexandrudima** [comment]
After running multiple times, I don't think there is any difference in Rendering/Painting times between using `transform:translate3d(...)` vs not using `transform:translate3d(...)`, but using `will-change: transform`. I am therefore inclined to completely remove our usage of `translate3d` and simply use `will-change: transform`, since `will-change: transform` does not have the bluriness problem on Windows when using non-integer `window.devicePixelRatio`.

**Comment by alexandrudima** [comment]
I've just replaced our usage of `transform:translate3d(...)` with setting `top`/`left` and hints in the form of `will-change:transform`. 

If anything goes bad, there is a new editor option `editor.disableLayerHinting`. 

The former option `editor.disableTranslate3d` is now no longer supported.
