### ISSUE TITLE
Indentation of a single row deletes selected text in some cases

### ISSUE THREAD

**Issue by foxable** [Microsoft/monaco-editor#443]
monaco-editor version: 0.8.3
Browser: IE/Chrome/Firefox
OS: Windows

**Steps reproducing the issue:**
1. Open the "Hello world!"-example on the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html)
2. Select the first line using your mouse (click left button then move mouse)
3. Press tab at least two times to indent the selected row

**Expected behavior:**
The selected line is indented for each tab press.

**Actual behavior:**
The selected line is only indented for the first tab press. On the second tab press, the row is indented a second time, but the selected text is deleted from the editor.

Note:
The described behavior cannot be observed, if
- the selected row starts with whitespaces or tabs
- the selected row contains a line-break and this line-break is part of the selection (e.g. using triple-click for selecting the complete row or using the keyboard to select the row including the line-break)

**Comment by alexandrudima** [comment]
This is caused by our desire to allow for replacing a selection within a line with a tab. e.g. 
![editor-443](https://user-images.githubusercontent.com/5047891/26970450-c03ebfa2-4d09-11e7-9566-f1776ad699a3.gif)

Perhaps in the case where everything except leading/trailing whitespace is selected on a line, we could indent instead of replacing with a tab.
