### ISSUE TITLE
The undo() and redo() method doesn't appear in monaco.d.ts

### ISSUE THREAD

**Issue by ee-** [Microsoft/monaco-editor#451]
To perform undo/redo operation you could call
````
editor.getModel().undo();
editor.getModel().redo();
````
But the `undo()` and `redo()` method doesn't appear in `IModel` of  `monaco.d.ts`

**Comment by alexandrudima** [comment]
I would not recommend calling `undo()` or `redo()` directly on the `IModel`, since that will undo the edits on the text, but will not restore the cursor position correctly.

I would recommend calling `editor.trigger('whatever...', 'undo')` and `editor.trigger('whatever...', 'redo')` which will end up executing `IModel.undo()` or `IModel.redo()`, but will do so through the context of the cursor which can restore its position correctly.

**Comment by ee-** [comment]
@alexandrudima Thanks ^^
