### ISSUE TITLE
[Bug] when 0.53 monaco-editor version will be released with the vulnerability fix?

### ISSUE THREAD

**Issue by Andrevwvm** [microsoft/monaco-editor#4738]
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [x] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Please answer the question: Do you happen to know when 0.53 monaco-editor version will be released with the vulnerability fix?
https://github.com/microsoft/monaco-editor/issues/4692#issuecomment-2447348884

Monaco editor has CVE which is fixed and not released for a quite some time for now.

**Comment by Andrevwvm** [comment]
Hi @joaomoreno, could you please provide us with some information about the release date? Thanks in advance for your help

**Comment by rogerhendriks** [comment]
https://www.npmjs.com/package/monaco-editor is still 0.52.0
@rzhao271 @mjbvz @joaomoreno can someone please give us a heads up? 
We are desperately awaiting this as all our dependency checks fail, the fix is there and milestone closed. 
Thanks!

**Comment by Andrevwvm** [comment]
[heart]         Andrew Mandruk | Fenêtre bv reacted to your message:
________________________________

**Comment by BerendvanhoekFenetre** [comment]
Hi @rzhao271 @mjbvz @joaomoreno 

As there is no reply in 3 weeks regarding the release date, can we please get an update?
Thanks!

**Comment by acherkashin** [comment]
At least knowing the approx date would be helpful

**Comment by rogerhendriks** [comment]
> Hi [@rzhao271](https://github.com/rzhao271) [@mjbvz](https://github.com/mjbvz) [@joaomoreno](https://github.com/joaomoreno)
> 
> As there is no reply in 3 weeks regarding the release date, can we please get an update? Thanks!

@aiday-mar @hediet

**Comment by dreamofdoc** [comment]
Do you know if new patch update release includes this fix, or we have to wait for minor release (0.53)?

**Comment by dreamofdoc** [comment]
@acherkashin Oh I see, thank you!

**Comment by blutorange** [comment]
Just from the diff between 0.52.2 and 0.52.0 it wasn't clear to me if the patch is really included. But if you take a look at

http://unpkg.com/monaco-editor@0.52.2/esm/vs/base/browser/dompurify/dompurify.js

you can see the the version `DOMPurify 3.1.7`. And according to [CVE-2024-45801](https://nvd.nist.gov/vuln/detail/CVE-2024-45801), it's fixed with DOMPurify `3.1.3`. So it really should be fixed now.

**Comment by hediet** [comment]
Fixed in 0.52.2 (https://github.com/microsoft/monaco-editor/blob/release/0.52/CHANGELOG.md#0521).

> Just from the diff between 0.52.2 and 0.52.0 it wasn't clear to me if the fix is really included. But if you take a look at

This is because the monaco editor is built from the VS Code sources, which we reference [by its commit hash](https://github.com/microsoft/monaco-editor/blob/release/0.52/package.json#L4).

> https://nvd.nist.gov/vuln/detail/CVE-2024-45801

That CVE is about "Inefficient Regular Expression Complexity", which does not play a role for the monaco-editor.
In any case, the warnings should disappear now, as the latest stable monaco editor now ships with a recent version of DOMPurify.
