### ISSUE TITLE
Language support for tcl

### ISSUE THREAD

**Issue by simark** [microsoft/monaco-editor#485]
monaco-editor version: 0.8.3
Browser: any
OS: any
Steps or JS usage snippet reproducing the issue: N/A

Hi!

I happen to have to work with some tcl code, it would be nice to have some basic support (e.g. syntax highlight) for it.  But of course, the more support the better :)

Thanks!

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
