### ISSUE TITLE
feature-request: getValue without comments

### ISSUE THREAD

**Issue by Lor-Saba** [microsoft/monaco-editor#490]
Could you add a parameter to the [.getValue()](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#getvalue); which returns back the editor content without comments?
something like `editor.getValue({ trimComments: true });`

For example, if I have this content: 
```
/*
    old sum function
    function sum(_a, _b){
        return _a + _b;
    }
*/

var a, b;

// add function
function add(_a, _b){
    return _b + _a;
}
```

the `editor.getValue({ trimComments: true });` should return back:
```

var a, b;

function add(_a, _b){
    return _b + _a;
}
```

Same for the other languages (css, html, ...)
   

My use case: I need to know if the editor contains actual code, not just content.

**Comment by yize** [comment]
+1

**Comment by codeStryke** [comment]
+1

**Comment by vicke4** [comment]
+1

**Comment by jasmine-song** [comment]
++1

**Comment by samirzubi-db** [comment]
+1

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
