### ISSUE TITLE
Load only readonly so footprint is smaller

### ISSUE THREAD

**Issue by playpianolikewoah** [microsoft/monaco-editor#516]
I wanted to use the monaco editor and start it in readonly and change to editable mode. I see I can do that with `updateOptions`. This is great. The footprint is still 1.5mb. Can we make the loader load only the code for reading mode and not editing so the footprint isn't so large?

**Comment by rehmsen** [comment]
I would also be interested in this, ideally with an option to lazy-load the rest when the user requests editing.

**Comment by hediet** [comment]
While this is a great feature request, it requires a ton of engineering effort (as write-only contributions would need to be loaded on demand), but at the same time it is very unlikely that this benefits VS Code.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
