### ISSUE TITLE
IPad Pro arrows don't work in editor

### ISSUE THREAD

**Issue by ryskin** [Microsoft/monaco-editor#556]
I tested in Chrome and Safari. That's making very hard to use.

**Comment by svdoever** [comment]
Only editor  found that supports ipad pro with keyboard (I use the logitech keyboard) is http://codeanywhere.com.

**Comment by 0fork** [comment]
I was very excited to find Monaco because it looks fantastic for coding on-the-move but lack of proper ”smart” keyboard support is obviously a showstopper.

I know this is most likely just something that nobody implemented because nobody happened to have iPad Pro so maybe I can help. The codebase is not trivial in size anymore so I was hoping if somebody familiar with the structure could point me to the part of the code where inputs are handled?

**Comment by alexandrudima** [comment]
Duplicate of #293
