### ISSUE TITLE
Consider adding breakpoints and debugging just like full VSCode can

### ISSUE THREAD

**Issue by Meai** [microsoft/monaco-editor#558]
I dont see any reason why this feature should be missing from monaco-editor.

**Comment by rcjsuen** [comment]
@Meai What do you mean by debugging support exactly? Monaco runs on the browser. It's not going to have access to your C++ native executable that's on your local disk.

Or did you mean you just want API to draw a breakpoint icon of some sort in the editor's margins?

**Comment by Meai1** [comment]
@rcjsuen Why not? Debugging just means that there is some kind of database that will be queried on a line by line basis with a GUI on top. 
That information could be queried by means of a protocol, which could be over a network or just by reading from a string in memory.
The point is that I'd like monaco-editor to offer some generic gui that shows locals, breakpoints, allows stepping etc.. VSCode itself has very nice barebones examples of textual debugging a .txt file. Why shouldn't that also be possible in monaco-editor? 
The textfile itself is just text. There isn't even any debug database necessary, yet I can "debug" it.
I want that for monaco-editor too!

If I have some way of running the code that and debug it (=ask debug information while it's running) then I would fill in the monaco-editor gui with the information that I gained from running my code. 
My code will probably run outside of the browser, that is correct but I can communicate with that process via the network.
Here is some further theory, but please keep in mind that I already proved my case via the textline debugging above: In theory my code could be running inside a VM that is running in the browser's javascript VM. Think of a .NET VM that is compiled to wasm and then I'd put in some IL code and run it. All within the browser. 

Here is what I actually built and why I truly need it: I built a code editor like dartpad / golang playground / rustlang playground for my custom language but now I want to offer debugging on top of that. 
So currently in my case each time a user presses 'run' for a given piece of code, I create a new container and send his code via network to my server where it's run in the container. I see no reason why the user shouldn't be able to connect with a debugger to that container so that he can get more than just the end result from that playground run. I want to give him the full debugging experience, while in the browser!

This is *not* a toy feature, I really would like to have it.

**Comment by AntonKrug** [comment]
I would like the debugs hooks as well. OpenOCD could be modified to use WebSockets and then actually browser could interact with even real hardware.

**Comment by lastmjs** [comment]
This could be useful to me as well. I'm currently using the ACE editor in a web application. I have a custom markup language that users can edit, and it can be manipulated from a JavaScript API from the ACE editor. It would be amazing to allow breakpoints to be set in the editor GUI to further ease the users' experience as they write and debug JavaScript directly in the editor.

**Comment by Jelledb** [comment]
+1 this can be very useful for me for the same reason @lastmjs stated.

**Comment by sec0ndhand** [comment]
yep, could totally use this.  Looking at codemirror to implement since it isn't in monaco yet: https://codemirror.net/demo/marker.html

**Comment by akosyakov** [comment]
@sec0ndhand You should use `monaco.editor.ICommonCodeEditor.deltaDecorations` for it.

**Comment by sec0ndhand** [comment]
I wasn't looking for all of the features above, like stepping support and the locals window, I just wanted break points at least, and @akosyakov that is what I was looking for.  Specifically for anyone else searching for debugging with monaco editor, this playground example shows the ability to set break points: [Rendering Glyphs in the Margin](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin)

**Comment by shivajivarma** [comment]
+1

**Comment by vincentLiuxiang** [comment]
+1

**Comment by tejasrivastav** [comment]
Any guidelines on how to add contextmenu to the modelDecorations aka breakpoints.

+1 for this feature, would a save multiple developer a lot time.

**Comment by tejasrivastav** [comment]
There is a private method on the editor instance which generates the GUI for the contextMenu. `editor._contributions["editor.contrib.contextmenu"]._contextMenuService.showContextMenu()`

**Comment by TehWardy** [comment]
Disclaimer: This is totally just a brain dump ... 
I also realise this is a huge ask but with modern roslyn API's in .Net and a little magic i've seen devs perform small miracles in the past so here's my 2p worth ...

We have a custom workflow engine that allows for blocks of code to be written in to the links between the activities in the flow as part of a visual designer experience. 
The engine runs the flow as an azure function execution by dynamically linking known activities together with dynamic functions generated from user input. 

The workflow engine already talks to a signalr Hub in our API layer and streams logging information in real time to the web page the designer is loaded on.

The idea being ...
I could (maybe) make a server side call / message send to "hold the execution and wait instructions on the hub connection". 
Then in the client code "hey here's a hub to which a running debug stream of messages will come from, talk through that and do your thing".

The specifics of course depend a lot on the debug information between the running process and the web page, I'm sort of hoping though that by telling the front end and the back end "hey guys, talk to each other through this hub" monaco's code can figure out the details.

In our case the workflow execution could be serialised in to a large block of code that contained the details of the entire execution which could be loaded in to monaco, so all I would need form the debugger stuff like "hey i'm on line x, here's your locals {json blob}" or something.

I imagine that's not trivial in itself ... then bolting on to that "ok step into" or "step over" ... there's also the issue of the function not living forever but that could be solved with using a docker container or something instead that has a longer lifecycle.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
