### ISSUE TITLE
How do I use EndofLine or DefaultEndofLine Enums?

### ISSUE THREAD

**Issue by CoderESalazar** [Microsoft/monaco-editor#559]
https://github.com/Microsoft/monaco-editor/blob/4930b6aff505b72e966fcfa54ade4e33d6abe3f8/monaco.d.ts#L1279

Really could use some help on how to use endofline and/or defaultendofLine enums in Monaco-Editor. I have the editor working but I can't get the editor to handle carriage returns without having to manually enter a ' \ ' at the end of each of line where I need a carriage return.  Also, spacing is not respected. Has anyone run into this issue? I have text (javascript) entered into editor being saved into a backend database. Any help would be greatly appreciated.

**Comment by alexandrudima** [comment]
Sorry, I'm not sure what your problem is.

The editor accepts a JavaScript string as the value to display. It will then split this string into lines, looking for `\r\n` or `\r` or `\n`. You can read the string value of the editor via `ed.getModel().getValue()`. Typically, this call will return the lines, joined by the same line separator that was used when the editor was created.

Hopefully you can further explain what you're trying to do, or perhaps you can validate that everything is fine in your DB layer by using a `<textarea>` for presenting the text for testing purposes, and getting everything working correctly in your app by using a `<textarea>`. Once everything is fine in your XHR calls / DB layer / etc. you can replace the front-end `<textarea>` with a monaco editor.

**Comment by CoderESalazar** [comment]
Thanks for responding to my question. I was able to resolve my issue, see Monaco-Editor Single String From Database

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Monaco-Editor Single String From Database

Been researching for the last couple of days and still no result. I have a back-end database that saves text ent...
 |

 |

 |



Sorry if my question was confusing, I just wasn't entirely able to explain the odd behavior. Anyways, once I was able to replace the new line breaks into an acceptable format, the "div" container was able to properly display the returned string. 



    On Tuesday, November 7, 2017, 8:31:26 AM PST, Alexandru Dima <notifications@github.com> wrote:  
 
 
Sorry, I'm not sure what your problem is.

The editor accepts a JavaScript string as the value to display. It will then split this string into lines, looking for \r\n or \r or \n. You can read the string value of the editor via ed.getModel().getValue(). Typically, this call will return the lines, joined by the same line separator that was used when the editor was created.

Hopefully you can further explain what you're trying to do, or perhaps you can validate that everything is fine in your DB layer by using a <textarea> for presenting the text for testing purposes, and getting everything working correctly in your app by using a <textarea>. Once everything is fine in your XHR calls / DB layer / etc. you can replace the front-end <textarea> with a monaco editor.
