### ISSUE TITLE
Inconsistent propagation of keyboard events from widgets

### ISSUE THREAD

**Issue by foxable** [microsoft/monaco-editor#566]
monaco-editor version: 0.10.0
Browser: IE/Chrome/Firefox
OS: Windows

__Steps reproducing the issue:__

1. Open the "Hello world!"-example on the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html)
2. Register a keyboard event listener using the Monaco API, e.g.
    `editor.onKeyDown(function()  { console.log("keyDown"); });`
3. Trigger the suggestions widget (`Ctrl + Space`), then press `Escape`
    Result: closes the suggestions widget and triggers a keyboard event on the editor
4. Now open the search widget (`Ctrl + F`), then press `Escape`
    Result: closes the search widget, but does __not__ trigger a keyboard event on the editor

__Expected behavior:__
Either both keyboard events are propagated to the editor or none. To me, the latter one is the preferred variant, since I'm trying to distinguish keyboard events triggered when widgets are active from those without active widgets. In specific, I'm trying to trigger an application-specific close behavior (e.g. if the editor is used within a modal) whenever `Escape` is pressed within the editor. However, I want to prevent this behavior if there is any widget active within the editor.

**Comment by alexandrudima** [comment]
`editor.onKeyDown` propagates an event when the focus is within the editor text. i.e. typically when the cursor is blinking in the editor. The editor can contain various other widgets, e.g.:
* find widget
* rename widget (F2)
* quick pick widget (F1) and go to line (ctrl+g)
* embedded editors

This event will not fire when focus is in those other widgets.

The suggest widget does not take focus from the editor, that's why the keydown when using the suggest widget is received.
