### ISSUE TITLE
monaco-editor as a chrome extension: path problem

### ISSUE THREAD

**Issue by jawil** [microsoft/monaco-editor#575]
monaco-editor version: the newest
Browser:Google Chrome
OS: Mac OS
Steps or JS usage snippet reproducing the issue:

I am in the development of a Chrome plug-in time, encountered a very difficult mistake. I configured all the path to run the code, the callback function has been unable to implement, the browser error is as follows.

![](https://ws2.sinaimg.cn/large/006tNc79gy1fj47ndzwefj30fm05h74y.jpg)

my demo:

```JavaScript
let path = chrome.extension.getURL('node_modules/monaco-editor/dev/vs')

require.config({ paths: { 'vs': path } })

let entrance = chrome.extension.getURL('node_modules/monaco-editor/dev/vs/editor/editor.main')

document.querySelector('.js-file-line-container').innerHTML = '111111'

console.log(1)

require(['vs/editor/editor.main'], function(ele) {
    
    console.log(22)
    console.log(monaco,33333)
    var editor = monaco.editor.create(document.querySelector('.js-file-line-container'), {
        value: [
            'function x() {',
            '\tconsole.log("Hello world!");',
            '}'
        ].join('\n'),
        language: 'javascript'

    });
})
```

**Comment by PyvesB** [comment]
Unsure what your problem is without seeing the extension's _manifest.json_ or the different versions of the modules you are using. However, if you want to see an example of the Monaco Editor running within a Chrome extension/Firefox add-on, you can take a look at our [Codext](https://github.com/bbc/codext) extension. The key points are to flag resources as `web_accessible_resources` ones and inject _require.js_ and _vs/loader.js_ as content scripts. 😉
