### ISSUE TITLE
Find/Replace widget position

### ISSUE THREAD

**Issue by valekask** [microsoft/monaco-editor#633]
monaco-editor version: 0.10.0
Browser: Chrome
OS: MacOX

When Find/Replace widget is opened, all lines move down and empty space appears at the top of the editor.
I don't find any option which allow to fix lines and don't move them down. I looked at EditorFindOptions and OverlayWidget interfaces. I also tried "fixedOverflowWidgets" editor option, but it did not help me.

I think it would be nice to have such option.

**Comment by mofux** [comment]
I can reproduce it on the playground, and it looks like a bug to me. It happens if the editor is scrollable.

Reproduce:
- Have enough text to scroll
- Open find widget (e.g. CMD+F)
- Scroll down a bit, than scroll back up. Notice that a gap at the top was created that only disappears if you close the find widget.

![find offset](https://user-images.githubusercontent.com/2785983/32901615-91d89628-caf0-11e7-8867-d087b717f90d.gif)

**Comment by valekask** [comment]
Also reproduced when there is no scroll. The same steps on playground:

![monaco-editor-find-widget](https://user-images.githubusercontent.com/423133/32902278-a38a902e-cafa-11e7-9895-c8ce7c6c9451.gif)

**Comment by mofux** [comment]
Actually, this is probably a feature rather than a bug, to have the user see highlighted search results that would otherwise be hidden underneath the widget. I would still be interested to know if this feature can be turned off somehow...

**Comment by valekask** [comment]
Yes, it seems like a feature and usually it's very useful, but it would be nice to have ability to control this behavior.

**Comment by kent08ian** [comment]
Any updates on this?

**Comment by alexdima** [comment]
We now have an option for this. You can use `monaco.editor.create(..., { find: { addExtraSpaceOnTop: false } })`.
