### ISSUE TITLE
Find all References shows hidden Areas

### ISSUE THREAD

**Issue by wysisoft** [microsoft/monaco-editor#645]
![image](https://user-images.githubusercontent.com/15177964/33235987-c545fd56-d203-11e7-9d2e-c805aa9f9648.png)

As you can see from the screenshot, I have a lot of hidden code, but it shows in the find all references area

**Comment by alexandrudima** [comment]
Yes, the notion of a hidden area is one that exists per editor view. The outer editor and the inner editor have two distinct views and two distinct view models (that's why they can be scrolled independently, have a different geometry, etc.), each with their own possible hidden areas.

**Comment by alexandrudima** [comment]
P.S. The hidden areas are something built explicitly for folding regions and here it appears they are "abused" for language service purposes. I suggest forking `monaco-typescript` if necessary and modifying it to your needs rather than doing such hacks to get typings working correctly in your environment.
