### ISSUE TITLE
Intellisense not working after a hash character

### ISSUE THREAD

**Issue by mdschweda** [Microsoft/monaco-editor#650]
monaco-editor version: 0.10.1
Browser: Chrome, Firefox, Edge
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

```js
monaco.languages.registerCompletionItemProvider("handlebars", {
    triggerCharacters: [ "{", "#", "/" ],
    provideCompletionItems: function(model, position) {
        let suggestions = [
            {
                label: "foo",
                kind: monaco.languages.CompletionItemKind.Variable,
                documentation: "...",
                insertText: "foo"
            }
        ];
        console.log(suggestions);
        return suggestions;
    }
});

let editor = monaco.editor.create(document.getElementById("container"), {
    language: "handlebars"
});
```

---

I was trying to provide custom code completion for application specific handlebar templates when I found this behaviour:

For the CompletionItemProvider above, suggestions are made on pressing <kbd>{</kbd> and <kbd>/</kbd>, but not for <kbd>#</kbd>.

More specifically, the Intellisense window won't show up or is empty (<kbd>CTRL</kbd>+<kbd>Space</kbd>) when the cursor is right next to the hash character. Strangely enough, the console output is printed out.

This seems to be an issue specific to HTML-like languages (`"html"`, `"handlebars"`, `"razor"` etc.). The stripped-down example works as expected after changing the language from `"handlebars"` to say `"python"`.

**Comment by alexandrudima** [comment]
This might have something to do with the word definition of the current language. This is something each language defines and the suggest code AFAIK uses the word definition to establish a context...

Here is the word pattern for HTML --- https://github.com/Microsoft/monaco-languages/blob/master/src/html.ts#L17

And here is the word pattern for python ---`/(-?\d*\.\d\w*)|([^\`\~\!\@\#\$\%\^\&\*\(\)\-\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\?\s]+)/g` --- the default one since it doesn't overwrite it.

**Comment by jrieken** [comment]
Yeah, when you word-pattern includes things like `#` and when you provide completion without a range then we compare the completion with the current word, e.g. compare `#` with `foo` which results in no match. I'd recommend to set the `range` property of the suggestions.
