### ISSUE TITLE
Tab character ignored in signatureHelpTriggerCharacters

### ISSUE THREAD

**Issue by rsbondi** [microsoft/monaco-editor#658]
monaco-editor version: 0.10.1
Browser: chrome/electron
OS: W10
Steps or JS usage snippet reproducing the issue:

```javascript
monaco.languages.register({id:'mine'})
monaco.languages.registerSignatureHelpProvider('mine', {
    provideSignatureHelp: function (model, position) {
         return {
            activeSignature: 0,
            activeParameter: 0,
            signatures: [{label: 'handler triggered', parameters: [{label: 'triggered', documentation: 'tab not working'}]}]
          }
     },
    signatureHelpTriggerCharacters:[' ', '\t', '\n']
})
monaco.editor.create(document.getElementById("container"), {
	value: "something",
	language: "mine"
});
```
space and enter work, tab does not

**Comment by alexdima** [comment]
Tab is not programmed to do anything at this point when having parameter hints.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
