### ISSUE TITLE
Ability to import SCSS files.

### ISSUE THREAD

**Issue by nekitozzz** [microsoft/monaco-editor#661]
I want to import some external variables in .SCSS file. For TypeScript it's possible to import additional files using addExtraLib method. Is there something like this for SCSS?

**Comment by aeschli** [comment]
The SCSS support is currently single file only, that means we don't follow any imports. It's the same in VSCode. There are VSCode feature requests for that, but there are currently no concrete plans to implement that.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
