### ISSUE TITLE
Including the loader script throws exception

### ISSUE THREAD

**Issue by TyOverby** [Microsoft/monaco-editor#662]
When I add 
```
<script src="./vs/loader.js"></script>
```

I get 

```
Error: Can only have one anonymous define call per script file
loader.js:7:19290
s</s.prototype.enqueueDefineAnonymousModule
http://localhost:8080/vs/loader.js:7:19290
o
http://localhost:8080/vs/loader.js:7:26855
<anonymous>
http://localhost:8080/deps/react-dom.js:12:5
<anonymous>
http://localhost:8080/deps/react-dom.js:5:3
```

**Comment by alexandrudima** [comment]
AFAIK we don't ship with `react-dom.js`, so I believe this error has something to do with your environment (i.e. all the things that you include in your HTML page).

**Comment by salcosta** [comment]
I don't completely understand the issue here but for some reason if you try to load AMD after the Monaco loader it breaks.  Perhaps the functions are not interchangeable?  Depending on what happens after this point it will cause havoc on the page.

To fix this issue I just waited for the page to fully load, then I included the Monaco loader (I used jQuery.getScript).  I am assuming, although I did not verify, that when you do this Monaco would use the AMD loader instead of defining its own.  For what it's worth if they are not interchangeable there should be a `noConflict` mode.

**Comment by mlynch** [comment]
I've run into this as well, and not using react. Something changed between monaco 0.10.1 and 0.11.0 inside of monaco itself. I'm using monaco in electron, and followed this guide which I'm guessing is now out of date: https://github.com/Microsoft/monaco-editor-samples/tree/master/electron-amd

**Comment by gaastonsr** [comment]
I'm getting the same error and I don't use React either.

**Comment by alexandrudima** [comment]
I have pushed a more simple variant at https://github.com/Microsoft/monaco-editor-samples/blob/master/electron-amd/electron-index.html

This works fine with Electron 2.0.9, I just tried it. (P.S. even the old sample worked fine with Electron 2.0.9, but I have simplified it a bit).

**Comment by willdelphia** [comment]
I am getting the `Uncaught Error: Can only have one anonymous define call per script file` error when I attempt to include monaco in a wordpress gutenberg context. (Gutenberg is built on top of react). 

Interestingly everything works fine, but there is a lot of red in the console. Is there any way to fix this?

**Comment by alexandrudima** [comment]
@willdelphia That means you are loading a library/script that invokes the AMD `define` function. You could try to search your other scripts for `define` calls and remove them if you're not using AMD for them or you could try to load the loader only after those problematic scripts have finished loading. Alternatively, you can load the scripts that call `define` with the loader itself.
