### ISSUE TITLE
Awesome Monaco

### ISSUE THREAD

**Issue by mofux** [microsoft/monaco-editor#699]
It would be awesome if you could provide a central place that lists monaco extensions (language providers, language servers, themes etc.) similar to https://github.com/bnb/awesome-hyper and link it in the README of this repository. If people create something useful, they can file a PR against that repo to get added to the list. I believe there is a strong monaco community out there, let's make it visible!

**Comment by sw-yx** [comment]
i needed this too. i've gone ahead and created it on my own. https://github.com/sw-yx/awesome-monaco-editor contribs welcome

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
