### ISSUE TITLE
APIs to define formatting rules

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#723]
I am trying to add a formatter to a custom language in Monaco Editor. I know we can use 

```
monaco.languages.registerDocumentFormattingEditProvider(...)
monaco.languages.registerDocumentRangeFormattingEditProvider(...)
monaco.languages.registerOnTypeFormattingEditProvider(...)
```

In each of the above APIs, we need to define a provider, e.g., [provideDocumentFormattingEdits](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.documentformattingeditprovider.html#providedocumentformattingedits) that returns a [TextEdit](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.textedit.html). In the TextEdit, we need to return a text, which will replace the initial text.

One way to construct the text of TextEdit, is to manually transfer the initial text by e.g., [replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) or inserting `\n`. But, I am wondering whether there is any existing APIs to simplify this process. For example, is there any way to set indentation/newline rules based on tokens?

Does anyone know?

**Comment by SidhantUnnithan** [comment]
@chengtie I'm trying to define a formatter for a custom language and I coudn't find a proper guide/documentation. When you say 

> In the TextEdit, we need to return a text, which will replace the initial text.

What do you mean? Could you please explain with an example? 
And also, suppose I want to insert a tab space `\t` after every word, what would the `TextEdit` look like?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
