### ISSUE TITLE
Implement Gherkin Language

### ISSUE THREAD

**Issue by AndreasKarz** [microsoft/monaco-editor#745]
monaco-editor version: 0.10.1
Browser: All
OS: All
Please implement Gherkin Language File

**Comment by NabaragRebaca** [comment]
Any ETA for this feature?

**Comment by AndreasKarz** [comment]
Hi @NabaragRebaca  -- all our Product Owners and ScrumMasters work with VSC to edit the Gherkin Specs. So, in VSC it works fine, you can select GHERKIN without problem and then you ave the colors and all other things. our idea is, that they also can edit the Specs directly in the AzureDevOps Code Editor.

**Comment by Purus** [comment]
While VS Code supports gherkin format, how can we enable it for the monoco editor?  Any steps or guide to implement this, please.

**Comment by rcjsuen** [comment]
> 
> 
> While VS Code supports gherkin format, how can we enable it for the monoco editor? Any steps or guide to implement this, please.

I think syntax highlighting support is somewhat documented in [monaco-languages](https://github.com/microsoft/monaco-languages/blob/master/README.md).

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
