### ISSUE TITLE
Modularize Command Registration Architecture

### ISSUE THREAD

**Issue by TheLarkInn** [microsoft/monaco-editor#760]
*monaco-version*: master

I was looking at the examples provided to showcase how to pull in the ES Modules from Monaco and bundle them with webpack. Specifically in the context of this code snippet from examples: 

```js
(1) Desired editor features:
import 'monaco-editor/esm/vs/editor/browser/widget/codeEditorWidget.js';
import 'monaco-editor/esm/vs/editor/browser/widget/diffEditorWidget.js';
import 'monaco-editor/esm/vs/editor/browser/widget/diffNavigator.js';
import 'monaco-editor/esm/vs/editor/contrib/bracketMatching/bracketMatching.js';
import 'monaco-editor/esm/vs/editor/contrib/caretOperations/caretOperations.js';
import 'monaco-editor/esm/vs/editor/contrib/caretOperations/transpose.js';
import 'monaco-editor/esm/vs/editor/contrib/clipboard/clipboard.js';
import 'monaco-editor/esm/vs/editor/contrib/codelens/codelensController.js';
import 'monaco-editor/esm/vs/editor/contrib/colorPicker/colorDetector.js';
import 'monaco-editor/esm/vs/editor/contrib/comment/comment.js';
import 'monaco-editor/esm/vs/editor/contrib/contextmenu/contextmenu.js';
import 'monaco-editor/esm/vs/editor/contrib/cursorUndo/cursorUndo.js';
import 'monaco-editor/esm/vs/editor/contrib/dnd/dnd.js';
import 'monaco-editor/esm/vs/editor/contrib/folding/folding.js';
import 'monaco-editor/esm/vs/editor/contrib/format/formatActions.js';
import 'monaco-editor/esm/vs/editor/contrib/goToDeclaration/goToDeclarationCommands.js';
import 'monaco-editor/esm/vs/editor/contrib/goToDeclaration/goToDeclarationMouse.js';
import 'monaco-editor/esm/vs/editor/contrib/gotoError/gotoError.js';
import 'monaco-editor/esm/vs/editor/contrib/hover/hover.js';
import 'monaco-editor/esm/vs/editor/contrib/inPlaceReplace/inPlaceReplace.js';
import 'monaco-editor/esm/vs/editor/contrib/linesOperations/linesOperations.js';
import 'monaco-editor/esm/vs/editor/contrib/links/links.js';
import 'monaco-editor/esm/vs/editor/contrib/multicursor/multicursor.js';
import 'monaco-editor/esm/vs/editor/contrib/parameterHints/parameterHints.js';
import 'monaco-editor/esm/vs/editor/contrib/quickFix/quickFixCommands.js';
import 'monaco-editor/esm/vs/editor/contrib/referenceSearch/referenceSearch.js';
import 'monaco-editor/esm/vs/editor/contrib/rename/rename.js';
import 'monaco-editor/esm/vs/editor/contrib/smartSelect/smartSelect.js';
import 'monaco-editor/esm/vs/editor/contrib/snippet/snippetController2.js';
import 'monaco-editor/esm/vs/editor/contrib/suggest/suggestController.js';
import 'monaco-editor/esm/vs/editor/contrib/toggleTabFocusMode/toggleTabFocusMode.js';
import 'monaco-editor/esm/vs/editor/contrib/wordHighlighter/wordHighlighter.js';
import 'monaco-editor/esm/vs/editor/contrib/wordOperations/wordOperations.js';
import 'monaco-editor/esm/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp.js';
import 'monaco-editor/esm/vs/editor/standalone/browser/inspectTokens/inspectTokens.js';
import 'monaco-editor/esm/vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard.js';
import 'monaco-editor/esm/vs/editor/standalone/browser/quickOpen/quickOutline.js';
import 'monaco-editor/esm/vs/editor/standalone/browser/quickOpen/gotoLine.js';
import 'monaco-editor/esm/vs/editor/standalone/browser/quickOpen/quickCommand.js';
import 'monaco-editor/esm/vs/editor/standalone/browser/toggleHighContrast/toggleHighContrast.js';
```

These kind of includes removes hopes for treeshaking or DCE pieces of implementations that don't end up getting used. 

So I'd like to propose a bit of rearch to the `registerCommand`, editor command registry and keybinding registry. 

Goals: As a developer I want to have full control over how and what commands are registered, and whether or not they are async or sync registrations. As a developer I want to use Monaco's capabilities and ensure that I'm not shipping unused code. 

Instead of the bare import, could each of these coreCommands, export all of the commands themselves as modules.

Then as a user I could write: 

```js
const editor = monaco.editor.create()

editor.registerCommand(() => import("./core/commands/cursorLeft"));
```

This is a very small and pseudocode like example but it derives from wanting to trim out as much as humanly possible from editor bundles. In most cases when using the examples in the GitHub repo, only about 60% of the bundled code gets used on the first load. Also by doing this, we should attempt to remove any sideEffects created against reexported modules, which would allow monaco-editor to leverage the new webpack 4 sideEffects: false feature.

The goal in the end from a technical / module bundling stance would be to remove any need for bare imports. Happy to help iterate over this.

**Comment by rebornix** [comment]
@TheLarkInn thanks for your feedback ;)

> These kind of includes removes hopes for treeshaking or DCE pieces of implementations that don't end up getting used.

Can you elaborate more about why it's about treeshaking/DCE but not code splitting? Here we do synchronous/top-level imports as we want to those commands to be registered, which meansthey are not going to be eliminated.

> `editor.registerCommand(() => import("./core/commands/cursorLeft"));`

As we didn't bundle these contribution/command files, users do have full power of how and what commands are registered. @alexandrudima gave a sample of how you can bundle editor core and contributions (they don't necessarily need to be commands) together. If you want to postpone the registration of contributions, like after the editor is created, you can do following

```
const editor = monaco.editor.create()

monaco.editor.onDidCreateEditor( e => {
  import("./core/commands/cursorLeft"));
  import("...")
});
```

IMO Webpack will do code split with above code and ensure the contribution bundles are loaded lazily. Above is just an example of loading contributions after the first editor being created, you can also load necessary contrib/feature after a specific language being used, a non-readonly model being created, etc.

> we should attempt to remove any sideEffects created against reexported modules, which would allow monaco-editor to leverage the new webpack 4 sideEffects: false feature.

I'd like to know more about this as currently it seems we didn't see any treeshaking/dce with webpack bundling, the webpack bundled+minified code is larger than our AMD-min version. Not sure if it's because we write code like `import * as abc from 'abc'` or it's due to this `sideEffects` feature.

**Comment by TheLarkInn** [comment]
Now that I have a bit more time (sorry initial post was a bit hurried), I'll do a more indepth analysis soon!

**Comment by rebornix** [comment]
@TheLarkInn thanks and that covers most of our discussions. You help me understand [*side-effects*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) in ESM and figured out which part of code is dead code easily with webpack ;)

Our major discussion is about dynamic module loading, how, when and what. Right now a good example in Monaco is language features ([1](https://github.com/Microsoft/monaco-languages/blob/master/src/bat/bat.contribution.ts#L16)), the language related module will be dynamiclly loaded and evaluated only when that language is required. To provide a out-of-box feature-complete editor, we bundled [coreCommands](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/controller/coreCommands.ts). It works pretty well most of the cases but since it's still large (1.3 MB after bundle and minification), we can look into whether we can better modularize it. Some rough ideas

* For users only need readonly editor (like Dev Tools most of the time), part of the core commands can be lazy loaded (it would lead to bad experience but if 99% of the model is readonly, then it's worthwhile)
* To create a thorough Monaco API, Diff Editor is bundled and contributes 100KB. We can probably make it as a plugin/contribution.

Another good finding is about how we check `process`, `platform`, etc, whose value is static in Monaco environment (like process is `undefined`, `isBrowser` can be `true`). This makes tree shaking in our shared code with VSCode (`/base`, `/platform`) possible. Webpack has a plugin for this and I need to look into if it really helps or what blocks Webpack from removing unnecessary code.

**Comment by alexdima** [comment]
I don't see us moving away from the self-registration pattern. Reasons:
- self-registration avoids code duplication in VSCode, VSCode web, Monaco Editor. If someone else would need to import the code and register things, then this "importing and registering" would need to be written at least 3 times, and potentially N times, by each Monaco Editor user if they choose to go with loading a subset of the editor
- we are already doing tree-shaking. We do tree-shaking when extracting the editor from VS Code's sources and we do it in TypeScript, so we know when it is safe to remove members of classes.
