### ISSUE TITLE
Error on dispose() after completion/suggestions has been shown (highlightedLabel is null)

### ISSUE THREAD

**Issue by AndersMad** [Microsoft/monaco-editor#772]
monaco-editor version: 0.11.1
Browser: Chrome

**Error:** "Cannot read property 'dispose' of undefined"

**Where:** at Renderer.disposeTemplate (suggestWidget.ts:179)

**Cause:** the `highlightedLabel` is null at code call on main editor dispose:
```
e.prototype.disposeTemplate = function(e) {
    e.highlightedLabel.dispose(),                    <-- error - highlightedLabel is null
    e.disposables = l.dispose(e.disposables)
```

**Repro:** In fresh editor (any e.g. css), CTRL + SPACE open suggestion list, ESC to close, now call the myEditor.dispose();

This error is new in 0.11 vs. prior version

**Comment by mohamedmansour** [comment]
I am getting the same issue (reported there #318)

```
    at Renderer.disposeTemplate (editor.main.js:102769)
    at PipelineRenderer.disposeTemplate (editor.main.js:24341)
    at editor.main.js:16068
    at Map.forEach (<anonymous>)
    at RowCache.garbageCollect (editor.main.js:16064)
    at RowCache.dispose (editor.main.js:16076)
    at editor.main.js:4023
    at Array.forEach (<anonymous>)
    at Object.dispose (editor.main.js:4023)
    at ListView.dispose (editor.main.js:23703)
```

I am doing the following:


```
    ngOnDestroy() {
        if (this._editor) {
            this._editor.getModel().dispose();
            this._editor.dispose();
        }
    }
```

**Comment by felixfbecker** [comment]
@alexandrudima I might be wrong, but I have a suspicion that https://github.com/Microsoft/vscode/commit/472ede044204c03e390797841c1e76cb89b710c8 is only a workaround for the actual issue.
First of all, this is the stack trace I am getting:
```
Renderer</Renderer.prototype.disposeTemplate
suggestWidget.js:162
PipelineRenderer</PipelineRenderer.prototype.disposeTemplate
listWidget.js:612
RowCache</RowCache.prototype.garbageCollect/<
rowCache.js:66
forEach self-hosted:3625:9 RowCache</RowCache.prototype.garbageCollect
rowCache.js:62
RowCache</RowCache.prototype.dispose
rowCache.js:74
_dispose/<
lifecycle.js:20
forEach self-hosted:261:13 _dispose
lifecycle.js:20
ListView</ListView.prototype.dispose
listView.js:465
_dispose/<
lifecycle.js:20
forEach self-hosted:261:13 _dispose
lifecycle.js:20
List</List.prototype.dispose
listWidget.js:1075
SuggestWidget</SuggestWidget.prototype.dispose
suggestWidget.js:884
SuggestController</SuggestController.prototype.dispose
suggestController.js:165
CommonCodeEditor</CommonCodeEditor.prototype.dispose
commonCodeEditor.js:107
CodeEditorWidget</CodeEditorWidget.prototype.dispose
codeEditorWidget.js:115
StandaloneEditor</StandaloneEditor.prototype.dispose
```
When breaking on this exception in a debugger, I can see that `templateData` passed to `disposeElement` is an `HTMLElement`:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/10532611/38721143-d57d83c6-3ead-11e8-9570-a0f3438e54ff.png">

even though it _should_ be `ISuggestionTemplateData`, an object.
There is no reason why `ISuggestionTemplateData.highlightedLabel` would be `undefined`, but of course the property does not exist on an HTMLElement.

I wondered how this could happen with TypeScript. Following the stack trace further, I can see that it is forwarded in [`PipelineRenderer.disposeTemplate()`](https://github.com/Microsoft/vscode/blob/f7ec491c3ed5cea258e144da873504a98582b7de/src/vs/base/browser/ui/list/listWidget.ts#L824), which takes `any[]` as parameter. So that's why there is no compile error.
And we can see there is a bug in the code:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/10532611/38721849-a611a9fc-3eb0-11e8-828e-0dfd734ed4b7.png">

`i` doesn't get incremented so it will iterate over the renderers, but always pass the first `templateData`, which in this case is the wrong type.

This code snippet doesn't exist anymore in upstream VS Code and was fixed already a month ago:

https://github.com/Microsoft/vscode/commit/2454b3448208b40c2b70be68ef57e8677f1b6457

So https://github.com/Microsoft/vscode/commit/472ede044204c03e390797841c1e76cb89b710c8 at this point seems like it is handling a case that was broken in a way worse way but can't happen anymore.

**Comment by alexandrudima** [comment]
:+1: I could not reproduce ... so I added a random `if` statement. Thanks for tracking this down! Cleaned up via https://github.com/Microsoft/vscode/commit/622eab8bebbe5a7b228cf890fc3ca1665a49bcf1
