### ISSUE TITLE
Can we have concatenated .js files for production?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/monaco-editor#78]
Rather than manually concatenate the separate portions of node_modules/monaco-editor/min/vs, can we have a drop of the non-worker files concatenated together? It would make onboarding Monaco onto existing website projects a bit easier.

**Comment by alexandrudima** [comment]
The split into files is driven by two factors:

1) reduce load times: e.g. why load 2MB of typescript compiler code if your project only ever exercises php files. That is why each language gets its own .js file that gets loaded only when you exercise the language.

2) when creating a web worker you must specify the script path and load scripts independently. You cannot just say "fork" me this current executing source code, you have to point to its script.

I would love to simplify things, and I am definitely open for suggestions, but the editor does more than a `<textarea>` replacement widget (loads languages on demand, spins up web workers on demand, etc.).

**Comment by sirisian** [comment]
@alexandrudima Regarding point 2, not sure how portable it is, but I've been using code like the following for a while in Chrome:

```js
await new Promise(resolve => {
	const blobURL = URL.createObjectURL(new Blob([MyFunction.toString(), '(', function() {
		onmessage = e => {
			({ foo } = e.data);
			const result = MyFunction(foo);
			postMessage(result);
		}
	}.toString(), ')()'], { type: 'application/javascript' }));
	const worker = new Worker(blobURL);
	URL.revokeObjectURL(blobURL);
	worker.onmessage = e => {
		worker.terminate();
		resolve(e.data);
	};
	worker.postMessage({ foo: 5 });
}
```
It lets you spawn workers with code all in the same file.

**Comment by alexdima** [comment]
@sirisian :+1: Thank you for the tip. 

We also use that technique for bootstrapping the web workers in the cross-origin case (when the JS is served from a different domain than the HTML) -- https://github.com/microsoft/vscode/blob/0230c97caf2f02c9fa3e3f1f4fbccf82ac7870ad/src/vs/base/worker/defaultWorkerFactory.ts#L36-L42

However, to inline the entire worker code, it means that the code would have to be loaded as a string on the UI thread (to support all browsers since `Function.toString()` is not in the EcmaScript spec AFAIK).

The first issue, of on-demand loading would remain... i.e. even if we load all the worker code as a string and inline that in the `editor.main.js`, the size of that will become equal to the sum of all sizes, approximately 6MB.

**Comment by JoshuaKGoldberg** [comment]
It's been quite a while since I posted this and I no longer have any desire for it to be resolved. Closing to keep my issues queue small 😄
