### ISSUE TITLE
DidChangeDecorations events not working

### ISSUE THREAD

**Issue by neoncom** [microsoft/monaco-editor#787]
monaco-editor version: 0.11.1
Browser: chrome newest
OS: win 10 64 bit
Steps or JS usage snippet reproducing the issue:

`editor.onDidChangeModelDecorations`
or
`editor.getModel().onDidChangeDecorations`

both return an empty object ({}). tested in my project and in monaco editor playground

in 0.10.1 it worked perfectly

**Comment by alexandrudima** [comment]
The event sent out no longer lists the decorations that were changed. This has been done in order to improve the speed of decorations. See https://github.com/Microsoft/vscode/pull/36410

You can, on your side keep track of the ranges you set on decorations. Then, in the `onDidChangeDecorations` callback, you can read the ranges for the decorations from the editor and figure out if your decorations have been changed.
