### ISSUE TITLE
Contrast ratio not met for xml files in theme vs

### ISSUE THREAD

**Issue by sibille** [Microsoft/monaco-editor#818]
We're using monaco editor with theme "vs"
Contrast ratio is less than 4.5:1 for xml files.

![image](https://user-images.githubusercontent.com/24698018/38739744-14796a58-3f36-11e8-849d-e1366f255271.png)

Do you provide a theme that meets color contrast specification or should we customize the colors to meet the specification?

Thanks!!

**Comment by alexandrudima** [comment]
AFAIK the colors for the default (vs) theme are taken from the Visual Studio default theme. This happened 6+ years ago, so the Visual Studio default theme might have changed. I suggest we do whatever Visual Studio is doing.

P.S. users can always press F1 > Toggle High Contrast Theme in order to turn on the high contrast theme in browsers like Chrome or on operating systems other than Windows.

**Comment by sibille** [comment]
Thanks for the quick answer!!

**Comment by alexandrudima** [comment]
Please see https://github.com/Microsoft/monaco-editor/wiki/Accessibility-Guide-for-Integrators
