### ISSUE TITLE
Some strings not localized

### ISSUE THREAD

**Issue by joechung-msft** [microsoft/monaco-editor#822]
monaco-editor version:
0.9.0 and later (including latest, 0.14.3)

Browser:
All

OS:
All

Steps or JS usage snippet reproducing the issue:
Use the test page for German localizations at https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-localized/index.html

The following sections of localizable strings are not localized:
* vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp
* vs/editor/standalone/browser/inspectTokens/inspectTokens
* vs/editor/standalone/browser/quickOpen/gotoLine
* vs/editor/standalone/browser/quickOpen/quickCommand
* vs/editor/standalone/browser/quickOpen/quickOutline
* vs/editor/standalone/browser/standaloneCodeEditor

0.14.3 example:
![image](https://user-images.githubusercontent.com/26208574/45992483-0722e480-c03f-11e8-9862-7515ed3220bc.png)

**Comment by alexandrudima** [comment]
@dbaeumer Are we pushing/pulling these strings to transifex ?

**Comment by dbaeumer** [comment]
@alexandrudima no they are not :-)

**Comment by dbaeumer** [comment]
Resource that are pushed to transifex need to be listed in `build\lib\i18n.resources.json`. I have added the standalone editor part.

**Comment by dbaeumer** [comment]
Actually the file has a vs\editor section so standalone should be included by default. Need to see why this is not the case ?

**Comment by dbaeumer** [comment]
Reopening the issue. Actually this is more complicated. What be push to transifex is what we bundle into our `large` JS files (the stuff that gets produced by the optimze step). Since the `standalone` folder is not bundled we don't upload any resource to transifex. This was done to not translated anything that we don't ship. Two options:

- we tolorate this. I am not sure what our statement regarding translating the standalone editor is
- we add an item to our deb to change the VS Code transifex push task to allow for not bundled resources.

**Comment by dbaeumer** [comment]
@alexandrudima opinions ?

**Comment by dbaeumer** [comment]
We could treat the standalone like an extension and try to resuse some code from there.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/48108

**Comment by joechung-msft** [comment]
It looks like an intern accidentally removed these localizations in this commit:
3af180691c ("Cleaned up unused translation files. Merged translations from Transifex.", 2017-04-26)

**Comment by joechung-msft** [comment]
Any progress to report on this issue?  Microsoft/vscode#48108 was closed with a sound explanation (not wanting to push all of vscode's resource strings to monaco-editor).  However, it isn't clear how the issue here will be resolved.

**Comment by dbaeumer** [comment]
@alexandrudima adding you as well based on the discussion from yesterday. I will try to summarize:

- things got more complicated since we are publishing the editor now as AMD and UMD and in UMD we can't use the tricks we use for AMD (a loader plugin to inject the translations very early into the loader process)
- VS Code got converted to language packs and we need to think about how the standalong editor could reuse the translations


An alternative would be to publish the keys and the English strings and to ask every product that embeds the stand alone editor to translate these strings. This would at the end be the cleanest solution since the strings we would pull from the VS Code translation might have the term `VS Code` in the translated value.

**Comment by jayspadie** [comment]
Thank you for making this a priority.  Localization issues will block us from taking a newer Monaco release in Azure DevOps, and there are a fixes/changes over the past few months that we'd love to deploy.  Please just let us know when more information is available so we can plan accordingly.

**Comment by dbaeumer** [comment]
I revived that translation for the Monaco editor in the build process. See https://github.com/Microsoft/vscode/issues/71065

**Comment by trevorade** [comment]
So, am I correct in that all localizations are completely busted in Monaco at the moment?

When I run `npm install monaco-editor` and navigate to: `/node_modules/monaco-editor/min/vs/editor`
All of the `editor.main.nls.XY.js` files are in English.  I see no localizations at all for any of the files presently.

**Comment by joechung-msft** [comment]
Closed with 0.17.0.  Thanks! :)
