### ISSUE TITLE
Extended cursor get confused by line endings

### ISSUE THREAD

**Issue by abrudz** [microsoft/monaco-editor#863]
monaco-editor version: 0.12.0.
Browser: Firefox Quantum 59.0.3
OS: Windows 10 Pro

Extending the cursor into lines that are too short (or moving part of an extended cursor beyond the end of its line) causes the cursor to be split up into separate pieces. Instead, the cursors should be allowed to move beyond the shorter lines until the longest line's end has been reached. Only then should the cursor wrap down one line.

![multiple cursors fail](https://user-images.githubusercontent.com/10961427/39694066-e35532b2-51dd-11e8-8c4d-adb5baaa7654.gif)

**Comment by alexandrudima** [comment]
@abrudz 
Perhaps you prefer the commands:
* `cursorColumnSelectDown` - <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>down</kbd>
* `cursorColumnSelectLeft` - <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>left</kbd>
* `cursorColumnSelectRight` - <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>right</kbd>
* `cursorColumnSelectUp` - <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>up</kbd>

Instead of the ones you appear to be using:
* `editor.action.insertCursorBelow` - <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>down</kbd>
* `cursorLeft` - <kbd>left</kbd>
* `cursorRight` - <kbd>right</kbd>
* `editor.action.insertCursorAbove` - <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>up</kbd>

**Comment by abrudz** [comment]
(Rectangular selection is useful — thanks! However…)

I don't see how that behaves any better. True, the cursor gets "gaps" where a line isn't long enough, but when moving the cursor, it seems to transform into the the same type as the simple extended cursor:
![monaco-block](https://user-images.githubusercontent.com/10961427/39804610-6b2e0d96-536c-11e8-88df-cae9e0abe193.gif)

**Comment by alexandrudima** [comment]
@abrudz Please feel free to implement a better version of arrow left and arrow right if you would like to use a different one on your website. We will not modify the one we ship with, as that is something pretty standard in editors.

e.g.
```
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

// Now arrow left never leaves the current line if there are multiple cursors
var myBinding = editor.addCommand(monaco.KeyCode.LeftArrow, function() {
    editor.setSelections(editor.getSelections().map((s) => {
        let lineNumber = s.startLineNumber;
        let column = Math.max(1, s.startColumn - 1);
        return new monaco.Selection(lineNumber, column, lineNumber, column);
    }));
}, "editorHasMultipleSelections");
```
