### ISSUE TITLE
API for TypeScript formatting options

### ISSUE THREAD

**Issue by npenin** [microsoft/monaco-editor#88]
Hi,

I would like to be able to have the opening bracket of code blocks in javascript and typescript on a new line. Is there such an option in the editor ?

Thanks,
Nicolas

**Comment by alexdima** [comment]
This is implemented [here](https://github.com/microsoft/monaco-typescript/blob/c050127710f42d57b249504f95f97d32d01ea7cb/src/languageFeatures.ts#L581-L599) and is currently not configurable.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
