### ISSUE TITLE
Implement folding provider for markdown

### ISSUE THREAD

**Issue by purocean** [microsoft/monaco-editor#905]
monaco-editor version: 0.13.1

```js
      this.editor = window.monaco.editor.create(window.document.getElementById('editor'), {
        value: this.value,
        language: 'markdown',
        theme: 'vs-dark',
        fontSize: '20',
        folding: true
      })
```

not work :(

**Comment by rcjsuen** [comment]
Markdown support might not be complete in the Monaco Editor. You can try looking at [this file](https://github.com/Microsoft/vscode/blob/61591c8585649cf0d86f2c9bf491afea0fa9c45c/extensions/markdown-language-features/src/features/foldingProvider.ts) for inspiration I suppose.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
