### ISSUE TITLE
How to support emmet?

### ISSUE THREAD

**Issue by hstarorg** [microsoft/monaco-editor#93]
When I type 'div', it not insert text '&lt;div>&lt;/div>'.

Can it support emmet like vscode?

**Comment by devmondo** [comment]
same issue here, really this is the only thing preventing us from using monaco :(

**Comment by hstarorg** [comment]
Yes, it is very important.

**Comment by egamma** [comment]
sorry, but emmet support is currently part of the VS Code workbench layer and not part of the monaco editor. Changing this is not on our immediate radar.

**Comment by leon-andria** [comment]
Do we have a roadmap or whatever ? This is like a must today for any kind editors.

**Comment by hstarorg** [comment]
@egamma Would you provider a plugin to support it?

**Comment by egamma** [comment]
We track the work on the monaco editor on the [VS Code Roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap). The items on the roadmap have higher priority to us for the next 6-12 months, sorry.

**Comment by hstarorg** [comment]
Okay, also thank you very much.

**Comment by hstarorg** [comment]
I provided a lib to support emmet in monaco, it's [https://github.com/hstarorg/emmet-monaco](https://github.com/hstarorg/emmet-monaco).

**Comment by kenyk7** [comment]
Also add Emmet integration for css files

**Comment by troy351** [comment]
Guys I've wrote a lib to support emment, too.
almost the same behavior as emmet in WebStorm and doesn't influence suggest completion & tab insert.
see at [https://github.com/troy351/emmet-monaco](https://github.com/troy351/emmet-monaco)

**Comment by hb1048317543** [comment]
How to support emmet?

**Comment by profstein** [comment]
Adding my vote here for this feature natively. Even just the ability to type an element name and hit tab to expand (without having to type the angle brackets) would help. I came here because I was checking out repl.it but have found I am just too used to writing HTML using Emmet to be able to use it. Everything feels so slow and awkward without it.

**Comment by techwithanirudh** [comment]
Check out tailwind's implementation for emmet [https://github.com/tailwindlabs/play.tailwindcss.com/blob/master/src/monaco/emmet.js](url)

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
