### ISSUE TITLE
Why the event 'IStandaloneCodeEditor.onDidFocusEditor' is triggered before 'IStandaloneCodeEditor.onDidBlurEditor' when I click an editor with focusing another editor?

### ISSUE THREAD

**Issue by Lushenggang** [Microsoft/monaco-editor#930]
monaco-editor version: 0.13.1
Browser: Chrome
OS:  Windows 10
Steps or JS usage snippet reproducing the issue:

There are two editors on a page, editor1 and editor2.
JSCode:

      editor.onDidFocusEditor((event) => {
        console.log('show')
      })
      editor.onDidBlurEditor((event) => {
        console.log('hide)
      })

step1: focus editor1. 
step2: focus editor2. The question is appeared, why the log info is
"
show
show
 hide
"
where we expect the log to be 
''
show
hide
show
''
?

**Comment by alexandrudima** [comment]
`onDidFocusEditor` and `onDidBlurEditor` work via timeouts. In the next version of the editor they will be called `onDidBlurEditorWidget` and `onDidFocusEditorWidget`.

That event is trying to keep track if the focus is anywhere within the monaco editor (including for example, in the find widget). For example, when being in an editor, and moving focus to the find widget, the DOM will emit a `blur` event on the input textarea (here we register a timeout), and in the next stack will emit a `focus` event on the find widget input. In the timeout callback we check if the focus is still in the editor and then emit `onDidBlurEditor` (`onDidBlurEditorWidget` in future releases) as necessary.

So, the blur event we emit is asynchronous because we need to check where the focus lands before we can emit it...

For synchronous events, you can use `onDidBlurEditorText` and `onDidFocusEditorText`, which reflect what happens to our input textarea. But then you need to handle the case that focus was moved to the find widget or to some other editor widget (like the rename widget or perhaps an embedded editor via find all references, etc).
