### ISSUE TITLE
event.preventDefault does not prevent the default behaviour for some keys in onKeyDown

### ISSUE THREAD

**Issue by brijeshb42** [microsoft/monaco-editor#940]
monaco-editor version: 0.13.1
Browser: chrome
OS: mac
Steps or JS usage snippet reproducing the issue:

On this [page](https://microsoft.github.io/monaco-editor/), open debugger and add this code snippet-

```js
editor.onKeyDown((e) => {console.log(e); e.preventDefault()})
```

Now try typing in some character in the main editor. These characters will not be added.

But pressing `backspace` or `CTRL+D` deletes the characters instead of not doing anything.

**Comment by alexandrudima** [comment]
The `preventDefault` function is the one that comes from all browser events, that's why it will prevent typing.

If you wish to remove default keybindings, you can register commands on those keybindings that do nothing. e.g. https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-key-events

**Comment by alexandrudima** [comment]
See https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance

You can register commands and use the context keys (e.g. `inInsertMode` or `inNormalMode`) and then manage those context keys from your side.

**Comment by robpaveza** [comment]
So we’re currently having trouble with this bubbling up to the document-level keydown handler for Escape when the InteliSense menu is up. If I register a command during this state, it won’t dismiss the code completion list. If I don’t register the handler, the keyboard event escapes your control. 

I’ve seen this pushback on several issues and I don’t really understand where it comes from. If your control is handling a User Input event, it’s because your control has special knowledge about the state of the program that it has under its control. In that case, it should either swallow the event entirely (preventDefault, etc.) or expose it as a separate observable event from the control (such as editor.onHandledKeyDown).

**Comment by alexandrudima** [comment]
This is complicated because the editor is pulled out from VS Code. In VS Code, we have a single `IKeybindingService` that registers on `document` a single `keydown` listener. This `IKeybindingService` works by dispatching key combinations, when their conditions hold, to command invocations (invokes a function). This is a system which works pretty well and allows for user-level customization of the keybinding rules, allows for 3rd party extensions to contribute rules, etc.

The editor is authored primarily for VS Code. We ship at as a separate project because we thought it might be useful for others, but primarily, the reason of existence of the editor is VS Code.

In the standalone editor, the story of a single `IKeybindingService` that installs a single listener on the `document` window does not work because here we are running in widget mode, where we should not do anything outside our container dom node. So, in the standalone editor we create an `IKeybindingService` per editor instance.

On top of how keys -> commands dispatching works, we have added some key events where we forward events received in the `<textarea>` which always has focus when the cursor is blinking in the editor.

So, there are two distinct things:
* keys -> commands dispatching (that is done by the `IKeybindingService` and that listens in the standalone editor case in the editor's dom node.
* keydown listening via the `onKeyDown`, `onKeyUp`, etc.

I'm sorry the two stories don't line up perfectly for your use-case and that there exists this extra complexity.
