### ISSUE TITLE
IE F12 tools crash on monaco playground

### ISSUE THREAD

**Issue by sandyarmstrong** [microsoft/monaco-editor#97]
**Steps to reproduce:**
1. Visit https://microsoft.github.io/monaco-editor/playground.html (any sample) in IE 11.494.10586.0
2. Press F12
3. Wait a couple of seconds

**Expected results:**

F12 dev tools open and can be used to debug the editor samples.

**Actual results:**

F12 dev tools open, but before they finish loading, the IE process crashes. Typically, the page will reload at this point.

I'm on Windows 10 if that helps. Other random websites work fine with F12 tools.

**Comment by sandyarmstrong** [comment]
I've seen a few reports of IE F12 tools crashing, for example https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7115490/ .

Figured I'd file in case it's something that can be fixed in the demo.

**Comment by T18970237136** [comment]
Hi,
note that the crash in IE11 only occurs on Windows 10 (Version 1511 / 1607). When using IE 11 on Windows 8.1 or Windows 7, no crash occurs.

**Comment by sandyarmstrong** [comment]
Confirmed, no crash in 8.1.

**Comment by alexandrudima** [comment]
Also, Edge does not crash. I'm thinking it is an F12 issue. fyi @roblourens

**Comment by roblourens** [comment]
It's code in IE, and I think I see the bug associated with that crash. I don't know if there's a workaround for Monaco but it might be related to that bug linked above. It should be fine in Edge. fyi @andysterland

**Comment by alexdima** [comment]
The Monaco Editor is generated from the source code of VS Code and in order to improve VS Code we must be able to use modern browser features, like Flexbox, which has a number of bugs that we cannot workaround in IE11.

We have investigated the cost of fixing all the problems of IE11 and have decided to discontinue support for IE 11. The last Monaco Editor version that was tested on IE 11 is `0.18.1`.

Thank you for your understanding.
